### ISSUE TITLE
problem installing TF 

### ISSUE THREAD

**Issue by daitory** [ROCmSoftwarePlatform/tensorflow-upstream#1000]
OS: Ubuntu 18.04

Video card
Radeon 580 Mobile
![image](https://user-images.githubusercontent.com/20446075/83833194-60b72f80-a6b9-11ea-8767-2d94964609ae.png)

OPENCL
![image](https://user-images.githubusercontent.com/20446075/83833280-952aeb80-a6b9-11ea-84f1-44572acb94e5.png)

Rocm Packages:
![image](https://user-images.githubusercontent.com/20446075/83833353-bb508b80-a6b9-11ea-9e35-cd647aacb32a.png)

/opt/rocm/lib :
![image](https://user-images.githubusercontent.com/20446075/83833698-88f35e00-a6ba-11ea-9d5d-94aeaa35d985.png)

Rocm version
![image](https://user-images.githubusercontent.com/20446075/83833789-bfc97400-a6ba-11ea-865e-6f8d56517371.png)

MAIN PROBLEM AFTER INSTALL TENSORFLOW-ROCM

![image](https://user-images.githubusercontent.com/20446075/83833867-f4d5c680-a6ba-11ea-8cc7-e1930dc4bae3.png)

**ImportError: libmcwamp.so.3: cannot open shared object file: No such file or directory**

thank you in advance

**Comment by sunway513** [comment]
Hi @daitory , can you refer to the following issue that has been resolved:
https://github.com/RadeonOpenCompute/ROCm/issues/1126
Basically you'll need to update your TF wheel packages along with the ROCm base version upgrades. You can also refer to the following document:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

**Comment by daitory** [comment]
I didi it but I receive this other error
![image](https://user-images.githubusercontent.com/20446075/83916832-da93fb00-a743-11ea-88f1-cd7ac02fb39f.png)

**Comment by sunway513** [comment]
@daitory , it seems your user bit ROCm environment has not been properly configured.
Please follow the ROCm document and try to clean up your existed ROCm installations before upgrading to ROCm3.5:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
Or you can pull our pre-built docker containers:
https://hub.docker.com/r/rocm/tensorflow

**Comment by daitory** [comment]
@sunway513 
I Did what you said, Fresh install Ubunut 18.04 , Rocm 3.5.0 and Tensorflow - Rocm 2.2.0

Additionally , I had to install rocm-libs,  miopen-hip , rccl 

Just before Tensorflow

And finally 

![image](https://user-images.githubusercontent.com/20446075/83958394-22e41380-a83f-11ea-829a-fe5278bcb2e8.png)


Thank you Mr, Without your help It wouldnt be possible

**Comment by sunway513** [comment]
Hi @daitory , thanks and great to know it's working now :-)
