### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by DeonRich** [ROCmSoftwarePlatform/tensorflow-upstream#1001]
**System information**
- Ubuntu 20.04
- TensorFlow 2.2.0
- Python version: 3.8.2
- Installed via pip 
- ROCm/MIOpen version: 3.5.0
- GPU model and memory: RX 5600XT

tensorflow is installed correctly. But when I try to run "tf_cnn_benchmarks.py --num_gpus=1 --batch_size=32 --model=resnet50" I get segmentation fault (core dumped)
I also tried running my own program and it says "WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU"

**Comment by jerryyin** [comment]
RX 5600 is a RDNA gaming card. I don't think we support this card. 

You can take a look at the output of `$ /opt/rocm/bin/rocminfo` to get your gfx architecture number. Then refer to [here](https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support) for the list of supported hardware.
