### ISSUE TITLE
F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)

### ISSUE THREAD

**Issue by papadako** [ROCmSoftwarePlatform/tensorflow-upstream#1002]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- Linux Ubuntu: 20.04
- TensorFlow installed from: pip
- TensorFlow version: 2.2.0
- Python version: 3.8
- GPU model and memory: Radeon VII 16GB
- rocm: 3.5 installed from: ppa
- Linux kernel: 5.7.0

Running a classifier using BERT I get the following error during training

```
Epoch 2/15
 192/1152 [====>.........................] - ETA: 1:10 - loss: 0.7163 - acc: 0.48962020-06-08 11:17:25.462278: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
```

**Comment by jerryyin** [comment]
Could you start with a release docker [here](https://hub.docker.com/r/rocm/tensorflow/tags) and make sure you can reproduce the issue?

Also, to make sure ROCm is configured correctly, follow the installation guide [here](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html).

**Comment by papadako** [comment]
Well, unfortunately I can not use the current docker since it is based on xenial and python3.5
```
Collecting bert-for-tf2
  Downloading bert-for-tf2-0.14.4.tar.gz (40 kB)
     |################################| 40 kB 1.0 MB/s 
ERROR: Could not find a version that satisfies the requirement py-params>=0.9.6 (from bert-for-tf2) (from versions: 0.1.5, 0.1.9, 0.2.0, 0.2.1, 0.2.4, 0.3.1, 0.4.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.9, 0.6.12, 0.7.3, 0.7.4, 0.8.1, 0.8.2, 0.8.3, 0.9.0)
ERROR: No matching distribution found for py-params>=0.9.6 (from bert-for-tf2)
```

**Comment by jerryyin** [comment]
Our officially supported and tested TF is 16.04. If the model has to be run in 20.04 then please submit a new issue when 20.04 is supported.
