### ISSUE TITLE
libhip_hcc.so not found in rocm-3.5.1

### ISSUE THREAD

**Issue by codecor-cn** [ROCmSoftwarePlatform/tensorflow-upstream#1019]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:2.2.0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version:3.5.1
- GPU model and memory:4GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory

the libhip_hcc.so is a symbolic link to libamdhip64.so  in /opt/rocm-3.5.1/hip/lib/libhip_hcc.so
but not found
/opt/rocm-3.5.1/hip/lib/ have already in ld.so.conf

**Comment by helfio** [comment]
I am experiencing this same error after upgrading from 3.5.0.
My case:

OS Platform and Distribution: Ubuntu 18.04 LTS (up to date)
TensorFlow installed from: pip install rocm-tensorflow
TensorFlow version: 2.2.0
Python version: 3.6.9
Installed using: pip in virtualenv environment
ROCm/MIOpen version: 3.5.1
GPU model and memory: RX 590 8GB

**Comment by witeko** [comment]
You need to reinstall (uninstall 3.5 and install 3.5.1).

**Comment by papadako** [comment]
> You need to reinstall (uninstall 3.5 and install 3.5.1).

I have the exact same problem. I removed all rocm packages and then re-installed but unfortunately the error message is still there.
`2020-06-23 15:10:17.516520: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory
Aborted (core dumped)
`

**Comment by codecor-cn** [comment]
> > You need to reinstall (uninstall 3.5 and install 3.5.1).
> 
> I have the same exact problem. I removed all rocm packages and then re-installed but unfortunately the error message is still there.
> `2020-06-23 15:10:17.516520: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory Aborted (core dumped) `



> > You need to reinstall (uninstall 3.5 and install 3.5.1).
> 
> I have the same exact problem. I removed all rocm packages and then re-installed but unfortunately the error message is still there.
> `2020-06-23 15:10:17.516520: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory Aborted (core dumped) `

i try to reinstall to 3.5.1 and change /etc/ld.so.conf.d/ but still error. untill i use LD_LIBRARY_PATH declare the rocm librarys. it's ok

**Comment by papadako** [comment]
I guess this is a problem with the packaging of ubuntu deb files. Maybe it should be kept open until the packages are fixed?

**Comment by papadako** [comment]
I guess this issue should be kept open. A lot of users have problems with the current deb packages.

AMD, please improve your QC

Other references to the same issue
#1022 and also https://github.com/tensorflow/tensorflow/issues/40751

**Comment by papadako** [comment]
#1022

**Comment by Chr0m0s0m3s** [comment]
issue fixed using the following commands
```
cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
ldconfig

```

**Comment by witeko** [comment]
@codecor-cn in my case no "magic tricks" were necessary, I just reinstalled

**Comment by vuquocan1987** [comment]
> > > You need to reinstall (uninstall 3.5 and install 3.5.1).
> > 
> > 
> > I have the same exact problem. I removed all rocm packages and then re-installed but unfortunately the error message is still there.
> > `2020-06-23 15:10:17.516520: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory Aborted (core dumped) `
> 
> > > You need to reinstall (uninstall 3.5 and install 3.5.1).
> > 
> > 
> > I have the same exact problem. I removed all rocm packages and then re-installed but unfortunately the error message is still there.
> > `2020-06-23 15:10:17.516520: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory Aborted (core dumped) `
> 
> i try to reinstall to 3.5.1 and change /etc/ld.so.conf.d/ but still error. untill i use LD_LIBRARY_PATH declare the rocm librarys. it's ok

Same for me, I can't just update the /etc/ld.so.conf.d/. If I update LD_LIBRARY_PATH on terminal it works temporally. This is not a permanent solution as  this only work in current terminal. If I use visualcode or pycharm, it doesn't work at all ( as I can't set LD_LIBRARY_PATH permanently ). How do you solve this?

**Comment by papadako** [comment]
Just try this
As root you should:
a) cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
b) ldconfig (the first letter is L - this is used for updating the links/cache of shared libraries, you can run it from anywhere)

I am not sure though what is the root cause of the problem. /opt/rocm/lib/libhip_hcc.so never gets cached

**Comment by papadako** [comment]
Running `ldconfig -v` shows the weird result `libamdhip64.so.3 -> libhiprtc.so` for /opt/rocm/lib.
I would expect a link like `libhiprtc.so -> libamdhip64.so.3`. So I guess maybe there are some cyclic dependencies?

A workaround that I am currently using is to:

a) Delete libhiprtc.so from /opt/rocm/lib

b) Add a file rocm-hip.conf in /etc/ld.so.conf.d with the following content (needs root permission)
`/opt/rocm/hip/lib`

c) Run `ldconfig` as root

Then everything should work as expected
