### ISSUE TITLE
Invalid argument: Input to reshape is a tensor with 4300800 values, but the requested shape has 19268370432

### ISSUE THREAD

**Issue by papadako** [ROCmSoftwarePlatform/tensorflow-upstream#1026]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version:
- GPU model and memory: Radeon VII

Hi,

I am using bert-for-tf2 over tensorflow 2.2.0,  keras 2.4.3, and the AMD rocm 3.5.1 environment, and sometimes I get an error like the following one:

File "bert-decept.py", line 543, in
history = fit_model(model, data, BATCH_SIZE, EPOCHS, tensorboard_callback, model_checkpoint_callback,
File "bert-decept.py", line 438, in fit_model
history = model.fit(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 766, in fit
return func.fit(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 649, in fit
return fit_loop(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 386, in model_iteration
batch_outs = f(ins_batch)
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 3631, in call
fetched = self._callable_fn(*array_vals,
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1470, in call
ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: Input to reshape is a tensor with 4300800 values, but the requested shape has 19268370432
[[{{node bert_1/encoder/layer_7/attention/self/query/Tensordot}}]]
[[Func/training_2/AdamW/gradients/gradients/bert_1/encoder/layer_7/output/dropout_62/cond_grad/StatelessIf/then/_11515/input/_23174/_9837]]
(1) Invalid argument: Input to reshape is a tensor with 4300800 values, but the requested shape has 19268370432
[[{{node bert_1/encoder/layer_7/attention/self/query/Tensordot}}]]
0 successful operations.
0 derived errors ignored.

or

File "bert-decept.py", line 543, in
history = fit_model(model, data, BATCH_SIZE, EPOCHS, tensorboard_callback, model_checkpoint_callback,
File "bert-decept.py", line 438, in fit_model
history = model.fit(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 766, in fit
return func.fit(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 649, in fit
return fit_loop(
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 386, in model_iteration
batch_outs = f(ins_batch)
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 3631, in call
fetched = self._callable_fn(*array_vals,
File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1470, in call
ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: Size 0 must be non-negative, not -1737945760
[[{{node bert/encoder/layer_5/attention/self/query/Tensordot/Reshape}}]]
[[Func/training/AdamW/gradients/gradients/bert/encoder/layer_9/output/dropout_30/cond_grad/StatelessIf/then/_696/input/_2295/_3389]]
(1) Invalid argument: Size 0 must be non-negative, not -1737945760
[[{{node bert/encoder/layer_5/attention/self/query/Tensordot/Reshape}}]]

At least in my non-experienced eyes it seems like an invalid pointer reference. The error does not happen for the CPU backend. Does anyone have any idea/insight about what might be the problem? Is there any other information that I could probably provide to solve this?

Best regards
Panagiotis

**Comment by jerryyin** [comment]
@ekuznetsov139 Mind take a look at the user case? There could be gap in terms that the user is using `bert-for-tf2` and that of using ROCm 3.5.1. From the look of it, the shape of dropout related node get corrupted into a negative value. Technically this does not necessarily indicate a framework issue, but could be a model issue as well.

@papadako We'd need your script and steps to reproduce to continue the investigation.

**Comment by ekuznetsov139** [comment]
This looks unpleasantly like #325, which was a hard-to-debug synchronization issue in the hip-hcc backend. The switch to hip-vdi backend may have exposed a similar issue. 

I'll see if I can reproduce this running bert as usual on 3.5.1, but, if that does not work, I'll need the specific script and detailed steps to reproduce.

**Comment by papadako** [comment]
Thanks for the replies. I will try to create a small code example that exposes reproducibly the problem (if possible since I am not able to reproduce it reliably up to now).

**Comment by papadako** [comment]
Can you provide any guidelines about how someone can extract more helpful debugging information for resolving this? Also any kind of environmental variables from https://rocmdocs.amd.com/en/latest/Other_Solutions/Other-Solutions.html that I can use to test if the problem occurs or not?

The problem usually appears after a number of runs, during a model hyper-parameter tuning process

**Comment by ekuznetsov139** [comment]
You could try to set AMD_SERIALIZE_KERNEL=3, AMD_SERIALIZE_COPY=3, TF_NUM_INTEROP_THREADS=1 and see if the problem still happens. (Note: the link calls them HCC_SERIALIZE_KERNEL and HCC_SERIALIZE_COPY, but, since 3.5, they are called AMD_... ). That should eliminate most of the timing and multithreading related randomness and the bug will either go away or become more consistently reproducible, in which case we can look into logging. The trouble with logging is that running bert with any kind of meaningful logging enabled will easily push the log file into the gigabyte range.

**Comment by papadako** [comment]
Hi,

I tried all of the above flags. Both of the AMD_SERIALIZE_KERNEL=3 and AMD_SERIALIZE_COPY=3 stuck the training process (is this a known issue?). 

With the TF_NUM_INTEROP_THREADS=1 things seemed to progress, but at step 56 out of the 60 steps of the tuning process I got the following relevant error:


NEW RUN!  56

Parameters: 
lr: 1.5e-05 dropout: 0.05 max length: 125 seed: 42 batch size: 16

3424it [00:04, 701.60it/s] 
861it [00:01, 725.27it/s] 
max seq_len 1472
max seq_len 125

Train on 3081 samples, validate on 343 samples
Epoch 1/20
3081/3081 [==============================] - 116s 38ms/sample - loss: 0.6371 - acc: 0.6446 - val_loss: 0.5345 - val_acc: 0.7609
Epoch 2/20
3081/3081 [==============================] - 107s 35ms/sample - loss: 0.5546 - acc: 0.7546 - val_loss: 0.5332 - val_acc: 0.7638
Epoch 3/20
3081/3081 [==============================] - 98s 32ms/sample - loss: 0.5058 - acc: 0.8014 - val_loss: 0.5516 - val_acc: 0.7434
Epoch 4/20
3081/3081 [==============================] - 99s 32ms/sample - loss: 0.4761 - acc: 0.8302 - val_loss: 0.5833 - val_acc: 0.7201
Epoch 5/20
3024/3081 [============================>.] - ETA: 1s - loss: 0.4438 - acc: 0.8628Traceback (most recent call last):

  File "bert-decept.py", line 548, in <module>
    history = fit_model(model, data, BATCH_SIZE, EPOCHS, tensorboard_callback, model_checkpoint_callback,
  File "bert-decept.py", line 438, in fit_model
    history = model.fit(
  File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 766, in fit
    return func.fit(
  File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 649, in fit
    return fit_loop(
  File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 386, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 3631, in __call__
    fetched = self._callable_fn(*array_vals,
  File "/home/papadako/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1470, in __call__
    ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 6144000 values, but the requested shape has 169030955081564160
         [[{{node bert/encoder/layer_6/intermediate/Tensordot}}]]
         [[bert/encoder/layer_7/attention/self/dropout_22/cond/then/_330/dropout/Mul/_3125]]
  (1) Invalid argument: Input to reshape is a tensor with 6144000 values, but the requested shape has 169030955081564160
         [[{{node bert/encoder/layer_6/intermediate/Tensordot}}]]
0 successful operations.
0 derived errors ignored.

**Comment by papadako** [comment]
Upgrading to rocm 3.7 seems to have resolved my issue (I have been fine-tuning a BERT model for almost a day)!
