### ISSUE TITLE
rocm 3.5 resnet50 benchmark regression 192 (v3.3) -> 86 (v3.5) img/sec

### ISSUE THREAD

**Issue by caius72** [ROCmSoftwarePlatform/tensorflow-upstream#1038]
**System information**
- Linux Ubuntu 20.04):
- TensorFlow installed: pip3 install tensorflow-rocm
- TensorFlow version: v2.2.0-30-g34c3143 2.2.0
- Python version: 3.8
- GPU model and memory: Vega64 8GB

**Describe the current behavior**
----------------------------------------------------------------
total images/sec: 86.47
----------------------------------------------------------------
**Describe the expected behavior**

----------------------------------------------------------------
total images/sec: 192.5
----------------------------------------------------------------
**Standalone code to reproduce the issue**

python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=64 --model=resnet50

**Comment by jerryyin** [comment]
Thanks for reporting. We are aware of the performance degrade with ROCm 3.5 and have internal ticket to track it. The suggested workaround is just to keep using ROCm 3.3. @deven-amd Please leave a comment if you have anything to add.

**Comment by jerryyin** [comment]
Tested `rocm/tensorflow-autobuilds:rocm3.7-latest` on a ROCm 3.7 Vega 10 and confirmed images/sec back to 193.76. Closing the Issue now.
