### ISSUE TITLE
"crosstool_wrapper_driver_is_not_gcc" build fail

### ISSUE THREAD

**Issue by cmburn** [ROCmSoftwarePlatform/tensorflow-upstream#1047]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10 Buster, backports kernel 5.6.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: HEAD git branch
- Python version:3.8
- Installed using virtualenv? pip? conda?: included scripts with git clone
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): GCC-8.3.0
- ROCm/MIOpen version: 3.5.0
- GPU model and memory: Radeon VII, 16GB

1. git clone https://github.com/ROCmSoftwarePlatform/tensorflow-upstream
2. cd tensorflow-upstream
3. ./build_rocm_xla_python3 or ./build_rocm_python3 (both have the same failure)

This is the kicked off error:
ERROR: /home/charlie/tensorflow-upstream/tensorflow/python/tools/BUILD:226:1 C++ compilation of rule '//tensorflow/core/kernels:cwise_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 

Let me know if there's a fix! Everything i've seen online was for nvidia GPUs.

**Comment by jerryyin** [comment]
You have two options as workaround:

- To compile by yourself, make sure to copy over the the workaround as indicated [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L121-L126).
- To use a pre-built docker, start with below:
   `$ docker pull rocm/tensorflow-autobuilds:latest`
