### ISSUE TITLE
2 seconds per step with batch_size 16 for mobile_netV2

### ISSUE THREAD

**Issue by rickrickrickyyy** [ROCmSoftwarePlatform/tensorflow-upstream#1056]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.4 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):v2.2.0-30-g34c3143 2.2.0
- Python version:3.6.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: none
- rocm-libs Version: 3.5.0-30
- GPU model and memory: radeon 7 16G

**Describe the current behavior**
2 seconds per step with batch_size 16 for mobile_netV2

**Describe the expected behavior**
faster than this,  because my laptop with lower spec is running faster than this. 
but when I run the benchmark 
`python tf_cnn_benchmarks.py --num_gpus=1 --batch_size=128 --model=resnet50
` 
on radeon I got total images/sec about  200.

**Comment by jerryyin** [comment]
Thanks for reporting this issue @rickrickrickyyy. Would it be possible for you to test this in an earlier ROCm version, say ROCm 3.3? Full instructions on installation and uninstallation please refer to [here](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html).

Or a quick way to experiment is to use an existing docker: `docker pull rocm/tensorflow-autobuilds:rocm3.3-latest`

**Comment by witeko** [comment]
@jerryyin on 3.3 works just as slow. At least it used to (I tried to train it some time age - but it was for sure on 3.3).

**Comment by witeko** [comment]
@jerryyin still slow on rocm 3.7 and tf21
tf23 doesnt work for me at all (doesnt even build)

**Comment by jerryyin** [comment]
@sunway513 Could you help follow-up with this issue related with `tf_cnn_benchmarks`? I had very little idea of what the right number should look like.

**Comment by jerryyin** [comment]
Now that ROCm3.7 related docker images are out, I'd recommend to give them a shot: [here](https://hub.docker.com/repository/registry-1.docker.io/rocm/tensorflow/tags?page=1)

**Comment by witeko** [comment]
@jerryyin and @sunway513 , tf23 causes errors for me while training mobile net (installing from whl, building from source doesnt work for me), but while it works it seems to be much faster on rocm 3.7 and tf23.

**Comment by jerryyin** [comment]
Closing the issue as fixed in ROCm 3.7
