### ISSUE TITLE
Vscode single step debugging tensorflow, how to configure the environment

### ISSUE THREAD

**Issue by ccywxhn** [ROCmSoftwarePlatform/tensorflow-upstream#1066]
Write a simple tensorflow program, I want to step debugging to understand tensorflow operation internal process by using VScode.  how to configure the environment in VScode.

Here is my environment configuration:
 * Ubuntu18.04
 * ROCm-3.3.0
 * Python3.6
 * Tensorflow 2.1(By compiling and installing with source code)
 * VScode

**Comment by jerryyin** [comment]
This fork only deal with ROCm related questions. I'd suggest you to ask it [upstream](https://github.com/tensorflow/tensorflow).
