### ISSUE TITLE
XLA GPU problems in tensorflow-rocm 3.7?

### ISSUE THREAD

**Issue by roblem** [ROCmSoftwarePlatform/tensorflow-upstream#1100]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 using upstream radeon driver
- TensorFlow installed from (source or binary): pypi (pip install tensorflow-rocm)
- TensorFlow version: 2.3.0
- Python version: Python 3.7.6
- Installed using virtualenv? pip? conda?: pip
- ROCm/MIOpen version: 3.7
- GPU model and memory: Dual Radeon VII's

**Describe the problem**

- Tensorflow ops work (https://gist.github.com/roblem/cf50f4393aa337717662a2d0596e80b4#file-tensorflow_ops-py)
- Tensorflow functions (@tf.function) work (https://gist.github.com/roblem/cf50f4393aa337717662a2d0596e80b4#file-tensorflow_functions-py)
- Tensorflow XLA functions on CPU (@(tf.function(experimental_compile=True) work
```
2020-08-31 08:09:10.722274: I tensorflow/compiler/jit/xla_compilation_cache.cc:314] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
```
- Tensorflow XLA functions on GPU don't work with this error:
```
2020-08-31 08:09:11.054180: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at xla_ops.cc:363 : Internal: unable to find ld.lld in PATH: No such file or directory
 ```

**Comment by whchung** [comment]
Could you help check if `ld.lld` is present under one of the following 2 directories in your ROCm 3.7 installation?

- `/opt/rocm/llvm/bin/ld.lld`
- `/opt/rocm/hcc/bin/ld.lld`

**Comment by roblem** [comment]
Neither of those directories exist on my machine.

**Comment by whchung** [comment]
Could you try install `llvm-amdgpu` package. In my installation where XLA works out of the box `/opt/rocm/llvm/bin/ld.lld` is present:

```
root@9af94f31d138:/opt/rocm/llvm/bin# dpkg -S ld.lld
llvm-amdgpu: /opt/rocm-3.7.0/llvm/bin/ld.lld
root@9af94f31d138:/opt/rocm/llvm/bin# apt show llvm-amdgpu
Package: llvm-amdgpu
Version: 11.0.dev
Status: install ok installed
Priority: optional
Section: devel
Maintainer: Konstantin.Zhuravlyov@amd.com, Mark.Searles@amd.com
Installed-Size: unknown
Depends: libstdc++6 | libstdc++8, libstdc++-5-dev | libstdc++-7-dev, libgcc-5-dev | libgcc-7-dev
Recommends: gcc, g++, gcc-multilib, g++-multilib
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
Description: amdgpu backend
  This is the amdgpu backend based on LLVM 11.0
```

**Comment by whchung** [comment]
Also you could try pull `rocm/tensorflow:rocm3.7-tf2.3-dev` docker image which should have everything configured.

https://hub.docker.com/r/rocm/tensorflow/tags

**Comment by roblem** [comment]
Here is what I have for the two commands you ran

```
$ dpkg -S ld.lld
dpkg-query: no path found matching pattern *ld.lld*

$ apt show llvm-amdgpu -a
Package: llvm-amdgpu
Version: 1:6.0-697810
Priority: optional
Section: devel
Maintainer: Advenced Micro Devices (AMD) <slava.grigorev@amd.com>
Installed-Size: 105 kB
Depends: llvm-amdgpu-runtime (= 1:6.0-697810), llvm-amdgpu-6.0 (= 1:6.0-697810)
Download-Size: 5,536 B
APT-Manual-Installed: yes
APT-Sources: file:/var/opt/amdgpu-pro-local ./ Packages
Description: Low-Level Virtual Machine (LLVM)
 The Low-Level Virtual Machine (LLVM) is a collection of libraries and
 tools that make it easy to build compilers, optimizers, Just-In-Time
 code generators, and many other compiler-related programs.
 .
 This is a dependency package providing the default llvm package.

Package: llvm-amdgpu
Version: 11.0.dev
Priority: optional
Section: devel
Maintainer: Konstantin.Zhuravlyov@amd.com, Mark.Searles@amd.com
Installed-Size: unknown
Depends: libstdc++6|libstdc++8, libstdc++-5-dev|libstdc++-7-dev, libgcc-5-dev|libgcc-7-dev
Recommends: gcc, g++, gcc-multilib, g++-multilib
Download-Size: 511 MB
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: amdgpu backend
  This is the amdgpu backend based on LLVM 11.0
```

**Comment by whchung** [comment]
@roblem So it seems `llvm-amdgpu` is not installed on your box. It should carry an attribute when you do `apt show`:

```
Status: install ok installed
```

Could you test again after you do `apt install llvm-amdgpu`?

**Comment by roblem** [comment]
Apologies.  Remnants of the opencl parts of amdgpupro were still lingering in the system.  After removing those and reinstalling rocm 3.7, this works so closing.
