### ISSUE TITLE
 TensorFlow cannot allocate >4GB on RX-480 8GB (ROCm-TF)

### ISSUE THREAD

**Issue by gsedej** [ROCmSoftwarePlatform/tensorflow-upstream#1103]
Short summary:
I can train/evaluate models that allocate less than 4GB of VRAM, but i get issue if more on 8GB gpu. I can run 2 models ~4GB at the same time though.

I have already opened issue on "ROCm" tracker, but didn't get any response in 1 week. Maybe ROCm-tensoflow guys can provide some info.
Full info on issue is here: https://github.com/RadeonOpenCompute/ROCm/issues/1206

Also another questions - why there are so many different "rocm" related repositories:
https://github.com/RadeonOpenCompute/
https://github.com/ROCmSoftwarePlatform/ 
https://github.com/ROCm-Developer-Tools/
It's hard to navigate between projects.

**Comment by jerryyin** [comment]
Have you tried to set the environment variable as what the error message suggests? `export TF_CUDNN_WORKSPACE_LIMIT_IN_MB=8192`

**Comment by gsedej** [comment]
`export TF_CUDNN_WORKSPACE_LIMIT_IN_MB=8192` did not help - same output 

(`Memory access fault by GPU node-1 (Agent handle: 0x4dfe2c0) on address 0x103369f000. Reason: Page not present or supervisor privilege.`)

I have read that ROCm version 3.3 was working better. How can I downgrade? (Ubuntu 18.04)


EDIT:
there another tensorflow model outputs another issue:
```
Epoch 00001: LearningRateScheduler reducing learning rate to 0.001.
Epoch 1/2
2020-09-03 17:33:46.847148: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-09-03 17:33:46.911703: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-09-03 17:33:46.914223: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-09-03 17:33:46.915777: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-09-03 17:33:47.337592: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
2020-09-03 17:33:47.460951: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-09-03 17:33:47.652288: W tensorflow/core/common_runtime/bfc_allocator.cc:246] Allocator (GPU_0_bfc) ran out of memory trying to allocate 6.12GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-09-03 17:33:47.652381: F tensorflow/stream_executor/rocm/rocm_dnn.cc:3527] Failed to allocate scratch memory - Failed to allocate the requested memory size (6576668672).
	You can set the env var TF_CUDNN_WORKSPACE_LIMIT_IN_MB to a larger number (e.g. 8192) to increase the max memory limit.
	Increasing the max memory limit might help resolve this error

```

**Comment by jerryyin** [comment]
Ok so by reading your log I don't think it is either TF or ROCm problems. It is simply because your model's peak memory requires more than 8GB of GPU memory. Remember, TF in its execution also consumes memory, e.g.: It has to store tensors in the forward pass in preparation for the backward pass. From the look of it, if the occupied memory at running the current node is ~2GB, and now TF ask to allocate another 6.12GB which in total exceeds the 8GB, there isn't much the framework can do to overcome the hardware limitation.

**Comment by gsedej** [comment]
OK. I checked now on nvidia Titan X with 11GB, it takes bit above 8GB. Understandable it does not work with 8GB.

But still, with "first" model, I can set size of input images. The bigger input, the bigger model (more VRAM).
If I set size of 488 x 488 pixels, the model is just below 4GB of VRAM - and it works fine on my RX480.
I can even run 2 instances of 488 x 488 pixels, consuming 8GB of VRAM together - it also works fine.
BUT if I set size of 512 x 512 pixel the rocm tensorflow fails (works on nvidia, it takes around 5GB).

**Comment by jerryyin** [comment]
The memory footprint is highly dependent on the ops you use in tensorflow. But I agree if the model on Nvidia hardware consumes only around 5GB whereas fails on AMD side, it is something to look into. Could you provide all details to reproduce? I will need a docker image, the setup instructions, model script and training data.

**Comment by gsedej** [comment]
Unfortunately I am not allowed to post model/data, since we are working on medical data.

I am also quite new to tensorflow (previously working on caffe), so I don't know which demo/example model uses more than 4GB of vram. Do you have polaris hw and model bigger than 4GB?

**Comment by gsedej** [comment]
I have tried tensorflow (deprecated) benchmark:

`python tf_cnn_benchmarks.py --num_gpus=1 --batch_size=64 --model=resnet50`

by using batch size 64, almost all of 8GB gpu memory gets used, meaning some model can use all memory.

The problem with my model might be something else - my model is so big, that batch_size = 1 needs all memory.

I will report when I will get more info.

**Comment by jerryyin** [comment]
Yes, it is not about a finding a model that is able to consume all GPU VRAM of a card, it is really about the peculiar case you see where AMD GPU consume much more memory than NVDIA GPU. We don't need real data, synthetic data that can reproduce the problem works too.

**Comment by jerryyin** [comment]
Closing with inactivity. Feel free to reopen if you have additional information.
