### ISSUE TITLE
"ROCm Fusion is enabled" appears all the time in the terminal when predicting/training a model

### ISSUE THREAD

**Issue by niso** [ROCmSoftwarePlatform/tensorflow-upstream#1141]
Hi all
I'm referring to this line:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/dd4c521ca818ed4f503eb38d3ee93986751defe3/tensorflow/core/common_runtime/gpu_fusion_pass.cc#L507

Is there any reason to not to use VLOG(kLogLevel) instead of VLOG(0)?

Thanks
Genís

**Comment by Mushoz** [comment]
Any news on this? This spam is driving me crazy to be honest. It's making it hard to quickly have a look at the log to see what's happening. Why was this issue closed?
