### ISSUE TITLE
build the TF ROCm master branch failed in a VM without functional ROCm stack

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/tensorflow-upstream#119]
- **OS Platform and Distribution: Ubuntu 16.04
- **Python version: 2.7 & 3.5
- **Bazel version (if compiling from source): 0.15.2
- **GCC/Compiler version (if compiling from source):5.4
- **CUDA/cuDNN version**: null
HCC version:1.2.18312
HIPCC version: HIP version: 1.5.18081
- **GPU model and memory**: gfx803,gfx900
HIP_PLATFORM=hcc

### Describe the problem
build the TF ROCm master branch failed at: protobuf_archive//:js_embed

### Source code / logs
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (329 packages loaded).
INFO: Found 1 target...
ERROR: /data/.cache/bazel/_bazel_root/83ff65d34212932ecc7e9a2871d57ecd/external/protobuf_archive/BUILD:260:1: Linking of rule '@protobuf_archive//:js_embed' failed (Exit 2): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /data/.cache/bazel/_bazel_root/83ff65d34212932ecc7e9a2871d57ecd/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=:/opt/hsa-rocr-dev/hsa/lib \
    PATH=/root/bin:/root/go/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/kube/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -o bazel-out/host/bin/external/protobuf_archive/js_embed -Wl,-no-as-needed -B/opt/rocm/hcc/compiler/bin -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/external/protobuf_archive/js_embed-2.params)
Can't exec "/usr/local/cuda/bin/nvcc": No such file or directory at /opt/rocm/hip/bin/hipcc line 505.
Died at /opt/rocm/hip/bin/hipcc line 505.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 362.862s, Critical Path: 58.76s
INFO: 480 processes: 480 local.

I have set HIP_PLATFORM=hcc ，why the hipcc still call cuda/bin/nvcc?

**Comment by whchung** [comment]
Setting env var is of no use building TensorFlow . The build system ignores all env vars in the shell. Please try alter bazel build command amending “—action_env=FOO=val”

**Comment by whchung** [comment]
@wormwang since you are filing a new ticket #124 I take this issue has been resolved. closing this ticket hereby.
