### ISSUE TITLE
Tensorflow-rocm for ROCm v3.10.0

### ISSUE THREAD

**Issue by quocdat32461997** [ROCmSoftwarePlatform/tensorflow-upstream#1196]
After installing ROCm v.3.10.0 and TF-ROCm 2.3.2, I got the following error:

`
2020-12-05 17:07:04.336041: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
`

I found this error at this issue #652. Probably, due to the incompatibility between ROCm v3.10.0 and TF-Rocm. The TF-Rocm release compatible with ROCm v3.10.0 would be helpful.

**Comment by Djip007** [comment]
```
2020-12-05 23:24:55.988244: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
*** stack smashing detected ***: <unknown> terminated
```
same with rocm-3.10 on centos8...

**Comment by quocdat32461997** [comment]
@Djip007 below ares the steps I downgraded to ROCm 3.9 and installed the compatible TF-ROCm. I tested it on Ubuntu, not sure CentosOS. Hope this helps.

I strictly followed the ROCm installation instructions in the [Install Rocm](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html) with minor modifications. Check the [TF-Rocm for the supported Rocm versions.](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md)

**Notes & Modifications:**
* Fresh installation is recommended.
* In step 2, change to:
`
wget -q -O - https://repo.radeon.com/rocm/apt/x.x.x/rocm.gpg.key | sudo apt-key add -
echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/x.x.x/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
`

that x.x.x is the version. E.g. for ROCm v3.9, **x.x.x = 3.9**
* After installing ROCm, install TF-ROCm by typing `pip3 install tensorflow-rocm`.
-- If errors "libhipsparse or librccl" raise, install them by typing `sudo apt install <package> && sudo ldconfig`. If more errors of missing package, repeat the above step to install them and refresh cache.

**Comment by Djip007** [comment]
@quocdat32461997 :
Thanks... well if someone need it for centOS8 you "simply" have to change the repos config from:
```
[ROCm]
name=ROCm
baseurl=https://repo.radeon.com/rocm/centos8/rpm
enabled=1
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
```
to
```
[ROCm]
name=ROCm
baseurl=https://repo.radeon.com/rocm/centos8/3.9.1
enabled=1
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
```
(all release have his directory : https://repo.radeon.com/rocm/centos8/  (3.5.1 / 3.7 / 3.8 / ...))
but well in my case a have au RX480 GPU that have other bug ;)

**Comment by xuhuisheng** [comment]
It is weired that tensorflow_rocm-2.3.3 didnt release, yet.
I cannot wait for offcial, have compiled by myself.

Cost hours.

Anyone who interested it, could clone `https://gitub.com/ROCmSoftwarePlatform/tensorflow-upstream` and checkout `r2.3-rocm-enhanced` branch.

**Comment by Molive-0** [comment]
The r1.15-rocm-enhanced branch still seems to fail to compile however :/

**Comment by xuhuisheng** [comment]
2.3.3 had been released.
https://pypi.org/project/tensorflow-rocm
:smile:

**Comment by quocdat32461997** [comment]
Great. Close this.

**Comment by BahramianArmin** [comment]
thansk for your articles in Medium....:D
But i do all f thing you say...
and when i 'rocm-smi' in terminal 

======================= ROCm System Management Interface =======================
WARNING: No AMD GPUs specified
================================= Concise Info =================================
GPU  Temp  AvgPwr  SCLK  MCLK  Fan  Perf  PwrCap  VRAM%  GPU%  
================================================================================
============================= End of ROCm SMI Log ==============================




so what can i do ???

my GPU == AMD Radeon R7 M265

**Comment by quocdat32461997** [comment]
@BahramianArmin 
just checked. Your GPU is not supported by either ROCm or TF-ROCm. Based on [this](https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support), your GPU is not supported. I guess that's why it said No AMD GPUs specified.
