### ISSUE TITLE
build debug tensorflow

### ISSUE THREAD

**Issue by ccywxhn** [ROCmSoftwarePlatform/tensorflow-upstream#1200]
In order to debug tensorflow, study TF internal module  and its principle. 
so, select source code compilation and installation.

**System information**
- Ubuntu18.04:
- TensorFlow 2.1( git checkout merge-200413):
- Python 3.6
- Bazel version2.0:
- ROCm 3.3
- Device: vega 10
- vscode

1. In build_ rocm_python 3 file add compilation options, --cxxopt="-g",  as follows:
        bazel build --cxxopt="-g" --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures &&
2. Implement
       ./build_rocm_python3
3. Meet problem
    Import TF into '. Py' file and write some simple TF addition and subtraction.            
    Debug can enter the . Py file in tensorflow, but can't enter the C / C++ code in TF.           
    I want to debug into C / C + + in TF. I don't know if there is a problem with my own compilation options.

**Comment by jerryyin** [comment]
Please use gdb to debug into C++ code.

Closing this as the repo only deal with ROCm specific issue, otherwise please post it to upstream at https://github.com/tensorflow/tensorflow. Will re-open only if you can prove this issue is ROCm specific.
