### ISSUE TITLE
Memory access fault by GPU node-1

### ISSUE THREAD

**Issue by hld2018** [ROCmSoftwarePlatform/tensorflow-upstream#1216]
I got an error when calling tf.compat.v1.train.Saver.save.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version 2.4.0:
- Python version:3.8
- ROCm version:4.0.0
- GPU model and memory: RX580 2048sp with 4GB RAM
**Message**
- Memory access fault by GPU node-1 (Agent handle: 0x5644299ef910) on address 0x6e77e9000. Reason: Page not present or supervisor privilege.
Maybe ROCm don't have fully support on my GPU? There is another message "MIOpen(HIP): Warning [ParseAndLoadDb] File is unreadable: /opt/rocm-4.0.0/miopen/share/miopen/db/gfx803_32.HIP.fdb.txt" before, I check the directory, it only have gfx803_36.HIP.fdb.txt, I think it's for gfx803 with 2306sp.

**Comment by ROCmSupport** [comment]
Thanks for reaching out.
gfx8 is not a supported config now.
We are not supporting gfx8 devices officially with ROCm and request you to follow our supported hardware section @ ROCm docs: [https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support](url)
