### ISSUE TITLE
Where i can download libtensorflow.so

### ISSUE THREAD

**Issue by gosha20777** [ROCmSoftwarePlatform/tensorflow-upstream#1261]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution Linux Ubuntu 16.04:
- TensorFlow version: 2.3.1

**Describe the problem**
I want to download or get the compiled libraries for tensorflow-rocm 2.3.1 (`libtensorflow.so` and `libtensorflow_framework.so.2` etc?)
Later I want to use them in my C# application.

**Comment by sunway513** [comment]
Hi @gosha20777 , you can pull the TF2.3 docker container and build it from source to get all the shared libraries available. The steps can be like the following:
```
alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --shm-size 16G --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx'

drun rocm/tensorflow:rocm4.0.1-tf2.3-dev

cd ~/tensorflow/ && bash build_rocm_python3

**Comment by gosha20777** [comment]
@sunway513 I don't need tensorflow for python
I need C++ tensorflow API to use it from C++ application.

**Comment by sunway513** [comment]
@deven-amd  does TF need different build options to build for C++ APIs?

**Comment by deven-amd** [comment]
We do not explicitly generate any C++ artifacts for TF in our containers. 
Let me look into whether any are generated as a by-product of creating the TF whl pkg. If yes, we can probably tweak our scripts to post them somewhere. Else we need to figure out a way to generate it.

**Comment by deven-amd** [comment]
@gosha20777 

Just confirming that we do not currently build and post the libtensorflow.so for linking with C/C++ apps.

You can follow the steps outlined here ( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md ), to build the same for ROCm.

Specifically, I have verified that the following steps will work in the container mentioned by @sunway513 above ( `rocm/tensorflow:rocm4.0.1-tf2.3-dev` )

```
yes "" | ROCM_PATH=/opt/rocm-4.0.1 TF_NEED_ROCM=1 PYTHON_BIN_PATH=/usr/bin/python3 ./configure

bazel test //tensorflow/tools/lib_package:libtensorflow_test && \
bazel build //tensorflow/tools/lib_package:libtensorflow

```

executing the above command will yield the library you want in `bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz`


We will plan on posting (i.e. making available for public download) the nightly and release version of the library, but that will take time.
