### ISSUE TITLE
missing the /opt/rocm/hip/include/hip include directory in the bazel project?

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/tensorflow-upstream#127]
System information
**OS Platform and Distribution: Ubuntu 16.04
**Python version: 2.7 & 3.5
**Bazel version (if compiling from source): 0.15.2
**GCC/Compiler version (if compiling from source):5.4
CUDA/cuDNN version: null
HCC version:1.2.18312
HIPCC version: HIP version: 1.5.18081
GPU model and memory: gfx803,gfx900
HIP_PLATFORM=hcc
bazelrc file:
build --action_env=HIP_PLATFORM=hcc --action_env=HCC_AMDGPU_TARGET=gfx900 --action_env=HIP_PATH=/opt/rocm/hip --action_env=HIPCC_PATH=/opt/rocm/hip/bin --action_env=HSA_PATH=/opt/hsa-rocr-dev/hsa --action_env=HCC_HOME=/opt/rocm/hcc --action_env=ROCM_PATH=/opt/rocm --action_env=HSA_LIBRARY=/opt/hsa-rocr-dev/lib/libhsa-runtime64.so --action_env=HSA_HEADER=/opt/hsa-rocr-dev/include --action_env="LD_LIBRARY_PATH=.:/opt/hsa-rocr-dev/hsa/lib:${LD_LIBRARY_PATH}

Describe the problem
missing the hip/hip_runtime.h  or hip/hip_runtime_api.h in different building task that depend hip's include files.

I have add a cxx_builtin_include_directory in tensorflow/third_party/gpus/crosstool/CROSSTOOL.tpl

 
%{cxx_builtin_include_directory: "/opt/rocm/hip/include/hip" }

How to add the /opt/rocm/hip/include/hip include directory into the bazel project?

Source code / logs
ERROR: /data/tensorflow-upstream/tensorflow/stream_executor/BUILD:106:1: C++ compilation of rule '//tensorflow/stream_executor:rocm_platform' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /data/.cache/bazel/_bazel_root/83ff65d34212932ecc7e9a2871d57ecd/execroot/org_tensorflow && \
  exec env - \
    HCC_AMDGPU_TARGET=gfx900 \
    HCC_HOME=/opt/rocm/hcc \
    HIPCC_PATH=/opt/rocm/hip/bin \
    HIP_PATH=/opt/rocm/hip \
    HIP_PLATFORM=hcc \
    HSA_HEADER=/opt/hsa-rocr-dev/include \
    HSA_LIBRARY=/opt/hsa-rocr-dev/lib/libhsa-runtime64.so \
    HSA_PATH=/opt/hsa-rocr-dev/hsa \
    LD_LIBRARY_PATH=:/opt/hsa-rocr-dev/hsa/lib \
    LITTLEENDIAN_CPU=1 \
    PATH=/root/bin:/root/go/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/kube/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    ROCM_PATH=/opt/rocm \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=1 \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/arm-opt/bin/tensorflow/stream_executor/_objs/rocm_platform/tensorflow/stream_executor/rocm/rocm_dnn.pic.d '-frandom-seed=bazel-out/arm-opt/bin/tensorflow/stream_executor/_objs/rocm_platform/tensorflow/stream_executor/rocm/rocm_dnn.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/arm-opt/genfiles -iquote external/com_google_absl -iquote bazel-out/arm-opt/genfiles/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/arm-opt/genfiles/external/bazel_tools -iquote external/nsync -iquote bazel-out/arm-opt/genfiles/external/nsync -iquote external/eigen_archive -iquote bazel-out/arm-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/arm-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/arm-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/arm-opt/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/arm-opt/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/arm-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/arm-opt/genfiles/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/arm-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/arm-opt/genfiles/external/local_config_cuda -iquote external/local_config_rocm -iquote bazel-out/arm-opt/genfiles/external/local_config_rocm -isystem external/nsync/public -isystem bazel-out/arm-opt/genfiles/external/nsync/public -isystem bazel-out/arm-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/arm-opt/genfiles/external/eigen_archive -isystem bazel-out/arm-opt/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/arm-opt/genfiles/external/gif_archive/lib -isystem bazel-out/arm-opt/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/arm-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/arm-opt/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/arm-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/arm-opt/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/arm-opt/genfiles/external/zlib_archive -isystem bazel-out/arm-opt/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/arm-opt/genfiles/external/local_config_cuda/cuda -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/arm-opt/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/arm-opt/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda/cuda/include/crt -isystem external/local_config_rocm/rocm -isystem bazel-out/arm-opt/genfiles/external/local_config_rocm/rocm -isystem bazel-out/arm-opt/bin/external/local_config_rocm/rocm -isystem external/local_config_rocm/rocm/rocm/include -isystem bazel-out/arm-opt/genfiles/external/local_config_rocm/rocm/rocm/include -isystem bazel-out/arm-opt/bin/external/local_config_rocm/rocm/rocm/include -isystem external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/arm-opt/genfiles/external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/arm-opt/bin/external/local_config_rocm/rocm/rocm/include/rocrand -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c tensorflow/stream_executor/rocm/rocm_dnn.cc -o bazel-out/arm-opt/bin/tensorflow/stream_executor/_objs/rocm_platform/tensorflow/stream_executor/rocm/rocm_dnn.pic.o)
In file included from tensorflow/stream_executor/rocm/rocm_dnn.cc:43:0:
bazel-out/arm-opt/genfiles/external/local_config_rocm/rocm/rocm/include/miopen/miopen.h:47:33:###  fatal error: hip/hip_runtime_api.h: No such file or directory
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 148.175s, Critical Path: 55.12s
INFO: 19 processes: 19 local.
FAILED: Build did NOT complete successfully

**Comment by sunway513** [comment]
Hi @wormwang 
Could you first update your ROCm packages to ROCm1.8.2?
Actually, I would suggest you start with our public docker images that contain the complete environment to build TF1.8 from source and add your changes on top of a successful build. 
Here's the dockerhub repo:
https://hub.docker.com/r/rocm/tensorflow/

The following docker image will do:
`rocm/tensorflow:rocm1.8.2-tf1.8-python3-dev`

**Comment by whchung** [comment]
@wormwang 

`tensorflow/third_party/gpus/crosstool/CROSSTOOL.tpl` is incorrect. Please try change:

`tensorflow/third_party/gpus/crosstool/CROSSTOOL_hipcc.tpl`, or `tensorflow/third_party/gpus/rocm_configure.bzl`.

You can find relevant ROCm-specific directories inside the file.
