### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by Bengt** [ROCmSoftwarePlatform/tensorflow-upstream#1276]
Python 3.9 has was released on 2020-10-05, which is almost 6 months ago:

<https://docs.python.org/3/whatsnew/3.9.html>

There are no packages for Python 3.9, as of yet:

<https://pypi.org/project/tensorflow-rocm/2.4.0/#files>

Currently, Python 3.8 seems to have the broadest library support. However, this is changing quickly and Python 3.9 is becoming more relevant by the day. So to stay applicable for many use cases, tensorflow-rocm should support Python 3.9 with pre-built wheel packages.

**Comment by Bengt** [comment]
Note that support for Python 3.9 is just becoming available in the upstream TensorFlow project:

<https://github.com/tensorflow/tensorflow/issues/44485#issuecomment-786936023>

So to support Python 3.9 with prebuilt packages, TensorFlow-ROCm needs to get the corresponding build jobs.

**Comment by sunway513** [comment]
Hi @Bengt , we expect TF 2.5 to be the first release enables Python 3.9 whl package support.
In the meanwhile, we'll also evaluate and try to enable python3.9 whl package in our nightly CSB builds. 
cc @deven-amd

**Comment by Bengt** [comment]
Hi @sunway513, thanks for the information. Now I can plan for upgrading my Python interpreters a bit better

**Comment by stevenireeves** [comment]
Python3.9 wheels are available for TF2.5 on.

**Comment by Bengt** [comment]
Cool. For future reference: https://pypi.org/project/tensorflow-rocm/2.5.0/#files
