### ISSUE TITLE
Convolution crashes

### ISSUE THREAD

**Issue by bhoeveler** [ROCmSoftwarePlatform/tensorflow-upstream#1347]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- Opensuse 15.2 with Kernel 5.12.1-1.g82ccb82-vanilla
- TensorFlow installed from pip wheel
- TensorFlow version : v2.4.0-rc4-86-gd9cfe09e0d4 2.4.0
- Python version: 3.6.12
- ROCm version: 4.0.1
- GPU model and memory: Radeon VII

**Describe the current behavior**

When calling tf.nn.conv1d with a float64 input and kernel tensorflow crashes. In contrast, a float32 input works.

**Standalone code to reproduce the issue**

```python
    x = tf.linspace(0,1,100)
    
    x = tf.cast( x , dtype=tf.float64)
    x = tf.reshape( x, ( 1, -1, 1) )
    z = tf.convert_to_tensor( [[-1,1,0], [0,-1,1]], dtype=tf.float64 )
    z = tf.reshape( tf.transpose( z ), (3,1,2))
    print( x, z )
    print( tf.nn.conv1d( x,z, 1, "VALID") )
    print( x[0,1:,0] -x[0,:-1,0])
```

**Comment by sunway513** [comment]
@deven-amd , can you help on this issue? Thanks.

**Comment by deven-amd** [comment]
@bhoeveler 

The reason for this is that `double` datatype is not supported for the convolution ops on the ROCm platform.

You should be getting an (admittedly cryptic) error message to this effect
```
2021-05-10 13:27:41.113700: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1707] Invalid DNN data type: 1
```

**Comment by deven-amd** [comment]
filed a PR to improve the error message a little bit to
```
2021-05-10 16:33:45.874371: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1706] Unsupported DNN data type: tf.float64 (dnn::DataType::kDouble)
```
