### ISSUE TITLE
Crash on import tensorflow

### ISSUE THREAD

**Issue by jansende** [ROCmSoftwarePlatform/tensorflow-upstream#1396]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 20.1 Cinnamon
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: Latest shipped with pip probably. Cannot check because of crash.
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: No virtualenv. pip. No conda.
- Bazel version (if compiling from source): Not applicable.
- GCC/Compiler version (if compiling from source): Not applicable.
- ROCm/MIOpen version: 3.10
- GPU model and memory: AMD Radeon RX 570 Armor 8G OC

**Describe the problem**
Installed ROCM using the following steps:
1. Update system.
```bash
sudo apt upgrade
sudo apt dist-upgrade
```
2. Install NUMA Development package.
```bash
sudo apt install libnuma-dev
```
3. Register ROCM package repository.
```bash
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add - 
echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/3.10/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
```

4. Update package manager.
```bash
sudo apt update
```
5. Install ROCM package.
```bash
sudo apt install rocm-dkms
```
6. Add yourself to `VIDEOGROUP`.
```bash
sudo usermod -a -G video $LOGNAME
sudo usermod -a -G render $LOGNAME
```
7. Open `/etc/adduser.conf` and add these lines:
```bash
sudo nano /etc/adduser.conf
```
```bash
ADD_EXTRA_GROUPS=1
EXTRA_GROUPS="render,video"
```
8. Open `/etc/udev/rules.d/70-kfd.rules` and add the following:
```bash
sudo nano /etc/udev/rules.d/70-kfd.rules
SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"
```
9. Install `libtinfo5`.
```bash
sudo apt install libtinfo5
```
Installed Tensorflow-ROCM using the following steps:
1. Install dependencies.
```bash
sudo apt install rocm-libs hipcub miopen-hip
```
2. Install RCCL.
```bash
sudo apt install rccl
```
3. Install Tensorflow-ROCM Python package.
```bash
pip3 install tensorflow-rocm
```
Trying to use Tensorflow in Python leads to a crash on import:

```python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/[REDACTED]/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamdhip64.so.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/[REDACTED]/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/[REDACTED]/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/[REDACTED]/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/[REDACTED]/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamdhip64.so.4: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 
```

I tried the same process using ROCM version 4.2 before, and had no trouble importing. However, as my GPU is not supported by this newer version of ROCM, I needed to roll back.

**Comment by sunway513** [comment]
Hi @jansende, RX570 is not supported by ROCm, for details you can refer to the following thread:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1230#issuecomment-789537799
cc @ROCmSupport
