### ISSUE TITLE
Embedded or Edge Computing

### ISSUE THREAD

**Issue by srika91** [ROCmSoftwarePlatform/tensorflow-upstream#1397]
Hello ,
I have been searching for sometime now.I could not get anything related to AMDs benchamrks on deep learning edge devices ,something that is equivalent of Nvidias Jetson devices
Is there any support for Edge devices with computer vision deep learning ,any benchmarks on AMD edge devices ?

**Comment by sunway513** [comment]
Hi @srika91 , I don't think ROCm has been enabled on edge devices. You can refer to the following document on the current ROCm HW support support coverage:
https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support
