### ISSUE TITLE
tensorflow-rocm and tensorflow-io

### ISSUE THREAD

**Issue by elukey** [ROCmSoftwarePlatform/tensorflow-upstream#1461]
Hi everybody,

We tested ROCm 4.3.1 and tensorflow-rocm 2.6.0 on our environments, everything works nicely but we realized that HDFS support was dropped:
```
ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on hdfs://analytics-hadoop/user/test/mobilenet/variables/variables: Unimplemented: File system scheme 'hdfs' not implemented (file: 'hdfs://analytics-hadoop/user/test/mobilenet/variables/variables')
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```
This seems to be related to a change in Tensorflow 2.6, that now delegates HDFS/S3/etc.. support to Tensorflow I/O:
https://discuss.tensorflow.org/t/how-can-i-access-to-hdfs-file-system-in-the-latest-tensorflow-2-6-0/3876

The main problem installing `tensorflow-io` from Pypi is that it requires `tensorflow`, that doesn't play well with `tensorflow-rocm`. Is there any plan to have something like `tensorflow-io-rocm` in the future?

We tried the TF_USE_MODULAR_FILESYSTEM suggestion but it didn't work.

Thanks in advance!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10 (we are aware that it is not supported natively)
- TensorFlow installed from binary: 2.6.0
- Python version: 3.7
- GPU model and memory: AMD Radeon Pro WX 9100 16GB

**Comment by elukey** [comment]
One alternative could be to collaborate with tensorflow-io's upstream and possibly add a variant to its setup.py. For example, one could install tensorflow-io[rocm] with a dependency on tensorflow-rocm instead of tensorflow.

**Comment by elukey** [comment]
@ROCmSupport tagging this account since this may be a big usability blocker for ROCm 4.3.1 and Tensorflow-rocm 2.6.

**Comment by elukey** [comment]
@deven-amd Hi! I naively thought that adding an extra/variant to setup.py in tensorflow-io could work (see https://github.com/tensorflow/io/issues/1548), but to me the best compromise seems to be forking tensorflow-io in tensorflow-io-rocm. What do you think?

**Comment by jayfurmanek** [comment]
I commented over on https://github.com/tensorflow/io/issues/1548
Tensorflow-io has this issue on `tensorflow-cpu` as well or any other variant. I'll take a peak over there to see if they can do something a bit better. The `addons` package doesn't have that problem so that may be a good compare point.

**Comment by elukey** [comment]
The PR got merged and the next version of `tensorflow-io` (likely 0.23) should support `tensorflow-rocm`.
