### ISSUE TITLE
mlir error when compiling tensorflow2 with rocm4.3.1

### ISSUE THREAD

**Issue by hclearner** [ROCmSoftwarePlatform/tensorflow-upstream#1468]
ROCm: 4.3.1
TensorFlow Version: 2.7
Operating System: centos 7.9
GCC: devtools-7.3.1
LLVM: https://repo.radeon.com/rocm/yum/4.3.1/

Compile command: 
```
TF_ENABLE_MLIR=1 
TF_ENABLE_XLA=1 
./build_rocm_python3
```

Error:
```
bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
error: Failure when generating HSACO
```

Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)

**Comment by deven-amd** [comment]
@weihanmines 

can you reproduce this error locally, and work with @rsanthanam-amd to come up with a fix for it. thanks

**Comment by weihanmines** [comment]
> ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> 
> Compile command:
> 
> ```
> TF_ENABLE_MLIR=1 
> TF_ENABLE_XLA=1 
> ./build_rocm_python3
> ```
> 
> Error:
> 
> ```
> bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> error: Failure when generating HSACO
> ```
> 
> Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)

I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.

**Comment by hclearner** [comment]
> 
> 
> > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > Compile command:
> > ```
> > TF_ENABLE_MLIR=1 
> > TF_ENABLE_XLA=1 
> > ./build_rocm_python3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error:
> > ```
> > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > error: Failure when generating HSACO
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> 
> I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.

The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `.  If the `--define=with_xla_support=false` is false, it also compiled failed.
```
build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
build --python_path="/opt/conda/bin/python3"
build --define=with_xla_support=false
build --config=rocm
build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-Wno-sign-compare
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_env=LD_LIBRARY_PATH
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
```
The GPU's name is gfx906 in our machine.
LLVM version:
```
llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
```
```
clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-4.3.1/llvm/bin
```

**Comment by weihanmines** [comment]
> > > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > > Compile command:
> > > ```
> > > TF_ENABLE_MLIR=1 
> > > TF_ENABLE_XLA=1 
> > > ./build_rocm_python3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Error:
> > > ```
> > > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > > error: Failure when generating HSACO
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> > 
> > 
> > I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.
> 
> The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `. If the `--define=with_xla_support=false` is false, it also compiled failed.
> 
> ```
> build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
> build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
> build --python_path="/opt/conda/bin/python3"
> build --define=with_xla_support=false
> build --config=rocm
> build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
> build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
> build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
> build:opt --copt=-Wno-sign-compare
> build:opt --host_copt=-Wno-sign-compare
> test --flaky_test_attempts=3
> test --test_size_filters=small,medium
> test --test_env=LD_LIBRARY_PATH
> test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
> test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
> test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
> test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
> ```
> 
> The GPU's name is gfx906 in our machine. LLVM version:
> 
> ```
> llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
> llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
> ```
> 
> ```
> clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /opt/rocm-4.3.1/llvm/bin
> ```

It compiles successfully on my end with `--define=with_xla_support=true`. I did an installation in centos-7.9 container too.

**Comment by hclearner** [comment]
> 
> 
> > > > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > > > Compile command:
> > > > ```
> > > > TF_ENABLE_MLIR=1 
> > > > TF_ENABLE_XLA=1 
> > > > ./build_rocm_python3
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Error:
> > > > ```
> > > > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > > > error: Failure when generating HSACO
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> > > 
> > > 
> > > I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.
> > 
> > 
> > The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `. If the `--define=with_xla_support=false` is false, it also compiled failed.
> > ```
> > build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
> > build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
> > build --python_path="/opt/conda/bin/python3"
> > build --define=with_xla_support=false
> > build --config=rocm
> > build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
> > build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
> > build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
> > build:opt --copt=-Wno-sign-compare
> > build:opt --host_copt=-Wno-sign-compare
> > test --flaky_test_attempts=3
> > test --test_size_filters=small,medium
> > test --test_env=LD_LIBRARY_PATH
> > test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
> > test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
> > test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
> > test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The GPU's name is gfx906 in our machine. LLVM version:
> > ```
> > llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
> > llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
> > Target: x86_64-unknown-linux-gnu
> > Thread model: posix
> > InstalledDir: /opt/rocm-4.3.1/llvm/bin
> > ```
> 
> It compiles successfully on my end with `--define=with_xla_support=true`. I did an installation in centos-7.9 container too.

Could you share the Bazel compile command in centos 7.9 with devtools 7.3.1?
```
yes "" | ROCM_PATH=$ROCM_PATH TF_NEED_ROCM=1 PYTHON_BIN_PATH=${PYTHON_EXE} ./configure
bazel build -j 20 --config=opt --config=rocm --copt="-I/opt/rh/devtoolset-7/root/usr/include/c++/7" --copt="-L/opt/rh/devtoolset-7/root/usr/lib64" --copt="-static-libstdc++" --copt="-L/opt/rocm/lib64" //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

**Comment by weihanmines** [comment]
> > > > > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > > > > Compile command:
> > > > > ```
> > > > > TF_ENABLE_MLIR=1 
> > > > > TF_ENABLE_XLA=1 
> > > > > ./build_rocm_python3
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Error:
> > > > > ```
> > > > > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > > > > error: Failure when generating HSACO
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> > > > 
> > > > 
> > > > I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.
> > > 
> > > 
> > > The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `. If the `--define=with_xla_support=false` is false, it also compiled failed.
> > > ```
> > > build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
> > > build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
> > > build --python_path="/opt/conda/bin/python3"
> > > build --define=with_xla_support=false
> > > build --config=rocm
> > > build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
> > > build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
> > > build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
> > > build:opt --copt=-Wno-sign-compare
> > > build:opt --host_copt=-Wno-sign-compare
> > > test --flaky_test_attempts=3
> > > test --test_size_filters=small,medium
> > > test --test_env=LD_LIBRARY_PATH
> > > test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
> > > test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
> > > test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
> > > test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The GPU's name is gfx906 in our machine. LLVM version:
> > > ```
> > > llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
> > > llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
> > > Target: x86_64-unknown-linux-gnu
> > > Thread model: posix
> > > InstalledDir: /opt/rocm-4.3.1/llvm/bin
> > > ```
> > 
> > 
> > It compiles successfully on my end with `--define=with_xla_support=true`. I did an installation in centos-7.9 container too.
> 
> Could you share the Bazel compile command in centos 7.9 with devtools 7.3.1?
> 
> ```
> yes "" | ROCM_PATH=$ROCM_PATH TF_NEED_ROCM=1 PYTHON_BIN_PATH=${PYTHON_EXE} ./configure
> bazel build -j 20 --config=opt --config=rocm --copt="-I/opt/rh/devtoolset-7/root/usr/include/c++/7" --copt="-L/opt/rh/devtoolset-7/root/usr/lib64" --copt="-static-libstdc++" --copt="-L/opt/rocm/lib64" //tensorflow/tools/pip_package:build_pip_package --verbose_failures
> ```

`bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

**Comment by hclearner** [comment]
> 
> 
> > > > > > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > > > > > Compile command:
> > > > > > ```
> > > > > > TF_ENABLE_MLIR=1 
> > > > > > TF_ENABLE_XLA=1 
> > > > > > ./build_rocm_python3
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Error:
> > > > > > ```
> > > > > > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > > > > > error: Failure when generating HSACO
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> > > > > 
> > > > > 
> > > > > I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.
> > > > 
> > > > 
> > > > The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `. If the `--define=with_xla_support=false` is false, it also compiled failed.
> > > > ```
> > > > build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
> > > > build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
> > > > build --python_path="/opt/conda/bin/python3"
> > > > build --define=with_xla_support=false
> > > > build --config=rocm
> > > > build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
> > > > build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
> > > > build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
> > > > build:opt --copt=-Wno-sign-compare
> > > > build:opt --host_copt=-Wno-sign-compare
> > > > test --flaky_test_attempts=3
> > > > test --test_size_filters=small,medium
> > > > test --test_env=LD_LIBRARY_PATH
> > > > test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
> > > > test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
> > > > test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
> > > > test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The GPU's name is gfx906 in our machine. LLVM version:
> > > > ```
> > > > llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
> > > > llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
> > > > Target: x86_64-unknown-linux-gnu
> > > > Thread model: posix
> > > > InstalledDir: /opt/rocm-4.3.1/llvm/bin
> > > > ```
> > > 
> > > 
> > > It compiles successfully on my end with `--define=with_xla_support=true`. I did an installation in centos-7.9 container too.
> > 
> > 
> > Could you share the Bazel compile command in centos 7.9 with devtools 7.3.1?
> > ```
> > yes "" | ROCM_PATH=$ROCM_PATH TF_NEED_ROCM=1 PYTHON_BIN_PATH=${PYTHON_EXE} ./configure
> > bazel build -j 20 --config=opt --config=rocm --copt="-I/opt/rh/devtoolset-7/root/usr/include/c++/7" --copt="-L/opt/rh/devtoolset-7/root/usr/lib64" --copt="-static-libstdc++" --copt="-L/opt/rocm/lib64" //tensorflow/tools/pip_package:build_pip_package --verbose_failures
> > ```
> 
> `bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

Thanks for replying. 
Maybe I can disable the mlir when comipling with `TF_ENABLE_MLIR=0`, but `--define=with_xla_support=false` seems not working.

**Comment by hclearner** [comment]
> 
> 
> > > > > > ROCm: 4.3.1 TensorFlow Version: 2.7 Operating System: centos 7.9 GCC: devtools-7.3.1 LLVM: https://repo.radeon.com/rocm/yum/4.3.1/
> > > > > > Compile command:
> > > > > > ```
> > > > > > TF_ENABLE_MLIR=1 
> > > > > > TF_ENABLE_XLA=1 
> > > > > > ./build_rocm_python3
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Error:
> > > > > > ```
> > > > > > bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--tile_sizes=256' '--max-supported-rank=5' '--arch=gfx906' '--input=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16.mlir' '--output=bazel-out/k8-opt/bin/tensorflow/core/kernels/mlir_generated/cast_gpu_i64_i16_kernel_generator_kernel.o' '--enable_ftz=False' '--cpu_codegen=False' '--jit=False'
> > > > > > error: Failure when generating HSACO
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Should I recompile the llvm with `-DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" ` ? Thank you :)
> > > > > 
> > > > > 
> > > > > I tried to reproduce the error the our end. However, there is no issue when I run the command in our docker container. It would be appreciated if you could share your docker container with us. Thank you.
> > > > 
> > > > 
> > > > The Operating System that I compiled tensorflow_rocm is centos 7.9 not ubuntu. Could you share the configuration in `.tf_configure.bazelrc `. If the `--define=with_xla_support=false` is false, it also compiled failed.
> > > > ```
> > > > build --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
> > > > build --action_env PYTHON_LIB_PATH="/opt/conda/lib/python3.6/site-packages"
> > > > build --python_path="/opt/conda/bin/python3"
> > > > build --define=with_xla_support=false
> > > > build --config=rocm
> > > > build --action_env LD_LIBRARY_PATH="/opt/rocm-4.3.1//miopen/lib:/opt/rocm-4.3.1//rocblas/lib:/opt/rocm-4.3.1//lib:/opt/rocm-4.3.1//lib64:/opt/rocm-4.3.1//opencl/lib/x86_64:/opt/rocm-4.3.1//hip/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
> > > > build --action_env ROCM_PATH="/opt/rocm-4.3.1/"
> > > > build --action_env ROCBLAS_TENSILE_LIBPATH="/opt/rocm-4.3.1//lib/library"
> > > > build:opt --copt=-Wno-sign-compare
> > > > build:opt --host_copt=-Wno-sign-compare
> > > > test --flaky_test_attempts=3
> > > > test --test_size_filters=small,medium
> > > > test --test_env=LD_LIBRARY_PATH
> > > > test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
> > > > test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
> > > > test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
> > > > test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The GPU's name is gfx906 in our machine. LLVM version:
> > > > ```
> > > > llvm-amdgpu-13.0.0.21313.40301-59.el7.x86_64
> > > > llvm-amdgpu-alt-13.0.0.21262.40301-59.el7.x86_64
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.1 21313 286c48af238c2d3a24ebc5a06ea5191f333eaed0)
> > > > Target: x86_64-unknown-linux-gnu
> > > > Thread model: posix
> > > > InstalledDir: /opt/rocm-4.3.1/llvm/bin
> > > > ```
> > > 
> > > 
> > > It compiles successfully on my end with `--define=with_xla_support=true`. I did an installation in centos-7.9 container too.
> > 
> > 
> > Could you share the Bazel compile command in centos 7.9 with devtools 7.3.1?
> > ```
> > yes "" | ROCM_PATH=$ROCM_PATH TF_NEED_ROCM=1 PYTHON_BIN_PATH=${PYTHON_EXE} ./configure
> > bazel build -j 20 --config=opt --config=rocm --copt="-I/opt/rh/devtoolset-7/root/usr/include/c++/7" --copt="-L/opt/rh/devtoolset-7/root/usr/lib64" --copt="-static-libstdc++" --copt="-L/opt/rocm/lib64" //tensorflow/tools/pip_package:build_pip_package --verbose_failures
> > ```
> 
> `bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

I find that this error will occur if there is no directory `/opt/rocm`.
After I modify this file  `./tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc`, it compiled successful.

I tested the xla with rocm based the tensorflow benchmark `https://github.com/tensorflow/benchmarks`.
The result of training vgg16 with xla off or on is only 3 samples speedup. Could you share your speedup?

**Comment by weihanmines** [comment]
Hi hcleaner,
Has the compilation problem has been solved? If so, I will close this ticket. Thank you for contacting us.

**Comment by hclearner** [comment]
> 
> 
> Hi hcleaner, Has the compilation problem has been solved? If so, I will close this ticket. Thank you for contacting us.

Yes, has been solved, thanks.
