### ISSUE TITLE
2.6.2 whls on pypi are 2.6.0?

### ISSUE THREAD

**Issue by justinkb** [ROCmSoftwarePlatform/tensorflow-upstream#1488]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-rocm 2.6.2
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: pip in venv
- ROCm/MIOpen version: 4.5.0
- GPU model and memory: RX 6800 16GB

The 2.6.2 tensorflow-rocm precompiled whls on pypi don't seem to be the right version. Not only do they report tensorflow.\_\_version\_\_ 2.6.0, but the fact they have the compatibility bug with keras>=2.7.0 confirms they aren't the right version. tensorflow 2.6.2 was released purely to fix that bug.

**Comment by stevenireeves** [comment]
@justinkb The python versioning on pypi is an unfortunate side-effect of the way pypi handles version numbers when the wheels are re-uploaded. The next real version of tensorflow-rocm will be 2.7.0. Sorry for the confusion.
