### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Kadantte** [ROCmSoftwarePlatform/tensorflow-upstream#149]
Any Supp for Windows 10 ?!

**Comment by whchung** [comment]
The project currently depends on ROCm stack which only supports Linux at this moment.

There are other projects going on within AMD to enable HIP-based applications such as this project onto other platforms. Please stay tuned.

**Comment by mkankana** [comment]
@whchung is this still the status of windows support.

**Comment by whchung** [comment]
Windows is yet supported (3/21/2019).

But if you monitor changes on HIP:
https://github.com/ROCm-Developer-Tools/HIP/pulls?q=is%3Apr+is%3Aclosed

you should be able to find some traces to suggest HIP applications would (hopefully soon) run on Windows.
