### ISSUE TITLE
Tensorflow spamming kern.log

### ISSUE THREAD

**Issue by roblem** [ROCmSoftwarePlatform/tensorflow-upstream#1492]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- Upstream amdgpu graphics driver
- TensorFlow installed from (source or binary): docker rocm/tensorflow:latest
- 2 x radeon vii 

**Custom code**

Any tensorflow call places causes these logging messages, e.g.:

```
import tensorflow
x = tf.constant(1.)
```
The logging problem is being exacerbated by looping over tensorflow models using `multiprocessing` and placing work on both gpus for concurrent computation.  This can cause hundreds of these messages per second.  In one day of work, I had a 9GB `kern.log` file.

**Other info / logs**:

Getting gigabytes of messages like this:
```

kernel: [  302.345219] amdgpu 0000:b5:00.0: amdgpu: [sdma1] address:0x000000000ac30000 src_id:247 ring:2 vmid:8 pasid:32775, for process python3 pid 7627 thread python3 pid 7627
kernel: [  302.357410] amdgpu 0000:b5:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
kernel: [  302.357421] amdgpu 0000:b5:00.0: amdgpu: [sdma1] address:0x000000000aec8000 src_id:247 ring:2 vmid:8 pasid:32775, for process python3 pid 7627 thread python3 pid 7627
kernel: [  302.370919] amdgpu 0000:b5:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
kernel: [  302.370930] amdgpu 0000:b5:00.0: amdgpu: [sdma1] address:0x000000000b160000 src_id:247 ring:2 vmid:8 pasid:32775, for process python3 pid 7627 thread python3 pid 7627
kernel: [  302.377871] amdgpu 0000:b5:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
kernel: [  302.377882] amdgpu 0000:b5:00.0: amdgpu: [sdma1] address:0x000000000b3f8000 src_id:247 ring:2 vmid:8 pasid:32775, for process python3 pid 7627 thread python3 pid 7627
kernel: [  302.886529] amdgpu 0000:19:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
kernel: [  302.886540] amdgpu 0000:19:00.0: amdgpu: [sdma0] address:0x0000000001070000 src_id:247 ring:6 vmid:8 pasid:32775, for process python3 pid 7627 thread python3 pid 7627
```
Maybe related to https://github.com/RadeonOpenCompute/ROCm/issues/1495, and after further digging indicates the error may be device to device copying, which is odd because the simple code above is only using gpu0. 

Apart from the messages and disk usage in logs, I don't believe I am encountering performance issues/bad computations.

**Comment by jayfurmanek** [comment]
Hi @roblem !
Thanks for the report. We've seen this before on non-LTS kernels (https://github.com/RadeonOpenCompute/ROCm/issues/1507)

To make this go away, you likely have to move to a supported ROCm/Ubuntu/kernel combination as listed here:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

**Comment by roblem** [comment]
Thanks.  With the radeon vii, I was trying to use a recent kernel >=5.13 so I could run rocm outside of docker.  As described in this thread due to ECC memory issues in the old versus new kernel (see https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1388), the only way to do this was to upgrade the kernel in 20.04 by compiling from source.  I was still unable to successfully run tensorflow code with this setup with the same error message,   so I upgraded to 21.10. 

Unfortunately, I couldn't install rocm locally (not in docker) because the python version in 20.10 was too new.  So I threw in the towel and started using the docker image.  Apart from that it is working fine as long as you use `tf.int32` rather than `tf.int64` dtypes.  

I am going to suppress those messages in the logs to avoid the spam and stay with what I have. 

It has been quite a battle keeping the Radeon VII running with ROCM release since none of the supported platforms have a kernel new enough to avoid the ECC memory issue.....
