### ISSUE TITLE
'stream:all' missing in RunMetadata

### ISSUE THREAD

**Issue by MikalaiDrabovich** [ROCmSoftwarePlatform/tensorflow-upstream#150]
1) 'stream:all' data is missing in RunMetadata for rocm, but it is always present in cuda. That's critical since  that's where native tfprof and also tensorscope take op gpu time ( 'acc time').

I diff'ed device_tracer_rocm.cc with cuda variant and the part which adds to  'stream:all' looks ok - data is being added to stream:all , yet it doesn't appear in RunMetadata - @eshcherb @whchung please take a look of what's going on with stream:all 
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/81544e88eb6f916b1e0ac4a9eb85d83edac8d906/tensorflow/core/platform/default/device_tracer_rocm.cc#L289

2) Not critical but nice to follow the same format: -  'stream:N' (where N is some int number) streams in rocm contain only memcpy ops, but should also include other ops (sum of times from all n streams will be equal to times stream:all)

**Comment by whchung** [comment]
@MikalaiDrabovich since the implementation you referred to is in #107 which is not merged. can we move the discussion over there? closing this ticket hereby.
