### ISSUE TITLE
TF 2.7.0: Failed compilation due to error: hipStream_t has not been declared

### ISSUE THREAD

**Issue by perestoronin** [ROCmSoftwarePlatform/tensorflow-upstream#1512]
**System information**
- OS Platform and Distribution: Gentoo
- TensorFlow installed from: source
- TensorFlow version: 2.7.0
- Python version: 3.9.9
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 11.2.0
- ROCm/MIOpen version: 4.5.2
- GPU model and memory: Vega Frontier Edition

**Describe the problem**
failed compilation due to error: `‘hipStream_t’ has not been declared`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`USE="rocm" emerge tensorflow`

**Any other info / logs**
[hipconfig -f](https://gist.github.com/raw/d3fc24c29fd8527988bbc07874d52662)
[build.log](https://gist.github.com/raw/fe72bfd31a076643a9a950f317356032)

**Comment by lubosz** [comment]
How did you resolve this? I am seeing the same on ArchLinux.
