### ISSUE TITLE
the difference between miopen and miopengemm

### ISSUE THREAD

**Issue by guojunxia** [ROCmSoftwarePlatform/tensorflow-upstream#1523]
I'm reading the miopen documents (https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#miopen) and i'm confused about the defferences between  miopen and miopengemm .
I'm totally a beginner in this ,can someone help me figure this out?

**Comment by stevenireeves** [comment]
@guojunxia Hello, MiOpenGEMM  is an OpenCL GEMM library. I would only use MIOpen, as it is the main ROCm kernels library. Checkout https://github.com/ROCmSoftwarePlatform/MIOpen for any more questions on MIOpen.
