### ISSUE TITLE
Do you have a plan to support Hawaii or Tonga GPUs?

### ISSUE THREAD

**Issue by kyt9601** [ROCmSoftwarePlatform/tensorflow-upstream#154]
Hello sir,

I have a r9 290x, and I tired to run tensorflow with ROcm and this rocm-ported tf.
I was able to install ROcm stack with no problem, but when I ran rocm-ported tf, I noticed that it only supports AMD ISA gfx803 or newer.

Do you have a plan to support GPUs like gfx701 Hawaii 290X or gfx802 Tonga 380?

**Comment by whchung** [comment]
Hawaii and Tonga won’t be on the roadmap for this project unfortunately.
