### ISSUE TITLE
Tensorflow Serving support

### ISSUE THREAD

**Issue by boniek83** [ROCmSoftwarePlatform/tensorflow-upstream#1657]
### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
I was really surprised to see there's no official container image for Tensorflow Model Serving available. Is this planned at all?
```

### Standlone code to reproduce the issue

```shell
-
```

**Comment by i-chaochen** [comment]
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1869
