### ISSUE TITLE
Tensorflow unstable?

### ISSUE THREAD

**Issue by lukas6464** [ROCmSoftwarePlatform/tensorflow-upstream#166]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 with Tensorflow 1.8 nad ROCm 1.9
- **GPU model and memory**: Radeon RX 480

### Describe the problem
I previously had the same MIOpen Error as in Issue #93 and Issue #142. By updating to ROCM 1.9 this error (in this problem at least) has disappeared. However, training appears to be very volatile. During the first epoch, a seemingly random step will fail with either the message `CtxFailure at reshape_op.h:82: Invalid argument: Input to reshape is a tensor with 8000 values, but the requested shape has 0` or `tensorflow.python.framework.errors_impl.OutOfRangeError: box_index has values outside [0, batch_size)` or `WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5830 elements; but when writing their indices, saw 1380 elements.`

### Source code / logs

The code is based on matterport's MaskRCNN (trainshapes.py) which would have to be installed and the images are quite large, so I have only included a very few.  I was able to train using tensorflow-cpu, so the code does seem to work. 

[bbc-mwe.zip](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2386781/bbc-mwe.zip)

**Comment by sunway513** [comment]
@lukas6464 ROCm TF1.10 is released, could you try that and let us know if the issue can be fixed there?
It would be helpful if you can try with docker images: 
https://hub.docker.com/r/rocm/tensorflow/

**Comment by whchung** [comment]
related issue: https://github.com/tensorflow/tensorflow/issues/6378

could you help tune GPU VRAM usage and see if the issue gets away?

**Comment by lukas6464** [comment]
> @lukas6464 ROCm TF1.10 is released, could you try that and let us know if the issue can be fixed there?
> It would be helpful if you can try with docker images:
> https://hub.docker.com/r/rocm/tensorflow/

Is it also possible to install without docker? I tried this, but can't seem to get it running. That is, I installed docker, downloaded the image, installed my dependencies, but can't get it  or a jupyter notebook running. 
--
However, this does sound very much like the issue referenced below. Could you perhaps elaborate on what you mean with tuning gpu vram usage? I'm not sure what you mean with tuning

**Comment by ericjang** [comment]
I am running into this problem as well, using TF1.10 with docker, training a Tensor2Tensor model. I am fairly certain this is not an issue with batch size or input size, but rather some bug in the underlying ROCM layer( I don't run into issues training these models on an NVIDIA Titan X).

If you want to reproduce my error case, here's my Docker file:
```
FROM tf1.10:latest # ROCM TF 1.10 image
RUN pip3 install Pillow
RUN pip3 install gym sympy flask gevent gunicorn h5py mesh-tensorflow oauth2client requests tqdm tensorflow-datasets google-api-python-client
RUN pip3 install tensor2tensor --no-deps
```
I run it as follows (fairly vanilla command):

```
alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx -v $HOME/scratch_code:/scratch_code -v $HOME/data:/data -v $HOME/experiments:/experiments -v $HOME/tmp:/tmp'

drun t2t:latest bash -c "t2t-trainer \
  --problem=video_bair_robot_pushing \
  --model=next_frame_sv2p \
  --hparams_set=next_frame_sv2p \
  --schedule=train \
  --generate_data \
  --alsologtostderr \
  --train_steps=50000 \
  --output_dir=/experiments/t2t_train/bair \
  --data_dir=/data/t2t_data/ \
  --tmp_dir=/tmp/
```

and after a few hours of training, I get the following error:
```
alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx -v $HOME/scratch_code:/scratch_code -v $HOME/da
ta:/data -v $HOME/experiments:/experiments -v $HOME/tmp:/tmp'

drun t2t:latest bash -c "t2t-trainer \
  --problem=video_bair_robot_pushing \
  --model=next_frame_sv2p \
  --hparams_set=next_frame_sv2p \
  --schedule=train \
  --generate_data \
  --alsologtostderr \
  --train_steps=50000 \
  --output_dir=/experiments/t2t_train/bair \
  --data_dir=/data/t2t_data/ \
  --tmp_dir=/tmp/

```

This error seems to come up a few hours into training. It also happens when I train smaller models like a MNIST VAE (multiple copies of the same model back to back).

I find that rebooting the machine seems to fix the issue sometimes, but I'm not certain if it's related.

**Comment by sunway513** [comment]
@ericjang , can you set the following environment variable and provide your full logs that show the failure?
```export MIOPEN_ENABLE_LOGGING=1```

**Comment by sunway513** [comment]
@lukas6464 @ericjang any updates on your issue?
Please try our latest docker image based on ROCm2.1:
rocm/tensorflow:rocm2.1-tf1.12-python3
If the problem persists, it would be helpful if you were able to provide us with the exact steps to reproduce or the logs we requested.

**Comment by sunway513** [comment]
I'm closing this issue, please reopen it if there are further questions.
