### ISSUE TITLE
After installing tensorflow-rocm whl v 0.0.1

### ISSUE THREAD

**Issue by alexja14** [ROCmSoftwarePlatform/tensorflow-upstream#177]
### Describe the problem
I tried to install tensorflow. So i installed the whl.. but its version 0.0.1. After I install this whl how do i efectivly install tensorflow ? Thank you for your time.

### Source code / logs
pip3 install tensorflow-rocm
Collecting tensorflow-rocm
  Using cached https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl
Installing collected packages: tensorflow-rocm
Successfully installed tensorflow-rocm-0.0.1

**Comment by whchung** [comment]
@alexja14 You probably want to disable your pip cache with `--no-cache-dir`. For example:

```
pip3 --no-cache-dir install tensorflow-rocm
```

The latest released version if 1.10.1:
https://pypi.org/project/tensorflow-rocm/#history

**Comment by whchung** [comment]
@alexja14 I believe the answer above should get your issue resolved. I'm closing this ticket hereby. Please feel free to re-open it, or create new tickets should you find other issues. Thanks.

**Comment by whchung** [comment]
It seems there could be some issue in your Python installation. Could you try with:

```
pip3 --no-cache-dir -vvv install tensorflow-rocm
```

to see what's causing the error that version `1.10.1` is not picked up?

**Comment by alexja14** [comment]
Skipping link https://files.pythonhosted.org/packages/7b/60/ba3b183169a0ecb9359b7d99d1e60e257cb2d964284bc022fb9153c1afcc/tensorflow_rocm-1.10.1-cp27-cp27mu-manylinux1_x86_64.whl#sha256=9bb91f875e076d9ac88bccf2364f4840be7a934883a2644db282f064aa16339e (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python

I got : python3 -V
Python 3.6.6

**Comment by whchung** [comment]
/cc @parallelo for awareness

@alexja14 in your log was `tensorflow_rocm-1.10.1-cp35-cp35m-manylinux1_x86_64.whl` checked? it'd be great if you could post the entire log here.

if true, this could be a genuine issue that PIP package generate for Python 3.5 is not compatible with Python 3.6. please help re-open this ticket and we'll need to address it.
