### ISSUE TITLE
"ROCm Fusion is enabled" appears all the time in the terminal when predicting/training a model

### ISSUE THREAD

**Issue by Mushoz** [ROCmSoftwarePlatform/tensorflow-upstream#1779]
This issue is a duplicate of https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1141 , but that one was closed with no resolution. Is there any way to disable this spam? It's making it very difficult to quickly go over the log to see what's happening.

**Comment by i-chaochen** [comment]
Have you tried to add this into your code?

```
import os  
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  
```

Basically, you can control the INFO, WARNING and ERROR message by yourself.
https://stackoverflow.com/questions/35869137/avoid-tensorflow-print-on-standard-error

0 = all messages are logged (default behavior)
1 = INFO messages are not printed
2 = INFO and WARNING messages are not printed
3 = INFO, WARNING, and ERROR messages are not printed

**Comment by Mushoz** [comment]
I have. The message is being printed regardless of verbosity. There seems to be no way to control this.

**Comment by i-chaochen** [comment]
Wondering what’s your version? As I have disabled it in my side by setting it to ‘3’


As a side note, it’s a string 3 not int 3

**Comment by Mushoz** [comment]
Duh, using a string rather than an int did the trick. Thanks! And my apologies for my brainfart :-)
