### ISSUE TITLE
Need WHL be compatible with Python 3.6

### ISSUE THREAD

**Issue by alexja14** [ROCmSoftwarePlatform/tensorflow-upstream#178]
@parallelo 

### Describe the problem
I tried to install tensorflow-rocm but it sems that: 

pip3 --no-cache-dir -vvv install tensorflow-rocm

gets me the version. 0.0.1

Thank you for your time. Opened for tests if u need to solve this issue .

### Source code / logs
This is the full log.

pip3 --no-cache-dir -vvv install tensorflow-rocm
Collecting tensorflow-rocm
  1 location(s) to search for versions of tensorflow-rocm:
  * https://pypi.python.org/simple/tensorflow-rocm/
  Getting page https://pypi.python.org/simple/tensorflow-rocm/
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/tensorflow-rocm/ HTTP/1.1" 301 122
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/tensorflow-rocm/ HTTP/1.1" 200 891
  Analyzing links from page https://pypi.org/simple/tensorflow-rocm/
    Found link https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl#sha256=22a762c79b984801d995c2f17330a983719d392e45f8644e8fdfed5c7161b001 (from https://pypi.org/simple/tensorflow-rocm/), version: 0.0.1
    Skipping link https://files.pythonhosted.org/packages/d1/47/efa7df3559e2a21d05668364bbe284a58ac10d99355da59a24f34ecc4b69/tensorflow_rocm-1.8.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=0e3dfedec82dcb561870bf8e25c0c826c9b31f000ceeb521e21b992e81668a48 (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/0a/32/5c7cf4dbaf7805d5cbe8a4eb35efbda57602d66e014029660500c62f994d/tensorflow_rocm-1.8.0-cp35-cp35m-manylinux1_x86_64.whl#sha256=d2ae972b381b0d744da48f9f9306711875c86b188dc5ee979fd28711e33ce582 (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/17/e0/9e4eac63a8949c99c4384aa5beb14b33324a3a24bb2510ed52e83bfd1717/tensorflow_rocm-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=effc49d5ec7385c0dc1805f7d722c5194088f5088dfdcba1bf1fd2009dccaaf4 (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/6c/ee/7dbabd2f7d030c82f3260ca762c251283a09252ca14610cfe39f08c89d40/tensorflow_rocm-1.10.0-cp35-cp35m-manylinux1_x86_64.whl#sha256=ad4a5445585c176c7d0aabc3f02098a7c58fb26ba85f9ebb7464e2c35205ecad (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/7b/60/ba3b183169a0ecb9359b7d99d1e60e257cb2d964284bc022fb9153c1afcc/tensorflow_rocm-1.10.1-cp27-cp27mu-manylinux1_x86_64.whl#sha256=9bb91f875e076d9ac88bccf2364f4840be7a934883a2644db282f064aa16339e (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/e5/dd/50a1635ab38f67d3f300669feef3c8fbec38820e12821fb84665b8f1d56f/tensorflow_rocm-1.10.1-cp35-cp35m-manylinux1_x86_64.whl#sha256=ff7bce2fa036820b5452f7dba44cf20541c81c0f23127ccab28bd18385ffd943 (from https://pypi.org/simple/tensorflow-rocm/); it is not compatible with this Python
  Using version 0.0.1 (newest of versions: 0.0.1)
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl HTTP/1.1" 200 1603
  Downloading https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl
  Downloading from URL https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl#sha256=22a762c79b984801d995c2f17330a983719d392e45f8644e8fdfed5c7161b001 (from https://pypi.org/simple/tensorflow-rocm/)
Installing collected packages: tensorflow-rocm

Successfully installed tensorflow-rocm-0.0.1
Cleaning up...

**Comment by whchung** [comment]
Additional info from OP: using UB 18.04+python 3.6.6

**Comment by alexja14** [comment]
Do u guys know how to solve this ? 
pc spec. ryzen 2700 x
moba X470 AORUS ULTRA GAMING-CF
graphic cards: 2x radeon 580x (Polaris GPU) 
ram : Type: DDR4
	Type Detail: Synchronous Unbuffered (Unregistered)
	Speed: 2133 MT/s

**Comment by whchung** [comment]
@alexja14 I'm not that familiar with PIP and publishing to PyPI. @parallelo is on vacation and will be back later this week. From the current information it seems we need to publish a new release with WHL compatible with Python 3.6 so I just renamed the title of the ticket.

**Comment by whchung** [comment]
@parallelo please help setup an UB18.04 system which contains Python 3.6.6 (this is the software config reported by @alexja14 in #177), and check how `tensorflow-rocm` package can be amended to support Python 3.6.

**Comment by parallelo** [comment]
FYI - We're testing this with our internal build process now.  Will have some further details tomorrow.

**Comment by parallelo** [comment]
Hi @alexja14 - We're still working on it.  Will update this thread when complete.

**Comment by alexja14** [comment]
Ok thank you very much.

**Comment by parallelo** [comment]
Quick update:  We've got py3.6 whl files being built in our pipeline now.  Will let you know when we post one to PyPI.

**Comment by alexja14** [comment]
I'm ready to test 🦊 
Tell me when it's green light.

**Comment by parallelo** [comment]
Just uploaded to PyPI.  Assuming you've got Python 3.6 already installed, you can try something like this:  
```
sudo apt update
sudo apt install rocm-libs miopen-hip cxlactivitylogger
sudo apt install python3-pip
pip3 install --user tensorflow-rocm
```

**Comment by briansp2020** [comment]
@parallelo The main readme should mention that

> sudo apt install rocm-libs miopen-hip cxlactivitylogger

is required. Other than that, I was able to install tf on Ubuntu 18.04

Thanks!

**Comment by parallelo** [comment]
The installation of those packages are included in our documentation; however, they are somewhat hidden among lots of other details.  Our README.ROCm.md file points to [tensorflow-install-basic.md](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md), which focuses on installing pre-built packages.

However, you make a good point -- we need to simplify those instructions considerably now that the process is much more streamlined.  We'll take care of that.  Thanks for the feedback.  

I'll close this ticket; but @alexja14, please feel free to reopen it if you hit any related installation issues.

**Comment by alexja14** [comment]
Good evening

After another 4 installs of ubuntu i made it work with your procedure. I think it should be specified in the main project description about the :
"sudo apt install rocm-libs miopen-hip cxlactivitylogger"

. In the end people that wanna use tensorflow on rocm it's cuz they wanna use the AMD GPU. 

Thank you very much for your help and update. 

Have a great week.
