### ISSUE TITLE
Mac Os

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [ROCmSoftwarePlatform/tensorflow-upstream#185]
Is it possible to build this for using discrete gpu (AMD radeon pro 555 2gb) on macbook pro? I found that tensorflow uses only CPU while calculations :(

**Comment by Mandrewoid** [comment]
I'm not AMD or affiliated with AMD, So don't quote me on this, but it looks like your CPU/GPU combination are supported for rocm (Radeon pro 555 is polaris based, macbook pro CPU is kabi lake)

Unfortunately Mac OS is _**not**_ supported. If you are determined to get this going, you will have to install Ubuntu on your macbook. There are guides for this available online, and probably user groups as well. I don't endorse any specific ones as I am not an apple owner. You can install it alongside Mac OS as long as you have enough space on your storage drive. If you search on Youtube, this is the first result, and makes it look easy. https://www.youtube.com/watch?v=kRgKlcm1XPI

If and once you have completed all that, you will have to get the ROCm stack up and running https://rocm.github.io/ROCmInstall.html Only then will you be able to install this tensorflow package, and get on with your project. 

If you do choose to proceed with this endeavour, I'm sure there will be many people here interested in your progress

**Comment by whchung** [comment]
@georgeMuraveiAlkh just like #184, Mac OS X is not an officially supported target yet. There are efforts being actively made to allow all HIP-based applications (such as TensorFlow ROCm port) run on hardware / software configurations not supported at this moment.

Like @Mandrewoid suggested, for the time being you can try install Ubuntu on your Macbook pro.

**Comment by xiaoyu830411** [comment]
If we choose other OS, why we don’t use Nvidia. Now the Mojave just supports AMD eGPU,  it is an opportunity to AMD. If APPLE company decides to support NV on eGPU, I think many people will choose Nvidia.

Now we just have one way for deep learning that we can choose Nvidia GTX series on 10.13.x (High Sierra).

**Comment by Degerz** [comment]
@xiaoyu830411 Don't blame AMD for Apple's own problems. AMD only supplies Apple with their GPUs on macOS, they have **ZERO** control over how either the graphics or compute stack works with macOS. It could've been possible if their Metal API was designed as a single source language but the [reality](https://github.com/ROCm-Developer-Tools/HIP/issues/150) is Apple doesn't care about having an alternative to CUDA ... 

It's entirely Apple's fault that they don't care about high end compute or machine learning ...

**Comment by sunway513** [comment]
Hi @georgeMuraveiAlkh , tensorflow-rocm project depends on ROCm support for operating systems. Could you continue the discussion on ROCm repo?
https://github.com/RadeonOpenCompute/ROCm
