### ISSUE TITLE
Does tensorflow ROCm support Tensorflow Serving?

### ISSUE THREAD

**Issue by ndeepesh** [ROCmSoftwarePlatform/tensorflow-upstream#1869]
### Issue Type

Others

### Source

source

### Tensorflow Version

tf 2.4

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.8

### Current Behaviour?

```shell
Question - Is TF Serving supported for AMD GPU's aka ROCm?
```

### Standalone code to reproduce the issue

```shell
NA
```

**Comment by jayfurmanek** [comment]
It does work, but currently you have to build it yourself.
I've created a dockerfile that will do that if you are interested:

https://github.com/jayfurmanek/serving/tree/rocm53
