### ISSUE TITLE
Problem running Matterport/Mask_RCNN

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/tensorflow-upstream#190]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04/ROCm 1.9
- **TensorFlow installed from (source or binary)**: docker pull rocm/tensorflow
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.5.2
- **GPU model and memory**: Vega FE
- **Exact command to reproduce**:

> docker pull rocm/tensorflow
docker run -it -p 8888:8888 -p 6006:6006 -p 8097:8097 --ipc=host rocm/tensorflow /bin/bash
pip3 install ipython pandas opencv-python scikit-image jupyter imgaug cython
pip3 install keras==2.1.6
git clone https://github.com/cocodataset/cocoapi
cd cocoapi/PythonAPI
python3 setup.py build_ext install
cd ../..
git clone https://github.com/matterport/Mask_RCNN
cd Mask_RCNN/samples
jupyter notebook --allow-root --ip=0.0.0.0

### Describe the problem
Running demo.ipynb in samples directory fails with

> terminate called after throwing an instance of 'ihipException'
  what():  std::exception

I used to be able to run Matterport Mask_RCNN with ROCm TensorFlow before...

Some other issues I'm having are
1. I'm having issue installing tensorflow directly. There is already a report here. https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/178
2. Runner rocminfo in docker fails with

> hsa api call failure at line 900, file: /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/rocminfo/rocminfo.cc. Call returned 4104

**Comment by briansp2020** [comment]
@sunway513 
Thank you. That worked.

**Comment by briansp2020** [comment]
It seems there were multiple issues reported that was caused because people did not know to specify all the options necessary to run docker properly. Probably worth mentioning it in the main read me. I know that it's mentioned in the rocm-docker repo. But, I think it's worth repeating.

Closing this issue.

Thank you.

**Comment by sunway513** [comment]
Thanks @briansp2020 , we have documented the docker run command on the dockerhub info page:
https://hub.docker.com/r/rocm/tensorflow/
And yes, we are trying to improve the documentation, will add more comprehensive instructions.
