### ISSUE TITLE
ROCm TensorFlow install instructions for Ubuntu 18.04

### ISSUE THREAD

**Issue by nsburbank** [ROCmSoftwarePlatform/tensorflow-upstream#206]
The install misc pkgs portion of the basic installation instructions (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md) don’t work with Ubuntu 18.04, because the clang-3.8 packages aren’t available for 18.04. With 3.9 substituted for 3.8, install seems to work fine.

The current instructions do recommend using Ubuntu 16.04, but the generic ROCm documentation now specifies 16.04 and 18.04 as supported.

**Comment by whchung** [comment]
@nsburbank Could you confirm if it's only `clang-3.8` which has to be changed? What about `clang-format-3.8` and `clang-tidy-3.8`? I'll need to get an UB 18.04 installation to test it. If you could share the exact diff of packages in your working environment that'd be very helpful.

**Comment by whchung** [comment]
@nsburbank / @witeko Thanks I've updated the documentation. Closing this ticket hereby.
