### ISSUE TITLE
3D Convolution

### ISSUE THREAD

**Issue by maxzoech** [ROCmSoftwarePlatform/tensorflow-upstream#209]
Hi!

I am trying to run a 3D Convolution but I am getting an error that IMOpen only supports 4D Tensors, Not 5D which I need. But [this list ](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/core_kernels.md) says that Conv3D is implemented in ROCm.

Could someone please explain to me why it doesn’t work and how (if possible) I can fix it.
Yours,
Max

**Comment by whchung** [comment]
@maxzoech the list is a bit misleading that basically it means operators in those files are successfully built and registered with TensorFlow ROCm port so it can be used from Python. But to get the the operators running properly we need StreamExecutor to pick up the right APIs in MIOpen. And thus far we are only using 2D convolution algorithms in MIOpen from TensorFlow at this moment, hence you are experiencing this issue.

@zjing14 knows better about the status of 3D convolution algorithms in MIOpen. @zjing14 , could you help weigh in here?

**Comment by sunway513** [comment]
Hi @maxzoech , could you ask the question in MIOpen repo?
https://github.com/ROCmSoftwarePlatform/MIOpen

**Comment by sunway513** [comment]
Hi @daniellowell , could you update the status of 3D convolution algorithms in MIOpen?

**Comment by ZiyueWangUoB** [comment]
Yes any update on this?

**Comment by odellus** [comment]
I opened an issue about it on MIOpen 7 months ago. Also looking forward to hearing back about this tatus. 
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/46

**Comment by daniellowell** [comment]
3D convolutions are slated for MIOpen 1.8 release.
