### ISSUE TITLE
gfx 7 card with ROCm tensorflow

### ISSUE THREAD

**Issue by MLnewby** [ROCmSoftwarePlatform/tensorflow-upstream#225]
Hi everyone,

i installed the recent ROCm Tensorflow release 1.11 and had hoped, that i can use my gfx7 card for Deep Learning in Tensorflow. Since it is stating in the ROCm documentation:
"The following list of GPUs are likely to work within ROCm, though full support is not guaranteed:
    GFX7 GPUs
        “Hawaii” chips, such as the AMD Radeon R9 390X and FirePro W9100"

After setting everything up and starting an Tensorflow example i get the following error:
"Ignoring visible gpu device with AMDGPU ISA gfx 701. The minimum required AMDGPU ISA is gfx803."

Did anyone get a gfx7 card to run with TensorFlow? It would be a pitty when i have to get a new graphics card just because of this software restrictions. Thanks in advance for your advice.

**Comment by whchung** [comment]
unfortunately gfx7 is not supported in this project.

Base ROCm stack and toolchain supports gfx7 but libraries to enable TensorFlow do not.
