### ISSUE TITLE
from tensorflow.python.keras.metrics import Metric ImportError: cannot import name 'Metric'

### ISSUE THREAD

**Issue by KelBel90** [ROCmSoftwarePlatform/tensorflow-upstream#236]
Ubuntu 18.04

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
```

> /usr/bin/python3.5 /home/c/.PyCharmCE2018.2/config/scratches/scratch.py
> Traceback (most recent call last):
>   File "/home/c/.PyCharmCE2018.2/config/scratches/scratch.py", line 1, in <module>
>     import tensorflow as tf
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 81, in <module>
>     from tensorflow.python import keras
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
>     from tensorflow.python.keras import activations
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
>     from tensorflow.python.keras._impl.keras.activations import elu
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
>     from tensorflow.python.keras._impl.keras import activations
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 24, in <module>
>     from tensorflow.python.keras._impl.keras.utils.generic_utils import deserialize_keras_object
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/__init__.py", line 34, in <module>
>     from tensorflow.python.keras._impl.keras.utils.multi_gpu_utils import multi_gpu_model
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/multi_gpu_utils.py", line 22, in <module>
>     from tensorflow.python.keras._impl.keras.engine.training import Model
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/__init__.py", line 21, in <module>
>     from tensorflow.python.keras._impl.keras.engine.base_layer import InputSpec
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 28, in <module>
>     from tensorflow.python.estimator import util as estimator_util
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/__init__.py", line 25, in <module>
>     import tensorflow.python.estimator.estimator_lib
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator_lib.py", line 22, in <module>
>     from tensorflow.python.estimator.canned.baseline import BaselineClassifier
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/canned/baseline.py", line 50, in <module>
>     from tensorflow.python.estimator import estimator
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 34, in <module>
>     from tensorflow.python.estimator import model_fn as model_fn_lib
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/model_fn.py", line 29, in <module>
>     from tensorflow.python.keras.metrics import Metric
> ImportError: cannot import name 'Metric'

Not sure where to start with how to solve the issue. Any input is awesome.  There is a "metrics" file with the path (tensorflow.python.keras.metrics) in my .local folder in Ubuntu under python 3.5. the folder, however, only has a file and a folder in it.

**Comment by pricebenjamin** [comment]
I don't believe this is an issue with `tensorflow-rocm`. I would try reinstalling `tensorflow-rocm` in a clean virutalenv or conda environment.

I didn't have any issue running your script.

**Comment by KelBel90** [comment]
thank you. I follow the directions here. I am still not able to get pycharm to recognize it. no matter which python interpreter i use. Can i ask how you are able to execute the script. many thx of course.

> AMD is hosting both Debian and RPM repositories for the ROCm 1.9.x packages at this time.
> 
> The packages in the Debian repository have been signed to ensure package integrity.
> 
> Ubuntu Support - installing from a Debian repository
> First make sure your system is up to date
> sudo apt update
> sudo apt dist-upgrade
> sudo apt install libnuma-dev
> sudo reboot
> Add the ROCm apt repository
> For Debian based systems, like Ubuntu, configure the Debian ROCm repository as follows:
> 
> wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
> echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
> The gpg key might change, so it may need to be updated when installing a new release. If the key signature verification is failed while update, please re-add the key from ROCm apt repository. The current rocm.gpg.key is not avialable in a standard key ring distribution, but has the following sha1sum hash:
> 
> f7f8147431c75e505c58a6f3a3548510869357a6 rocm.gpg.key
> 
> Install
> Next, update the apt repository list and install the rocm package:
> 
> Warning: Before proceeding, make sure to completely uninstall any previous ROCm package:
> 
> sudo apt update
> sudo apt install rocm-dkms
> Next set your permissions
> With move to upstreaming the KFD driver and the support of DKMS, for all Console aka headless user, you will need to add all your users to the 'video" group by setting the Unix permissions
> 
> Configure Ensure that your user account is a member of the "video" group prior to using the ROCm driver. You can find which groups you are a member of with the following command:
> 
> groups
> To add yourself to the video group you will need the sudo password and can use the following command:
> 
> sudo usermod -a -G video $LOGNAME 
> You may want to ensure that any future users you add to your system are put into the "video" group by default. To do that, you can run the following commands:
> 
> echo 'ADD_EXTRA_GROUPS=1' | sudo tee -a /etc/adduser.conf
> echo 'EXTRA_GROUPS=video' | sudo tee -a /etc/adduser.conf
> Once complete, reboot your system.
> 
> Upon Reboot run the following commands to verify that the ROCm installation waas successful. If you see your GPUs listed by both of these commands, you should be ready to go!
> 
> /opt/rocm/bin/rocminfo 
> /opt/rocm/opencl/bin/x86_64/clinfo 
> Note that, to make running ROCm programs easier, you may wish to put the ROCm libraries in your LD_LIBRARY_PATH environment variable and the ROCm binaries in your PATH.
> 
> echo 'export LD_LIBRARY_PATH=/opt/rocm/opencl/lib/x86_64:/opt/rocm/hsa/lib:$LD_LIBRARY_PATH' | sudo tee -a /etc/profile.d/rocm.sh
> echo 'export PATH=$PATH:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64' | sudo tee -a /etc/profile.d/rocm.sh

**Comment by KelBel90** [comment]
I am installing the following from here: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream 
 now:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/236#issuecomment-437644068
