### ISSUE TITLE
Typo is breaking gfx1100 and gfx1030 support

### ISSUE THREAD

**Issue by JMaravalhasSilva** [ROCmSoftwarePlatform/tensorflow-upstream#2410]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.14.0.600

### Custom code

No

### OS platform and distribution

Ubuntu 22.04

### Current behavior?

When using a 7900 XTX, running this code:
```py
import tensorflow as tf

print("GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

Produces the following output:
 ```
tensorflow/core/common_runtime/gpu/gpu_device.cc:2266] Ignoring visible gpu device (device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0) with AMDGPU version : gfx1100. The supported AMDGPU versions are gfx1030gfx1100, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.
```

Obviously the 7900 XTX should be supported, but notice the part that says **gfx1030gfx1100**.

Clearly, there should be a comma in there, so I believe some typo is currently responsible for making both gfx1030 and gfx1100.

This problem has already been mentioned [here](https://github.com/ROCm/ROCm/discussions/2729) and [here](https://community.amd.com/t5/discussions/rocm-6-0-0-tensorflow-not-working-on-rx-7900-xt/m-p/657562), but I believe that no one has actually opened a github issue about it.

Please note that I tried both installing [tensorflow-rocm](https://pypi.org/project/tensorflow-rocm/) on a venv, and also the official [docker image](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/3rd-party/tensorflow-install.html). Both methods are currently broken.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print("GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

**Comment by ElGatoNinja** [comment]
happening to me, lol

**Comment by pikdum** [comment]
Running into the same:

```
2024-02-24 02:54:50.311991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2266] Ignoring visible gpu device (device: 0, name: Radeon RX 7900 XT, pci bus id: 0000:0c:00.0) with AMDGPU version : gfx1100. The supported AMDGPU versions are gfx1030gfx1100, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.
```

Guessing it's line 184 of `./lib/python3.10/site-packages/tensorflow/include/tensorflow/compiler/xla/stream_executor/device_description.h` .

```diff
   return {
        "gfx900",  // MI25
        "gfx906",  // MI50 / MI60
        "gfx908",  // MI100
        "gfx90a",  // MI200
        "gfx940",  // MI300
        "gfx941",  // MI300
        "gfx942",  // MI300
-       "gfx1030"  // Navi21
+       "gfx1030", // Navi21
        "gfx1100"  // Navi31
    };
```

**Comment by ugcoder** [comment]
> Running into the same:
> 
> ```
> 2024-02-24 02:54:50.311991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2266] Ignoring visible gpu device (device: 0, name: Radeon RX 7900 XT, pci bus id: 0000:0c:00.0) with AMDGPU version : gfx1100. The supported AMDGPU versions are gfx1030gfx1100, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.
> ```
> 
> Guessing it's line 184 of `./lib/python3.10/site-packages/tensorflow/include/tensorflow/compiler/xla/stream_executor/device_description.h` .
> 
> ```diff
>    return {
>         "gfx900",  // MI25
>         "gfx906",  // MI50 / MI60
>         "gfx908",  // MI100
>         "gfx90a",  // MI200
>         "gfx940",  // MI300
>         "gfx941",  // MI300
>         "gfx942",  // MI300
> -       "gfx1030"  // Navi21
> +       "gfx1030", // Navi21
>         "gfx1100"  // Navi31
>     };
> ```

how can fix this issue?

**Comment by cloneable** [comment]
Looks like commit c4ed071cfea966cd280a5d0d6d616eaaf63f6ac3 caused this. Maybe @wenchenvincent or @jayfurmanek can help fix this?

**Comment by jayfurmanek** [comment]
Thanks for finding this!

**Comment by cloneable** [comment]
Thanks a lot for the quick fix, @jayfurmanek! Do you think we could get a 2.14 patch release?

Btw, #2404 is related.

**Comment by jayfurmanek** [comment]
Check here for nightly 2.14 whls:
http://ml-ci.amd.com:21096/job/tensorflow/job/release-rocmfork-r214-rocm-enhanced/job/release-build-whl/
