### ISSUE TITLE
Is there a published version with this bugfix included? https://github.com/ROCm/tensorflow-upstream/pull/2434

### ISSUE THREAD

**Issue by mmmurf** [ROCmSoftwarePlatform/tensorflow-upstream#2487]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

v2.14.0-4246-g996b6d313c1 2.14.0

### Custom code

No

### OS platform and distribution

Ubuntu 22.04 host for rocm/tensorflow:latest

### Python version

3.9.18

### Current behavior?

I am getting the bug that was fixed in this PR: 

https://github.com/ROCm/tensorflow-upstream/pull/2434

I am trying to download a package or use a docker image that includes a rocm/tensorflow that has the bugfix, but I don't know which one to use. 

### Standalone code to reproduce the issue

```shell
# test_tf.py
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

### Relevant log output

```shell
D Radeon RX 6600, pci bus id: 0000:08:00.0) with AMDGPU version : gfx1030. The supported AMDGPU versions are gfx1030gfx1100, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.D Radeon RX 6600, pci bus id: 0000:08:00.0) with AMDGPU version : gfx1030. The supported AMDGPU versions are gfx1030gfx1100, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.
```

**Comment by YellowRoseCx** [comment]
You could do this to build it:
```
git clone https://github.com/ROCm/tensorflow-upstream.git -b r2.14-rocm-enhanced --depth 1
./build_rocm_python3
```

or for the develop-upstream branch:
```
git clone https://github.com/ROCm/tensorflow-upstream.git --depth 1
./build_rocm_python3
```
you'll need bazel 6.1.1 though, https://github.com/bazelbuild/bazel/releases/tag/6.1.1

**Comment by gitleibin** [comment]
> You could do this to build it:
> 
> ```
> git clone https://github.com/ROCm/tensorflow-upstream.git -b r2.14-rocm-enhanced --depth 1
> ./build_rocm_python3
> ```
> 
> or for the develop-upstream branch:
> 
> ```
> git clone https://github.com/ROCm/tensorflow-upstream.git --depth 1
> ./build_rocm_python3
> ```
> 
> you'll need bazel 6.1.1 though, https://github.com/bazelbuild/bazel/releases/tag/6.1.1
could help me how to solve this build problems #2531

**Comment by harkgill-amd** [comment]
Hi @mmmurf, the latest wheels found at https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/ have this fix present.

The fix is also present in newer branches such as https://github.com/ROCm/tensorflow-upstream/tree/r2.18-rocm-enhanced which you can build using the `build_rocm_python3` script as highlighted by @YellowRoseCx.
