### ISSUE TITLE
HSA_STATUS_ERROR_OUT_OF_RESOURCES with num_gpus=4 in tensorflow/benchmarks

### ISSUE THREAD

**Issue by jamilbk** [ROCmSoftwarePlatform/tensorflow-upstream#250]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary (pip package)
- TensorFlow version (use command below): 1.12
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 4x Radeon Vega FE on Gigabyte X399 and TR1950x

Rocm lib versions:

```
rocm-clang-ocl/Ubuntu 16.04,now 0.3.0-7997136 amd64 [installed,automatic]
rocm-dev/Ubuntu 16.04,now 1.9.307 amd64 [installed,automatic]
rocm-device-libs/Ubuntu 16.04,now 0.0.1 amd64 [installed]
rocm-dkms/Ubuntu 16.04,now 1.9.307 amd64 [installed]
rocm-libs/Ubuntu 16.04,now 1.9.307 amd64 [installed]
rocm-opencl/Ubuntu 16.04,now 1.2.0-2018111340 amd64 [installed,automatic]
rocm-opencl-dev/Ubuntu 16.04,now 1.2.0-2018111340 amd64 [installed,automatic]
rocm-profiler/Ubuntu 16.04,now 5.4.6878 amd64 [installed]
rocm-smi/Ubuntu 16.04,now 1.0.0-72-gec1da05 amd64 [installed,automatic]
rocm-utils/Ubuntu 16.04,now 1.9.307 amd64 [installed,automatic]
rocminfo/Ubuntu 16.04,now 1.0.0 amd64 [installed,automatic]
```

**Describe the current behavior**
The tensorflow benchmark suite crashes with `HSA_STATUS_ERROR_OUT_OF_RESOURCES` when more than 1 GPU is used. This does not occur with one GPU. This is a new issue with tensorflow-rocm 1.12 and occurs regardless of the `batch_size` used.

**Describe the expected behavior**
I expect the benchmarks to complete successfully and, in an ideal world, achieve a speedup that scales (mostly) linearly with the number of GPUs used.

**Code to reproduce the issue**
```
$ git clone https://github.com/tensorflow/benchmarks
$ cd benchmarks/scripts/tf_cnn_benchmarks
$ gco cnn_tf_v1.12_compatible
$ python tf_cnn_benchmarks.py --num_gpus=4 --batch_size=1 --model=resnet50
```

**Other info / logs**

Here is the full output:

[output.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2605408/output.txt)

**Comment by jeffdaily** [comment]
This is a known "day 1" issue that required a work-around for mGPU training.  The issue regressed further in the ROCm 1.9.2 release (1.9.307).  The next ROCm 2.0 release addresses the root cause of this issue.

The work-around is to set sysctl vm.max_map_count to 250000.  On 8xGPU training this might need to be even greater, such as 1M.

To increase the max_map_count parameter
1. Add the following line to /etc/sysctl.conf:
vm.max_map_count=map_count
2. Reload the config as root:
`sysctl -p`
3. Check the new value:
`cat /proc/sys/vm/max_map_count`
