### ISSUE TITLE
tensorflow-rocm/2.14.0.602 is not found

### ISSUE THREAD

**Issue by adammer85** [ROCmSoftwarePlatform/tensorflow-upstream#2529]
**System information**
-  Linux Centos 8.3
- TensorFlow installed with pip
- TensorFlow version: 2.14.0

Hello,
I would like to use TF 2.14 with ROCm 6.0.2 and want to try out tensorflow-rocm/2.14.0.602. But I can not install this version of tensorflow-rocm. Should this version be already available?
Thank you.

**Comment by harkgill-amd** [comment]
Hi @adammer85, a 2.14.0.602 tensorflow-rocm wheel was never released. To utilize ROCm 6.0 with TF, please refer to the `2.14.0.600` wheel at https://pypi.org/project/tensorflow-rocm/2.14.0.600/. 

After the release of ROCm 6.1, the wheels are no longer hosted at pypi.org and can instead be found at repo.radeon.com. For example at https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/
