### ISSUE TITLE
cudnn PoolForward launch failed

### ISSUE THREAD

**Issue by ericjang** [ROCmSoftwarePlatform/tensorflow-upstream#254]
Steps to reproduce error:

1. Using AMD Vega Frontier Edition GPU.
2. Install dependencies for and run this notebook: https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/NSynth.ipynb
3, Encountered the following error:

```
InternalError (see above for traceback): cudnn PoolForward launch failed [[Node: ae_pool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 1, 512], padding="SAME", strides=[1, 1, 1, 512], _device="/job:localhost/replica:0/task:0/device:GPU:0"](ae_pool-0-TransposeNHWCToNCHW-LayoutOptimizer)]] [[Node: Reshape_373/_751 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1526_Reshape_373", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
On STDOUT, I see the following message:
```
MIOpen Error: /data/repo/MIOpen/src/ocl/pooling_ocl.cpp:97: Pooling window too large to do backwards
2018-11-27 05:41:18.309479: E tensorflow/stream_executor/rocm/rocm_dnn.cc:2985] failed to enqueue forward pooling on stream: miopenStatusUnknownError
```

When I set CUDA_VISIBLE_DEVICES='', it works just fine, and prints the following message:
```
INFO:tensorflow:Restoring parameters from /dance/test_data/wavenet-ckpt/model.ckpt-200000
CPU times: user 20.6 s, sys: 3.18 s, total: 23.7 s
Wall time: 5.81 s
```

Is there a missing op that hasn't been implemented?

**Comment by whchung** [comment]
/cc @daniellowell for awareness

@ericjang it seems to be a bug in `MIOpen`, could you help collect configs passed from TensorFlow to `MIOpen` with an environment variable `MIOPEN_ENABLE_LOGGING=1`?

**Comment by ericjang** [comment]
Thanks for the speedy reply. Attached are the requested logs.
[logs.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2621010/logs.txt)

**Comment by ericjang** [comment]
Hi, the problem seems to have disappeared once I upgraded to Ubuntu 18.04 and re-installed rocm-dkms along with the rocm/tensorflow docker image.
