### ISSUE TITLE
TF 2.15 support 

### ISSUE THREAD

**Issue by barlas** [ROCmSoftwarePlatform/tensorflow-upstream#2549]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15

### Custom code

Yes

### Current behavior?

There is none.

### Standalone code to reproduce the issue

```shell
There is no support for 2.15
```

**Comment by harkgill-amd** [comment]
Hi @barlas, Tensorflow 2.15 support exists both with ROCm 6.1.x and 6.2.x. You can find the wheels at 

https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1/tensorflow_rocm-2.15.0-cp39-cp319-manylinux2014_x86_64.whl
https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/tensorflow_rocm-2.15.1-cp39-cp39-manylinux_2_28_x86_64.whl

For more information, please refer to [Installing Tensorflow for ROCm](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html#installing-tensorflow-for-rocm).
