### ISSUE TITLE
Proper CMake Support

### ISSUE THREAD

**Issue by skn123** [ROCmSoftwarePlatform/tensorflow-upstream#271]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow-upstream
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
CMake for cross-platform build

**Will this change the current api? How?**
No changes

**Who will benefit with this feature?**
Everyone who do not want to use bazel builds

**Any Other info.**

GIven the fact that TF will be dropping contrib support from 2.0, it is expected that CMake support will also disappear.
https://groups.google.com/a/tensorflow.org/forum/#!topic/build/9vKi3ceP2ZI
Now, I was wondering if we can preempt this in the ROCm port of TF and future proof the codebase. I am willing to contribute to this effort and would like some placeholders to this effect. Given that there is an existing CMake project already available, I was wondering how can we add ROCm support in this? 
I will take up the responsibility of maintaining CMake support and am hopeful of others taking part in this.

**Comment by skn123** [comment]
@baerbock thanks. I suspect the output of a bazel configuration would be a Makefile. Is that correct? If so, we can pull out those details. We also have the base CPU-only CMake file in the contrib folder. What it lacks is specific #ifdefs for Rocm. Can you shed some light?

**Comment by sunway513** [comment]
@skn123 thanks for the heads up! Tensorflow-rocm project currently only supports Linux distros for AMD GPU; in the future, if we have plans expanding our coverage, we'll update on this ticket.
Will close this ticket, for now, many thanks for the willingness to improve tensorflow-rocm!
