### ISSUE TITLE
Packaging questions for nixos

### ISSUE THREAD

**Issue by Redhawk18** [ROCmSoftwarePlatform/tensorflow-upstream#2719]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

nightly

### Custom code

Yes

### OS platform and distribution

Nixos Linux

### GPU model and memory

5700xt

### Current behavior?

Nixos already has system wide support for rocm with a simple `nixpkgs.config.rocmSupport = true;`. This works great for many projects like ollama for example. However this core package that requires rocm does not have that support.

### Standalone code to reproduce the issue

Assuming I have a correctly packaged tensorflow, what would I have to add to this package to add rocm support? I know I'll need some of the env variables and the rocm packages themselves. But are there custom git patches or should I refer to this fork instead of the tensorflow master? There are many questions like these you won't find in the readme's.

**Comment by zichguan-amd** [comment]
Hi @Redhawk18, you need to either use prebuilt Docker images, use our official wheels provided here: https://repo.radeon.com/rocm/manylinux, or build from source using the ROCm-forked tensorflow (i.e. this repo). You can read more [here](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/tensorflow-install.html).
