### ISSUE TITLE
In which version did we start supporting the gemm_algorithm_picker=2 feature?

### ISSUE THREAD

**Issue by JoeNan1** [ROCmSoftwarePlatform/tensorflow-upstream#2758]
In which version was the gemm_algorithm_picker=2 feature implemented, and what are the specific effects on NVIDIA?
![image](https://github.com/user-attachments/assets/62a00a13-583b-44af-9eec-452b6efae3bf)

**Comment by JoeNan1** [comment]
@jayfurmanek

**Comment by taylding-amd** [comment]
Hi @JoeNan1, do you mind letting me know which commit you are on? The picture looks like a different directory structure than our TOT, I will be able to help by going to the code base once I get the right commit. For NVIDIA support, unfortunately, it  is specific to AMD's ROCm stack, and I believe it has no effect on NVIDIA GPUs.

**Comment by taylding-amd** [comment]
Hi, this issue will be closed now due to inactivity. Please feel free to reopen it or ask follow-up questions should further assistance be required. Thanks!
