### ISSUE TITLE
Hang on building tensorflow rccl packages

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#280]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch of this repo
- Python version: 3.5
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 1.19.2
- GCC/Compiler version (if compiling from source): gcc-5
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**

Hi, I am building the tensorflow-upstream source code inside ROCm docker image on a non-any-GPU machine, all ROCm libraries are installed inside the container such as rocBLAS, etc.

But when I build the tensorflow inside this container, the following building step hangs and is never going to pass:
```sh
[2,905 / 9,076] 96 actions, 9 running
    Linking external/nasm/nasm [for host]; 1599s local
    Linking external/protobuf_archive/python/google/protobuf/internal/_api_implementation.so [for host]; 1599s local
    Linking tensorflow/python/framework/fast_tensor_util.so [for host]; 1598s local
    Compiling external/rccl_archive/src/rcclTracker.cpp [for host]; 1598s local
    Compiling external/rccl_archive/src/rcclReduce.cpp [for host]; 1598s local
    Compiling external/rccl_archive/src/rcclAllReduce.cpp [for host]; 1598s local
    Compiling external/rccl_archive/src/rcclAllGather.cpp [for host]; 1598s local
    Compiling external/rccl_archive/src/rcclBcast.cpp [for host]; 1598s local ...
```

How to get over it?

**Comment by jeffdaily** [comment]
The other reason for the failure might be due to RCCL being installed as a deb package for ROCm 2.0.  The header files in /opt/rocm rccl package might conflict with the tarball that the TF build will download.  Please try `apt remove rccl` and try the TF build again.

**Comment by ghostplant** [comment]
I tried removing rccl but it doesn't work. Is there Dockerfile to build tensorflow-rocm from source.
Something like:

```sh
FROM rocm/tensorflow:rocm1.9.0-tf1.10-python3
ENV HIP_PLATFORM=hcc
RUN apt update && apt install -y zip unzip librdmacm-dev openjdk-8-jdk curl git vim-tiny less netcat-openbsd zlib1g-dev bash-completion g++ python3-setuptools python3-pip python3-wheel python3-numpy python3-dev rccl
RUN curl -Ls https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel_0.19.2-linux-x86_64.deb > bazel.deb && dpkg -i bazel.deb && rm bazel.deb
RUN git clone https://github.com/ROCmSoftwarePlatform/tensorflow-upstream
RUN cd tensorflow-upstream && ./build_rocm_python3
```

The Dockerfile above failed for /usr/local/bin/nvcc not found.
If I make a fake nvcc to wrap it to /opt/rocm/bin/hipcc, the building step just hangs as I described above.

**Comment by ghostplant** [comment]
@jeffdaily More solutions available?

**Comment by jeffdaily** [comment]
Your full docker file, I still see 'rccl' is apt installed?  Was that a typo or did you try removing it?

**Comment by ghostplant** [comment]
Yeah, I tried both but whether installing or not removing rccl package just doesn't make any difference.

**Comment by jeffdaily** [comment]
What version of rocm do you have installed?

**Comment by ghostplant** [comment]
rocm1.9.0 as I uses the image `rocm/tensorflow:rocm1.9.0-tf1.10-python3`

**Comment by jeffdaily** [comment]
The latest version of rocm tensorflow depends on rocm 2.0 features from miopen.  I started with your same image and got stuck compiling our rocm stream_executor sources.  Are you trying to build the latest TF tip or are you looking for the last TF release that worked prior to rocm 2.0?

**Comment by ghostplant** [comment]
If I use rocm-2.0 + tensorflow-upstream 1.12, there will be multiple other problem that fails earlier, like:

```sh
ERROR: /root/.cache/bazel/_bazel_root/28e90fc2296d53cdd9093e717cd499ea/external/rccl_archive/BUILD.bazel:10:1: error while parsing .d file: /root/.cache/bazel/_bazel_root/28e90fc2296d53cdd9093e717cd499ea/execroot/org_tensorflow/bazel-out/host/bin/external/rccl_archive/_objs/rccl/rcclReduce.pic.d (No such file or directory)
clang-8: error: language not recognized: 'cu'
clang-8: warning: /usr/bin/gcc: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: external/rccl_archive/src/rcclReduce.cpp: 'linker' input unused [-Wunused-command-line-argument]
clang-8: error: language not recognized: 'cu'
clang-8: warning: /usr/bin/gcc: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: external/rccl_archive/src/rcclReduce.cpp: 'linker' input unused [-Wunused-command-line-argument]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 24.000s, Critical Path: 2.22s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 230 processes: 230 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by ghostplant** [comment]
Another build problem is like this when I build tf-1.10 with rocm-1.9.0:

```sh
INFO: From Linking external/protobuf_archive/js_embed [for host]:
ld: cannot find -lcuda
ld: cannot find -lcudart
hcc: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: /root/.cache/bazel/_bazel_root/67778629e06e02d2e488bd3219d62efa/external/protobuf_archive/BUILD:260:1: output 'external/protobuf_archive/js_embed' was not created
ERROR: /root/.cache/bazel/_bazel_root/67778629e06e02d2e488bd3219d62efa/external/protobuf_archive/BUILD:260:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 17.351s, Critical Path: 9.62s
INFO: 1120 processes: 1120 local.
FAILED: Build did NOT complete successfully
```

**Comment by jeffdaily** [comment]
I have tried your same `rocm/tensorflow:rocm1.9.0-tf1.10-python3` on a system with ROCm 1.9.1 installed and I was not able to reproduce the failed build.

**Comment by jeffdaily** [comment]
Your build is behaving as if you did not `./configure` tensorflow to use ROCm.  Could you double-check the invocation of `./configure` to verify ROCm was enabled?

**Comment by sunway513** [comment]
Hi @ghostplant , the following commit in our release branch should help you with the issue:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/26942124fd818fcc3fb20621df6f415f6a40b5e7
Basically HIP currently check the system kernel modules to detect if the target build path is HCC or NVCC, with that, if your system has no supported AMD GPUs and kernel drivers enabled, HIPCC will try to compile as NVCC path. Therefore, it can cause the issue you've observed. 
To rebuild Tensorflow, I'd suggest you go with our public docker images that have all the proper dependencies installed:
rocm/tensorflow:rocm2.1-tf1.12-python3-dev

**Comment by ghostplant** [comment]
@sunway513 Thank you, I'll try that. BTW, if I want to add amdgpu-target=gfx902 before building the Tensorflow from source, where should I change the code to add this target?

**Comment by sunway513** [comment]
@ghostplant , there's a config file inside the docker image, edit that file if you want to add more GPU targets for your build:
/opt/rocm/bin/target.lst
The current content of the file:
```
/root# cat /opt/rocm/bin/target.lst
gfx803
gfx900
gfx906
```

**Comment by ghostplant** [comment]
Thanks!

**Comment by ghostplant** [comment]
@sunway513 I think I tried adding this patch before and it doesn't work:
```sh
RUN sed -i 's/^bazel build /bazel build --action_env=HIP_PLATFORM=hcc /g' tensorflow-upstream/build_rocm_python3
```

**Comment by sunway513** [comment]
@ghostplant , the tip of r1.12-rocm branch already has that workaround applied. 
Please try it with the recommended docker image with the dev environment.

**Comment by ghostplant** [comment]
I switch to a host environment with AMD GPUs and such issues no longer exists now. Thanks!
