### ISSUE TITLE
Provide Debian package

### ISSUE THREAD

**Issue by stephanlachnit** [ROCmSoftwarePlatform/tensorflow-upstream#283]
I want to as if you could to provide tensorflow-rocm as a Debian package in your repository. I know that there is a package available for pip, but a Debian package would have several advantages:

1. Update with apt
If there is an update for tensorflow-rocm, you can simply update it with all your other stuff via apt, no need to use pip. For example, I downloaded Numpy from the Debian repository, which is pretty neat. I would never update via pip as often as via apt.

2. Add dependencies
With Debian packages, you could add dependencies for rocm-libs, miopen-hip and cxlactivitylogger. If any of these dependencies change, you can simply change that info in the .deb file.

3. Easier installation for new users
Especially with added dependencies, its easier to install or update the package for new Linux users, because they don't need to handle pip or manual dependencies.

**Comment by sunway513** [comment]
Hi @stephanlachnit , tensorflow-rocm follows the upstream tensorflow installation support, details:
https://www.tensorflow.org/install/
There's no deb support from the upstream tensorflow, could you open the issue there for further discussions?
