### ISSUE TITLE
Question: will the radeon vii be optimized for fp16? Pls reply when You can. :) (i know it's not out yet)

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#288]
Question: will the radeon vii be optimized for fp16? Pls reply when You can. :) (i know it's not out yet)

**Comment by witeko** [comment]
@sunway513 , @dagamayank , cmon guys, typing in 2-3 letters takes less than 8 days.

**Comment by pricebenjamin** [comment]
While it's not an official response, I asked another community member if they could post some numbers for their Radeon VII in the performance comparison thread.

**Comment by witeko** [comment]
@pricebenjamin ty :)

**Comment by sebpuetz** [comment]
I posted some results over at #173 
If you want some specific benchmark, feel free to ask. I can run them after the weekend

**Comment by witeko** [comment]
@sebpuetz thx, looks good. Can You also run "  rocminfo | grep 'Fast F16 Operation'  "? :)

**Comment by sebpuetz** [comment]
I posted the output of rocminfo over at #316. Value is True for Fast F16  Operation

**Comment by witeko** [comment]
@sebpuetz I think the value is FALSE - based on #316 :
Agent 2                  
*******                  
  Name:                    gfx906                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26287                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1802                               
  BDFID:                   10240                              
  Compute Unit:            60                                 
  Features:                KERNEL_DISPATCH 
  **Fast F16 Operation:      FALSE**

**Comment by sebpuetz** [comment]
Well, sorry about that, I'm on mobile. I was looking at the output further down (ISA agent) that states Fast F16 True.

**Comment by witeko** [comment]
@sebpuetz thx anyway :), its seems that even thought it says FALSE the speed increase is there.
