### ISSUE TITLE
Why does your install tell people to delete  /var/lib/apt/lists/* ?

### ISSUE THREAD

**Issue by emerth** [ROCmSoftwarePlatform/tensorflow-upstream#307]
For Python2

> sudo apt-get update && sudo apt-get install -y \
>     python-numpy \
>     python-dev \
>     python-wheel \
>     python-mock \
>     python-future \
>     python-pip \
>     python-yaml \
>     python-setuptools && \
>     sudo apt-get clean && \
>     sudo rm -rf /var/lib/apt/lists/*

Similar for Python3.

There is no reason to delete the contents of /var/lib/apt/lists/.

**Comment by sunway513** [comment]
Hi @emerth , thanks for reporting the issue!
Those steps were inherited from our Dockerfiles. For docker image preparations, this step is important to reduce the final image size. However, I agree with you that for bare metal setup this step is not necessary.
Will submit a PR to remove this recommendation.

**Comment by sunway513** [comment]
Hi @emerth , I've updated the doc, thanks for reporting.

**Comment by emerth** [comment]
Thanks Peng!
