### ISSUE TITLE
Installing tensorflow-rocm with pip / Python 3.7 installs an empty package

### ISSUE THREAD

**Issue by CyberShadow** [ROCmSoftwarePlatform/tensorflow-upstream#308]
Using Python 3.7, the command:

```console
$ pip3 install --user tensorflow-rocm
```

attempts to download and install the following file:

https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none-any.whl

which contains an empty package (only an `__init__.py` with only a `name = "tensorflow-rocm"` line).

Importing tensorflow thus "works", but everything else fails.

Using `pip2` instead of `pip3` as a workaround works on systems with Python 2.7 / 3.7.

**Comment by sunway513** [comment]
@CyberShadow We currently support python2.7, python3.5 and python3.6 for pip installation, those whl packages can be found here:
https://pypi.org/project/tensorflow-rocm/#files
Besides, the upstream tensorflow package doesn't support python3.7 yet:
https://pypi.org/project/tensorflow/#files
We'll keep our eyes open to follow the upstream tensoflow progress on pypl packages distributions, thanks for reporting!

**Comment by CyberShadow** [comment]
All of this makes sense, but shouldn't there be an explicit error instead of installing an empty package?

Compare the result of installing tensorflow and tensorflow-rocm with Python 3.7:

```console
$ env -i HOME=$PWD pip3 install --user tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

$ env -i HOME=$PWD pip3 install --user tensorflow-rocm
Collecting tensorflow-rocm
  Downloading https://files.pythonhosted.org/packages/d6/b5/f14d48711d276f2391c944ecda0bc94bc44c0c168ac0a0208bb730886fe8/tensorflow_rocm-0.0.1-py3-none
Installing collected packages: tensorflow-rocm
Successfully installed tensorflow-rocm-0.0.1
```

The last one installs an empty package instead of an error like the first one.

**Comment by sunway513** [comment]
Hi @CyberShadow , thanks, we have removed the tensorflow-rocm-0.0.1 package on pypl, please try again and see if the issue remains.

**Comment by CyberShadow** [comment]
Looks fixed, thanks!
