### ISSUE TITLE
Error "Missing metadata for __global__ function"

### ISSUE THREAD

**Issue by doody1986** [ROCmSoftwarePlatform/tensorflow-upstream#319]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
CPU: Intel(R) Xeon(R) CPU E5-2630
GPU: AMD R9 Nano

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A

- TensorFlow installed from (source or binary):
Source

- TensorFlow version (use command below):
From branch r1.12-rocm

- Python version:
2.7.15

- Bazel version (if compiling from source):
0.15.0

- GCC/Compiler version (if compiling from source):
7.3.0

- CUDA/cuDNN version:
N/A

- GPU model and memory:
GPU: AMD R9 Nano

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When training with CIFAR10 data with the script provided by tensorflow, one error occurred as below: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _ZN10tensorflow7functor17BlockReduceKernelIN7rocprim18transform_iteratorIPfNS_10squareHalfIfEEfEES4_Li256EN6hipcub3SumEEEvT_T0_iT2_NSt15iterator_traitsISA_E10value_typeE

**Describe the expected behavior**
The training works properly.

**Code to reproduce the issue**
The script I was using is exactly the same from the one in there https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_train.py

**Other info / logs**
(Note that only part of the traces are provided)
2019-02-13 18:18:16.501110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1057]      0 1 
2019-02-13 18:18:16.501117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 0:   N N 
2019-02-13 18:18:16.501123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 1:   N N 
2019-02-13 18:18:16.501171: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:82:00.0)
2019-02-13 18:18:16.523874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 3540 MB memory) -> physical GPU (device: 1, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:83:00.0)
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _ZN10tensorflow7functor17BlockReduceKernelIN7rocprim18transform_iteratorIPfNS_10squareHalfIfEEfEES4_Li256EN6hipcub3SumEEEvT_T0_iT2_NSt15iterator_traitsISA_E10value_typeE
terminate called recursively
Aborted (core dumped)

**Comment by pricebenjamin** [comment]
This looks very similar to #316, and is being [actively worked on](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/316#issuecomment-463347028). If possible, I'd suggest installing `tensorflow-rocm` via pip for the time being.

**Comment by doody1986** [comment]
@pricebenjamin 
Thanks a lot!

**Comment by whchung** [comment]
Thanks for @pricebenjamin . It's the same issue with #316.

**Comment by whchung** [comment]
A branch in HIP ( https://github.com/ROCm-Developer-Tools/HIP/tree/feature_maybe_dlopen ) has been developed to fix this issue, and is under extensive testing. If everything goes well it would be released on ROCm 2.3 in March. For the moment please using `tensorflow-rocm` via pip.

**Comment by doody1986** [comment]
@whchung 
Thanks a lot for the info!

**Comment by whchung** [comment]
Also it's possible to get around the issue for now if you indeed need to build TensorFlow from source: downgrade to ROCm 2.0, especially for user-level components:

There are some docker container tags you can pick from at:
https://hub.docker.com/r/rocm/tensorflow/tags

**Comment by whchung** [comment]
@doody1986 I'm closing this ticket hereby.

**Comment by wormwang** [comment]
Did the master branch included code of  feature_maybe_dlopen branch. When release tag roc-2.3? for this issue? That is big obstacle for TF :-(

**Comment by typedrat** [comment]
I'm getting this error when I try to do anything with Tensorflow using a `pip` install of `tensorflow-rocm` or using the Docker container.

I'm running Ubuntu 18.04.4 and ROCm 3.3 on a Ryzen R7 2700X with a Radeon RX 5700XT.

**Comment by BloodBlight** [comment]
Same here!  Totally new to this, trying to call tf.keras.metrics.Mean or tf.keras.metrics.SparseCategoricalAccuracy ends in this error.

Mint 19.3
ROCm 3.3
tensorflow-rocm 2.1.1
On a Ryzen 3900X with a Radeon RX 5700XT

@typedrat Have you had any luck?

**Comment by BloodBlight** [comment]
@hatamiarash7 and @leoschneider Seems like it is a GFX10 compatibility issue up stream.  :(

See:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/967#issuecomment-630261097
