### ISSUE TITLE
bazel compile for TF1.12-GPU fails on AMD TR with latest ROCM 

### ISSUE THREAD

**Issue by RogerWeihrauch** [ROCmSoftwarePlatform/tensorflow-upstream#324]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

WITH REF TO ALREADY CLOSED: #304: I tried suggestions there, but with no success
I am trying to build TF on my own from sources and I am stuck always a the same point:
hint on build not suvccessful at: 

C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1): crosstool_wrapper_driver_rocm failed

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Debian 9.7 with latest updates from backports repo

debian@StretcH:/etc$ less os-release:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): FROM SOURCE

- TensorFlow version:
debian@StretcH:~/TensorFlow/tensorflow$ less RELEASE.md 
# Release 1.12.0
## Major Features and Improvements

- Python version:
debian@StretcH:~$ python -V
Python 2.7.13

- Installed using virtualenv? pip? conda?: PIP

- Bazel version (if compiling from source):debian@StretcH:~/TensorFlow/tensorflow$ bazel version
INFO: Invocation ID: e8b92533-7388-4712-8012-78303b25dc3f
Build label: 0.22.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:58:08 2019 (1548680288)
Build timestamp: 1548680288
Build timestamp as int: 1548680288
debian@StretcH:~/TensorFlow/tensorflow$ 

- GCC/Compiler version (if compiling from source):
debian@StretcH:~/TensorFlow/tensorflow$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
debian@StretcH:~/TensorFlow/tensorflow$ 

- ROCm/MIOpen version:
debian@StretcH:~/TensorFlow/tensorflow$ rocminfo 
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen Threadripper 1900X 8-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB                            
  Chip ID:                 0                                  
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):3900                               
  BDFID:                   0                                  
  Compute Unit:            8                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65877168KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65877168KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    AMD Ryzen Threadripper 1900X 8-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB                            
  Chip ID:                 0                                  
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):3900                               
  BDFID:                   0                                  
  Compute Unit:            8                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    66026832KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    66026832KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 3                  
*******                  
  Name:                    gfx803                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26591                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1365                               
  BDFID:                   16640                              
  Compute Unit:            36                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64                                 
  Workgroup Max Size:      1024                               
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888                           
    Dim[1]:                  1090520064                         
    Dim[2]:                  0                                  
  Grid Max Size:           4294967295                         
  Waves Per CU:            40                                 
  Max Work-item Per CU:    2560                               
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295                         
    Dim[1]:                  4294967295                         
    Dim[2]:                  4294967295                         
  Max number Of fbarriers Per Workgroup:32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64KB                               
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Dimension: 
        Dim[0]:                  67109888                           
        Dim[1]:                  1024                               
        Dim[2]:                  16777217                           
      Workgroup Max Size:      1024                               
      Grid Max Dimension:      
        x                        4294967295                         
        y                        4294967295                         
        z                        4294967295                         
      Grid Max Size:           4294967295                         
      FBarrier Max Size:       32                                 
*** Done ***             
debian@StretcH:~/TensorFlow/tensorflow$ 

- GPU model and memory: AMD RADEON RX580
debian@StretcH:~/TensorFlow/tensorflow$ rocm-smi 

========================        ROCm System Management Interface        ========================
================================================================================================
GPU   Temp   AvgPwr   SCLK    MCLK    PCLK           Fan     Perf    PwrCap   SCLK OD   MCLK OD  GPU%
0     N/A    N/A      N/A     N/A     N/A            0%      N/A     N/A      N/A       N/A      N/A      
1     N/A    N/A      N/A     N/A     N/A            0%      N/A     N/A      N/A       N/A      N/A      
2     58.0c  36.008W  900Mhz  2000Mhz 8.0GT/s, x16   31.76%  auto    145.0W   0%        0%       0%       
================================================================================================
========================               End of ROCm SMI Log              ========================
debian@StretcH:~/TensorFlow/tensorflow$ 

**Describe the problem**

I do not get TF compiled from sources successfully, since rocm and the TF-Docker image are running perfectly after successful installation

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When executing (after doing a 'bazel clean'):

debian@StretcH:~/TensorFlow/tensorflow$ bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures   ,

I get these error messages:

INFO: Found 1 target...
ERROR: /home/debian/.cache/bazel/_bazel_debian/798b0a4f94570ae27e79c05337954cd9/external/mkl_dnn/BUILD.bazel:71:1: C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /home/debian/.cache/bazel/_bazel_debian/798b0a4f94570ae27e79c05337954cd9/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/debian/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/rocm/bin:/home/linuxbrew/.linuxbrew/bin:/home/debian/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_DOWNLOAD_CLANG=1 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=1 \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/memory_desc_wrapper.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/memory_desc_wrapper.pic.o' -fPIC -iquote external/mkl_dnn -iquote bazel-out/k8-opt/genfiles/external/mkl_dnn -iquote bazel-out/k8-opt/bin/external/mkl_dnn -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/include -isystem bazel-out/k8-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/common -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/xbyak '--config=monolithic' -fexceptions '-DMKLDNN_THR=MKLDNN_THR_SEQ' -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c external/mkl_dnn/src/common/memory_desc_wrapper.cpp -o bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/memory_desc_wrapper.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
gcc: error: unrecognized command line option '--config=monolithic'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 12.073s, Critical Path: 2.16s
INFO: 356 processes: 356 local.
FAILED: Build did NOT complete successfully

**Any other info / logs**
I do not know if this is of any relevance, but all 'action_outs' files have a size of 0 bytes:
debian@StretcH:~/TensorFlow/tensorflow/bazel-out/_tmp/action_outs$ ll
[action_outs.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2871736/action_outs.txt); I have not files in bazel-testlogs.

Thank you all for your hints,help,support.

Regards,
Roger

**Comment by sunway513** [comment]
Hi @RogerWeihrauch, Debian9.7 is not in our official support list, please consult with the following doc:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available

Since rocm/tensorflow docker image could work correctly on your setup, if you need to build from source, I would suggest using the following base docker:
rocm/tensorflow:rocm2.1-tf1.12-python3-dev
In the above base docker image, all the dependency required to build tensorflow-rocm from source has been properly configured.

**Comment by sunway513** [comment]
Close the issue for now, please let me know if you still see build error using rocm/tensorflow:rocm2.1-tf1.12-python3-dev base docker image.
