### ISSUE TITLE
installing package not working

### ISSUE THREAD

**Issue by Six-wars** [ROCmSoftwarePlatform/tensorflow-upstream#328]
I think there's a chance you need to app ppa for this packages since when I try to install them I get package not found.

I'm on ubuntu 18.04

    sam@sam:~$ sudo apt update
    Hit:1 http://ke.archive.ubuntu.com/ubuntu bionic InRelease
    Hit:2 http://ke.archive.ubuntu.com/ubuntu bionic-updates InRelease                                 
    Hit:3 http://ke.archive.ubuntu.com/ubuntu bionic-backports InRelease                               
    Hit:4 http://ppa.launchpad.net/clipgrab-team/ppa/ubuntu bionic InRelease                           
    Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                        
    Hit:6 http://ppa.launchpad.net/deluge-team/ppa/ubuntu bionic InRelease                             
    Hit:7 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu bionic InRelease                      
    Hit:8 https://packages.microsoft.com/repos/vscode stable InRelease                                 
    Hit:9 http://ppa.launchpad.net/ubuntu-desktop/ubuntu-make/ubuntu bionic InRelease                  
    Get:10 https://dist.crystal-lang.org/apt crystal InRelease [2,496 B]     
    Err:10 https://dist.crystal-lang.org/apt crystal InRelease
    The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 09617FD37CC06B54
    Reading package lists... Done 
    W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: GPG error: https://dist.crystal-lang.org/apt crystal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 09617FD37CC06B54
    E: The repository 'https://dist.crystal-lang.org/apt crystal InRelease' is not signed.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
    sam@sam:~$ sudo apt install rocm-libs miopen-hip cxlactivitylogger
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package rocm-libs
    E: Unable to locate package miopen-hip
    E: Unable to locate package cxlactivitylogger
    sam@sam:~$ sudo apt install rocm-dkms
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package rocm-dkms

**Comment by sunway513** [comment]
Hi @Six-wars , yes, you'll need to configure debian repository for ROCm before trying to install. 
Could you follow the instructions in the following doc?
https://github.com/RadeonOpenCompute/ROCm#add-the-rocm-apt-repository

**Comment by sunway513** [comment]
Closing the ticket for now, @Six-wars please let us know if you still have build issues.
