### ISSUE TITLE
Prebuilt tf-rocm for python3.6 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#336]
Current tf-rocm docker images are built with Ubuntu16.04 + python3.5 which is not compatible with python3.6 runtime.

If I build tf-rocm myself on Ubuntu 18.04, it crashes with unknown bugs from bazel/gcc, so how can I get a prebuilt tf-rocm version based on python3.6 runtime?

**Comment by sunway513** [comment]
Hi @ghostplant , in fact we've been publishing whl packages for python3.6 in pypi, the following is the latest  python3.6 package for TF-1.13 release:
https://files.pythonhosted.org/packages/e7/84/2c26bca9ea97a089f8c655564f8815dc6e059096f783552532851051417b/tensorflow_rocm-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
Can you try that out? 

I'm closing the issue for now, please reopen it if you have further questions.

**Comment by ghostplant** [comment]
@sunway513 Thanks, I'll try that. Another question related to compiling tensorflow-rocm from source.
I update `/opt/rocm/bin/target.lst` to include necessary `gfxNNN` architecture per line, but it just doesn't take effect. The target tensorflow-upstream wheel output will only include the architecture corresponding with the local detected GPU architecture. What is the problem?

**Comment by sunway513** [comment]
Hi @ghostplant , our CI system has been using the "target.lst" approach, it has been working correctly.
You might try to clean the TF build cache and build again:
`bazel clean --expunge` 
If you still have issues, please pull our base dev docker image and try inside there:
rocm/tensorflow:rocm2.1-tf1.13-python3-dev
