### ISSUE TITLE
Tensorflow missing GLIBCXX_3.4.21 on Centos 7 with kernel 3.10

### ISSUE THREAD

**Issue by amirjaber** [ROCmSoftwarePlatform/tensorflow-upstream#348]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
 binary
- TensorFlow version:
 1.13 and 1.12
- Python version:
3.6
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
0.15
- GCC/Compiler version (if compiling from source):
gcc (GCC) 4.8.5
- ROCm/MIOpen version:
2
- GPU model and memory:
Frontier vega and MI25

**Describe the problem**

I installed Rocm 2.0 on CentOS 7 with kernel 3.10 which passed the tests in rocm installation wiki, then installed the binary of Tensorflow 1.13 and 1.12 using pip but when importing Tensorflow in python3.6 it is missing several libraries as below. I tried to build Tensorflow from source but it requires Bazel 0.19 while Centos 7 Bazel is 0.15. I could not find rpm binary for it and my yum command could not resolve dependencies for bazel-0.19.0-1.el7.src.rpm while building. I can install every dependency one by one with rpm but stoped at this stage to see if someone had fixed this issue before. 

**Any other info / logs**
ldd ~/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so)
/home/amir/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so)
	linux-vdso.so.1 =>  (0x00007ffe56a92000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f579740f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f579710d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5796ef1000)
	libhc_am.so => /opt/rocm/hcc/bin/../lib/libhc_am.so (0x00007f5796c8f000)
	libhip_hcc.so => /opt/rocm/lib/libhip_hcc.so (0x00007f5796317000)
	libhsa-runtime64.so.1 => /opt/rocm/hsa/lib/libhsa-runtime64.so.1 (0x00007f579604c000)
	libCXLActivityLogger.so => /opt/rocm/lib/libCXLActivityLogger.so (0x00007f5795dfd000)
	libtensorflow_framework.so => /home/amir/.local/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (0x00007f57949c0000)
	libhiprand.so.1 => /opt/rocm/hiprand/lib/libhiprand.so.1 (0x00007f579477f000)
	librocfft.so.0 => /opt/rocm/lib/librocfft.so.0 (0x00007f57944b4000)
	librocblas.so.0 => /opt/rocm/lib/librocblas.so.0 (0x00007f579140a000)
	libMIOpen.so.1 => /opt/rocm/lib/libMIOpen.so.1 (0x00007f57909d9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f57907d1000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f57904ca000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f57902b4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f578fee7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f57a896f000)
	libmcwamp.so => /opt/rocm/hcc/bin/../lib/libmcwamp.so (0x00007f578fcce000)
	libhsakmt.so.1 => /opt/rocm/lib64/libhsakmt.so.1 (0x00007f578faaa000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f578f894000)
	librocrand.so.1 => /opt/rocm/rocrand/lib/librocrand.so.1 (0x00007f578f247000)
	librocfft-device.so.0 => /opt/rocm/bin/../lib/librocfft-device.so.0 (0x00007f57871bd000)
	libmiopengemm.so => /opt/rocm/bin/../lib/libmiopengemm.so (0x00007f57862cf000)
	libamdocl64.so => /opt/rocm/opencl/lib/x86_64/libamdocl64.so (0x00007f578200c000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f5781e00000)
	libpci.so.3 => /lib64/libpci.so.3 (0x00007f5781bf3000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f57819da000)

**Comment by sunway513** [comment]
Hi @amirjaber , for CentOS we provide docker based solutions.
Here are the steps to enable install docker-ce on centos:
```
sudo yum install -y epel-release
sudo yum -y remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine
sudo yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce
sudo systemctl start docker
sudo systemctl enable docker
sudo docker run hello-world
```
Steps to launch the tensorflow-rocm docker image on centos:
```
alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME/dockerx:/dockerx -v /data/imagenet/tf:/imagenet'
drun rocm/tensorflow:rocm2.1-tf1.13-centos-dev
```

**Comment by amirjaber** [comment]
I appreciate it. Is there any performance loss using the docker vs OS installation. I want to do several benchmarkings and also test FP16 on Vega Frontier and MI25 cards.

**Comment by sunway513** [comment]
Hi @amirjaber , there won't be performance loss for single-node by using docker solution. 
Please let me know if you have further questions :-)

**Comment by amirjaber** [comment]
Thanks @sunway513 I have several cards but all in one machine. Do I get any benefit moving to Ubuntu 18.04? Can you also inform me about possibility of FP16 on MI25 cards?

**Comment by sunway513** [comment]
Hi @amirjaber , we have full support on Ubuntu18.04; and yes, it'll be easier to configure the environments and dependencies on Ubuntu. 
TF FP16 benchmark should work correctly on MI25 boards. Please let us know if you see issues there.

**Comment by amirjaber** [comment]
I ran benchmarks in a Centos7 docker container: rocm/tensorflow:rocm2.1-tf1.13-centos-dev with a MI25 card but received inferior results than others. By adding FP16 it goes even worse consistently.

TF_ROCM_FUSION_ENABLE=1 python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=128 --model=resnet50

Step	Img/sec	total_loss
1	images/sec: 210.7 +/- 0.0 (jitter = 0.0)	8.221
10	images/sec: 209.5 +/- 0.6 (jitter = 0.9)	8.285
20	images/sec: 209.1 +/- 0.5 (jitter = 1.2)	8.061
30	images/sec: 208.9 +/- 0.4 (jitter = 1.3)	8.312
40	images/sec: 208.1 +/- 0.7 (jitter = 1.1)	8.178
50	images/sec: 208.3 +/- 0.6 (jitter = 1.1)	8.243
60	images/sec: 208.3 +/- 0.5 (jitter = 1.1)	8.186
70	images/sec: 208.2 +/- 0.5 (jitter = 1.2)	8.156
80	images/sec: 207.9 +/- 0.4 (jitter = 1.5)	8.143
90	images/sec: 207.4 +/- 0.4 (jitter = 2.0)	8.215
100	images/sec: 206.7 +/- 0.4 (jitter = 2.7)	8.155

total images/sec: 206.62

TF_ROCM_FUSION_ENABLE=1 python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=128 --model=resnet50 --use_fp16

Step Img/sec	total_loss
1	images/sec: 193.8 +/- 0.0 (jitter = 0.0)	8.209
10	images/sec: 192.0 +/- 0.6 (jitter = 1.0)	8.183
20	images/sec: 191.8 +/- 0.5 (jitter = 0.8)	8.318
30	images/sec: 191.5 +/- 0.4 (jitter = 1.1)	8.197
40	images/sec: 191.4 +/- 0.4 (jitter = 0.9)	8.150
50	images/sec: 191.3 +/- 0.4 (jitter = 1.1)	8.391
60	images/sec: 191.0 +/- 0.4 (jitter = 1.3)	8.272
70	images/sec: 190.9 +/- 0.4 (jitter = 1.3)	8.148
80	images/sec: 190.7 +/- 0.4 (jitter = 1.2)	8.290
90	images/sec: 190.7 +/- 0.4 (jitter = 1.2)	8.330
100	images/sec: 190.8 +/- 0.3 (jitter = 1.0)	8.210

total images/sec: 190.71

**Comment by sunway513** [comment]
Hi @amirjaber , could you review the comments on the following issue:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/256
