### ISSUE TITLE
build_rocm_python3 failed

### ISSUE THREAD

**Issue by Hycdog** [ROCmSoftwarePlatform/tensorflow-upstream#356]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Fedora 29 on kernel 4.20.14
- TensorFlow version: 1.13.0 rc2
- Python version: 3.7.2
- Bazel version (if compiling from source):0.21.0
- GCC/Compiler version (if compiling from source):8.2.1
- ROCm/MIOpen version:2.1.0
- GPU model and memory:Vega 56

**Describe the problem**
![IMG_0119](https://user-images.githubusercontent.com/31446768/54469737-26712200-47d7-11e9-9361-dbdcd8b3c40d.JPG)
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[root@localhost tensorflow-upstream-merge-190225]# ./build_rocm_python3 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: be8003bd-1977-43e7-a7be-c50127c067b5
You have bazel 0.21.0 installed.
Found possible Python library paths:
  /usr/local/lib/python3.7/site-packages
  /usr/lib/python3.7/site-packages
  /usr/local/lib64/python3.7/site-packages
  /usr/lib64/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.7/site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]: No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
Skipping tensorflow as it is not installed.
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 89a83c60-a9e9-4776-a19e-ab49a44a49d6
DEBUG: /root/.cache/bazel/_bazel_root/54f4232353e20708c14820982fe7fe38/external/build_bazel_rules_apple/apple/repositories.bzl:35:5: 
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/python/BUILD:3225:1: in py_library rule //tensorflow/python:standard_ops: target '//tensorflow/python:standard_ops' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/python/BUILD:100:1: in py_library rule //tensorflow/python:no_contrib: target '//tensorflow/python:no_contrib' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/contrib/metrics/BUILD:16:1: in py_library rule //tensorflow/contrib/metrics:metrics_py: target '//tensorflow/contrib/metrics:metrics_py' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/contrib/bayesflow/BUILD:17:1: in py_library rule //tensorflow/contrib/bayesflow:bayesflow_py: target '//tensorflow/contrib/bayesflow:bayesflow_py' depends on deprecated target '//tensorflow/contrib/distributions:distributions_py': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/contrib/BUILD:14:1: in py_library rule //tensorflow/contrib:contrib_py: target '//tensorflow/contrib:contrib_py' depends on deprecated target '//tensorflow/contrib/distributions:distributions_py': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (381 packages loaded, 19363 targets configured).
INFO: Found 1 target...
ERROR: /home/hu/Downloads/tensorflow-upstream-merge-190225/tensorflow/stream_executor/BUILD:682:1: C++ compilation of rule '//tensorflow/stream_executor:rocm_platform' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/54f4232353e20708c14820982fe7fe38/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_driver.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_driver.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -iquote . -iquote bazel-out/host/genfiles -iquote bazel-out/host/bin -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote bazel-out/host/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote bazel-out/host/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote bazel-out/host/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote bazel-out/host/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote bazel-out/host/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote bazel-out/host/bin/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/host/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote bazel-out/host/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote bazel-out/host/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote bazel-out/host/bin/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/host/genfiles/external/local_config_cuda -iquote bazel-out/host/bin/external/local_config_cuda -iquote external/local_config_rocm -iquote bazel-out/host/genfiles/external/local_config_rocm -iquote bazel-out/host/bin/external/local_config_rocm -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem bazel-out/host/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda -isystem bazel-out/host/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/crt -isystem external/local_config_rocm/rocm -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm -isystem bazel-out/host/bin/external/local_config_rocm/rocm -isystem external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include -isystem external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocrand -g0 '-march=native' -g0 -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c tensorflow/stream_executor/rocm/rocm_driver.cc -o bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_driver.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/stream_executor/rocm/rocm_driver.cc: In static member function 'static bool stream_executor::gpu::GpuDriver::SynchronousMemsetUint32(stream_executor::gpu::GpuContext*, hipDeviceptr_t, tensorflow::uint32, size_t)':
tensorflow/stream_executor/rocm/rocm_driver.cc:490:20: error: 'hipMemsetD32' was not declared in this scope
   hipError_t res = hipMemsetD32(pointer, value, uint32_count);
                    ^~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc:490:20: note: suggested alternative: 'hipMemset3D'
   hipError_t res = hipMemsetD32(pointer, value, uint32_count);
                    ^~~~~~~~~~~~
                    hipMemset3D
tensorflow/stream_executor/rocm/rocm_driver.cc: In static member function 'static bool stream_executor::gpu::GpuDriver::AsynchronousMemsetUint32(stream_executor::gpu::GpuContext*, hipDeviceptr_t, tensorflow::uint32, size_t, stream_executor::gpu::GpuStreamHandle)':
tensorflow/stream_executor/rocm/rocm_driver.cc:520:20: error: 'hipMemsetD32Async' was not declared in this scope
   hipError_t res = hipMemsetD32Async(pointer, value, uint32_count, stream);
                    ^~~~~~~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc:520:20: note: suggested alternative: 'hipMemset3DAsync'
   hipError_t res = hipMemsetD32Async(pointer, value, uint32_count, stream);
                    ^~~~~~~~~~~~~~~~~
                    hipMemset3DAsync
tensorflow/stream_executor/rocm/rocm_driver.cc: In function 'std::__cxx11::string stream_executor::gpu::MemorySpaceString(stream_executor::gpu::MemorySpace)':
tensorflow/stream_executor/rocm/rocm_driver.cc:119:21: warning: control reaches end of non-void function [-Wreturn-type]
       LOG(FATAL) << "impossible memory space";
                     ^~~~~~~~~~~~~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 17.626s, Critical Path: 4.90s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully

**Comment by Hycdog** [comment]
I was able to run rocm-tf docker and passed all the test scripts, 
but when tried to build rocm-tf the errors occured. 
Could you guys probably give me a hint on what's the possible problem?Thx

**Comment by sunway513** [comment]
Hi @Hycdog , please pull our release branches to build from source:
`git clone -b r1.13-rocm https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git tensorflow`
The current develop-upstream branch requires customized ROCm toolchains to build, which will be in place by ROCm2.3. 

In addition, we provide dev docker images that has configured all the required dependancies, you can use that as your base docker:
`sudo docker pull rocm/tensorflow:rocm2.2-tf1.13-python3-dev`

**Comment by sunway513** [comment]
Close this issue for now. @Hycdog please feel free to re-open this issue if you have further questions.
