### ISSUE TITLE
Error compiling r2.0 branch

### ISSUE THREAD

**Issue by hwchong** [ROCmSoftwarePlatform/tensorflow-upstream#357]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.0
- Python version:3.6.7
- Installed using virtualenv? pip? conda?:Source on docker
- Bazel version (if compiling from source):0.19.2
- GCC/Compiler version (if compiling from source): clang version 6.0.0-1ubuntu2 
- ROCm/MIOpen version: 2.2.31
- GPU model and memory: Vega 56 8GB

**Describe the problem**

I am trying to compile Tensorflow 2.0 from the r2.0-rocm branch and am running into the error message attached below. Is the r2.0 buildable? Can we run TF2.0 alpha on ROCM?

`ERROR: /root/tensorflow-upstream/tensorflow/stream_executor/rocm/BUILD:73:1: C++ compilation of rule '//tensorflow/stream_executor/rocm:rocm_driver' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/stream_executor/rocm/_objs/rocm_driver/rocm_driver.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/stream_executor/rocm/_objs/rocm_driver/rocm_driver.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -iquote . -iquote bazel-out/host/genfiles -iquote bazel-out/host/bin -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote bazel-out/host/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote bazel-out/host/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote bazel-out/host/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote bazel-out/host/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote bazel-out/host/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote bazel-out/host/bin/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/host/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote bazel-out/host/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote bazel-out/host/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote bazel-out/host/bin/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/local_config_rocm -iquote bazel-out/host/genfiles/external/local_config_rocm -iquote bazel-out/host/bin/external/local_config_rocm -iquote external/local_config_cuda -iquote bazel-out/host/genfiles/external/local_config_cuda -iquote bazel-out/host/bin/external/local_config_cuda -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem bazel-out/host/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_rocm/rocm -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm -isystem bazel-out/host/bin/external/local_config_rocm/rocm -isystem external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include -isystem external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocrand -isystem external/local_config_cuda/cuda -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda -isystem bazel-out/host/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/crt -g0 '-march=native' -g0 -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c tensorflow/stream_executor/rocm/rocm_driver.cc -o bazel-out/host/bin/tensorflow/stream_executor/rocm/_objs/rocm_driver/rocm_driver.pic.o)
In file included from tensorflow/stream_executor/rocm/rocm_driver.cc:29:0:
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h: In function 'decltype (hipHostMalloc(args ...)) tensorflow::wrap::hipHostMalloc(Args ...)':
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:51:63: error: decltype cannot resolve address of overloaded function
     using FuncPtrT = std::add_pointer<decltype(::hipSymbolName)>::type;     \
                                                               ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:92:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipHostMalloc)                            \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:51:64: error: template argument 1 is invalid
     using FuncPtrT = std::add_pointer<decltype(::hipSymbolName)>::type;     \
                                                                ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:92:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipHostMalloc)                            \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:52:12: error: 'FuncPtrT' does not name a type
     static FuncPtrT loaded = []() -> FuncPtrT {                             \
            ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:92:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipHostMalloc)                            \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:62:7: error: expected primary-expression before ')' token
     }();                                                                    \
       ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:92:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipHostMalloc)                            \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h: In function 'decltype (hipMalloc(args ...)) tensorflow::wrap::hipMalloc(Args ...)':
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:51:63: error: decltype cannot resolve address of overloaded function
     using FuncPtrT = std::add_pointer<decltype(::hipSymbolName)>::type;     \
                                                               ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:96:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipMalloc)                                \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:51:64: error: template argument 1 is invalid
     using FuncPtrT = std::add_pointer<decltype(::hipSymbolName)>::type;     \
                                                                ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:96:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipMalloc)                                \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:52:12: error: 'FuncPtrT' does not name a type
     static FuncPtrT loaded = []() -> FuncPtrT {                             \
            ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:96:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipMalloc)                                \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:62:7: error: expected primary-expression before ')' token
     }();                                                                    \
       ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:96:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipMalloc)                                \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h: At global scope:
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:106:11: error: '::hipMemsetD32' has not been declared
   __macro(hipMemsetD32)                             \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:106:11: note: suggested alternative: 'hipMemset3D'
   __macro(hipMemsetD32)                             \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:106:11: error: '::hipMemsetD32' has not been declared
   __macro(hipMemsetD32)                             \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:106:11: note: suggested alternative: 'hipMemset3D'
   __macro(hipMemsetD32)                             \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:109:11: error: '::hipMemsetD32Async' has not been declared
   __macro(hipMemsetD32Async)                        \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:109:11: note: suggested alternative: 'hipMemset3DAsync'
   __macro(hipMemsetD32Async)                        \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:109:11: error: '::hipMemsetD32Async' has not been declared
   __macro(hipMemsetD32Async)                        \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:109:11: note: suggested alternative: 'hipMemset3DAsync'
   __macro(hipMemsetD32Async)                        \
           ^
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:50:48: note: in definition of macro 'STREAM_EXECUTOR_HIP_WRAP'
   auto hipSymbolName(Args... args)->decltype(::hipSymbolName(args...)) {    \
                                                ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc: In static member function 'static bool stream_executor::gpu::GpuDriver::SynchronousMemsetUint32(stream_executor::gpu::GpuContext*, hipDeviceptr_t, tensorflow::uint32, size_t)':
tensorflow/stream_executor/rocm/rocm_driver.cc:491:38: error: 'hipMemsetD32' is not a member of 'tensorflow::wrap'
   hipError_t res = tensorflow::wrap::hipMemsetD32(pointer, value, uint32_count);
                                      ^~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc:491:38: note: suggested alternative: 'hipMemsetD8'
   hipError_t res = tensorflow::wrap::hipMemsetD32(pointer, value, uint32_count);
                                      ^~~~~~~~~~~~
                                      hipMemsetD8
tensorflow/stream_executor/rocm/rocm_driver.cc: In static member function 'static bool stream_executor::gpu::GpuDriver::AsynchronousMemsetUint32(stream_executor::gpu::GpuContext*, hipDeviceptr_t, tensorflow::uint32, size_t, stream_executor::gpu::GpuStreamHandle)':
tensorflow/stream_executor/rocm/rocm_driver.cc:521:38: error: 'hipMemsetD32Async' is not a member of 'tensorflow::wrap'
   hipError_t res = tensorflow::wrap::hipMemsetD32Async(pointer, value, uint32_count, stream);
                                      ^~~~~~~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc:521:38: note: suggested alternative: 'hipMemsetAsync'
   hipError_t res = tensorflow::wrap::hipMemsetD32Async(pointer, value, uint32_count, stream);
                                      ^~~~~~~~~~~~~~~~~
                                      hipMemsetAsync
In file included from tensorflow/stream_executor/rocm/rocm_driver.cc:29:0:
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h: In instantiation of 'decltype (hipMalloc(tensorflow::wrap::hipMalloc::args ...)) tensorflow::wrap::hipMalloc(Args ...) [with Args = {void**, long long unsigned int}; decltype (hipMalloc(tensorflow::wrap::hipMalloc::args ...)) = hipError_t]':
tensorflow/stream_executor/rocm/rocm_driver.cc:627:62:   required from here
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:63:18: error: 'loaded' was not declared in this scope
     return loaded(args...);                                                 \
            ~~~~~~^~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:96:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipMalloc)                                \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h: In instantiation of 'decltype (hipHostMalloc(tensorflow::wrap::hipHostMalloc::args ...)) tensorflow::wrap::hipHostMalloc(Args ...) [with Args = {void**, long long unsigned int, int}; decltype (hipHostMalloc(tensorflow::wrap::hipHostMalloc::args ...)) = hipError_t]':
tensorflow/stream_executor/rocm/rocm_driver.cc:673:91:   required from here
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:63:18: error: 'loaded' was not declared in this scope
     return loaded(args...);                                                 \
            ~~~~~~^~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:92:3: note: in expansion of macro 'STREAM_EXECUTOR_HIP_WRAP'
   __macro(hipHostMalloc)                            \
   ^~~~~~~
./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:125:1: note: in expansion of macro 'HIP_ROUTINE_EACH'
 HIP_ROUTINE_EACH(STREAM_EXECUTOR_HIP_WRAP)
 ^~~~~~~~~~~~~~~~
tensorflow/stream_executor/rocm/rocm_driver.cc: In function 'std::__cxx11::string stream_executor::gpu::MemorySpaceString(stream_executor::gpu::MemorySpace)':
tensorflow/stream_executor/rocm/rocm_driver.cc:123:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

**Comment by whchung** [comment]
There are new HIP runtime APIs being used in this branch, which is yet released in ROCm 2.2. They are already in the tip of HIP repo and would be released in ROCm 2.3.

If you clone HIP and build it from source, please notice the following components would also have to be built from source too:

rocRAND 
rocBLAS 
rocFFT
MIOpen

Once you build these 5 components from source, then you can build TF 2.0 branch from source.

@sunway513 shall we publish an early preview PyPI or docker container for 2.0 alpha branch?

**Comment by sunway513** [comment]
@hwchong , here's the prerequisite steps to build `r2.0-rocm` branch based on ROCm2.2:
```
cd ~ && git clone https://github.com/ROCm-Developer-Tools/HIP.git && \
    mkdir HIP/build && cd HIP/build && \
    git checkout -b 2019-03-06 0c4a40efcc974e5a4b2935fb84b3e8d368e9880b && \
    cmake .. && make package -j $(nproc) && dpkg -i ./hip*.deb
cd ~ && wget https://www.dropbox.com/s/e6yh6glemrkoo91/tf-pr318-deb-pkgs.tar.gz && \
    tar xzf tf-pr318-deb-pkgs.tar.gz && dpkg -i ./tf-pr318-deb-pkgs/*.deb
```
I would suggest using our dev base docker image for such experiment so it won't break your local ROCm user-bit environment:
`sudo docker pull rocm/tesnorflow:rocm2.2-tf1.13-python3-dev`

**Comment by hwchong** [comment]
Thank you for the advice! Yes it would be great if you guys could provide a TF2.0a Docker image for us to try.
