### ISSUE TITLE
how to build tfprof on rocm platform

### ISSUE THREAD

**Issue by xiongshan** [ROCmSoftwarePlatform/tensorflow-upstream#371]
Hi,
I am failed to build tfprof on ROCm platform by command:
_"bazel build --config opt tensorflow/core/profiler:profiler"_
or
_"TF_NEED_ROCM=1 PYTHON_BIN_PATH=/usr/bin/python3 ./configure
bazel build -s --config=opt --config=rocm --action_env=HIP_PLATFORM=hcc tensorflow/core/profiler:profiler"_

is there any official guide can build pass?

Thanks

**Comment by whchung** [comment]
@xiongshan could you help share your system configuration, and the errors you are seeing?

I just verified that `//tensorflow/core/profiler:profiler` can be properly built with the following configuration:

- ROCm: 2.2
- Docker image tag: `rocm/tensorflow:rocm2.2-tf1.13-python3-dev`
- Config command:
```
TF_NEED_ROCM=1 PYTHON_BIN_PATH=/usr/bin/python3 ./configure
```
- Build command:
```
bazel build -s --config=opt --config=rocm --action_env=HIP_PLATFORM=hcc tensorflow/core/profiler:profiler
```

Also I've verified `tfprof` builds fine in the upcoming release candidates for ROCm 2.3.

**Comment by xiongshan** [comment]
@whchung , previously, I user _rocm/tensorflow:latest_ docker image (it is rocm2.1 sevral days ago.) and sync “latest” _tensorflow-upstream_ codebase to build, not from a tag, this maybe cause the build error.  
Now it works well base on the tensorflow codebase in _rocm/tensorflow:rocm2.2-tf1.13-python3-dev_
Thanks for your kindly help !
