### ISSUE TITLE
build_rocm_python3 fails on Springdale 7.6 (RHEL)

### ISSUE THREAD

**Issue by tbalbers** [ROCmSoftwarePlatform/tensorflow-upstream#372]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Springdale 7.6 x86_64 (RHEL rebuild, kernel 3.10.0-957.10.1.el7.x86_64)

- **TensorFlow installed from (source or binary)**:

source

- **TensorFlow version (use command below)**:

1.13.0

- **Python version**:

3.6.3

- **Bazel version (if compiling from source)**:

0.21.0

- **GCC/Compiler version (if compiling from source)**:

4.8.5

- **CUDA/cuDNN version**:

N/A

- **GPU model and memory**:

Radeon Pro WX 7100 8GB

- **Exact command to reproduce**:

[tba@rockem tensorflow-upstream]$ git clone -b r1.13-rocm https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git

[tba@rockem tensorflow-upstream]$ ./build_rocm_python3

### Describe the problem

build_rocm_python3 fails with:

Execution platform: @bazel_tools//platforms:host_platform
external/com_google_absl/absl/base/dynamic_annotations.cc:1:0: error: bad value (haswell) for -march= switch

It's a Xeon W-2175 processor aka skylake. I can't see how the value march=haswell is set.

### Source code / logs

ERROR: /home/tba/.cache/bazel/_bazel_tba/2caf3292469d3f55a6a7c04e2f276364/external/com_google_absl/absl/base/BUILD.bazel:58:1: C++ compilation of rule '@com_google_absl//absl/base:dynamic_annotations' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /home/tba/.cache/bazel/_bazel_tba/2caf3292469d3f55a6a7c04e2f276364/execroot/org_tensorflow && \
  exec env - \
    HIP_PLATFORM=hcc \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/opt/rh/rh-python36/root/lib/python3.6/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=1 \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/k8-opt/bin/external/com_google_absl/absl/base/_objs/dynamic_annotations/dynamic_annotations.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_google_absl/absl/base/_objs/dynamic_annotations/dynamic_annotations.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl '-march=haswell' -Wno-sign-compare -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-sign-compare -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c external/com_google_absl/absl/base/dynamic_annotations.cc -o bazel-out/k8-opt/bin/external/com_google_absl/absl/base/_objs/dynamic_annotations/dynamic_annotations.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
external/com_google_absl/absl/base/dynamic_annotations.cc:1:0: error: bad value (haswell) for -march= switch
 // Copyright 2017 The Abseil Authors.

**Comment by sunway513** [comment]
Hi @tbalbers , Springdale is not in ROCm support list, doc is here:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available
Our documentation is for Ubuntu:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-build-from-source.md

You can alternatively use either of the following two dev docker images to rebuild tensorflow-rocm from source:
```
# Ubuntu docker image
rocm/tensorflow:rocm2.2-tf1.13-python3-dev
# CentOS docker image
rocm/tensorflow:rocm2.2-tf1.13-centos-dev
```
