### ISSUE TITLE
Build TF 1.13.1 from source

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/tensorflow-upstream#379]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source code
- TensorFlow version: v1.13.1
- Python version: python 2.7
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 7.3 & hcc of ROCM 2.2
- ROCm/MIOpen version: 2.2
- GPU model and memory: vega 64

Build error

ERROR: /home/motech/tensorflow-r13-rocm/tensorflow-upstream/tensorflow/core/kernels/BUILD:3774:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:softmax_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/softmax_op_gpu.cu.cc':
  '/opt/rocm/hcc/lib/clang/9.0.0/include/stddef.h'
  '/opt/rocm/hcc/lib/clang/9.0.0/include/__stddef_max_align_t.h'
  '/opt/rocm/hcc/lib/clang/9.0.0/include/stdarg.h'
  '/opt/rocm/hcc/lib/clang/9.0.0/include/stdint.h'
  '/opt/rocm/hcc/lib/clang/9.0.0/include/limits.h'

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sunway513** [comment]
duplicate issue of #380
