### ISSUE TITLE
Tensorflow supports Python 3.7 in 1.13.1

### ISSUE THREAD

**Issue by elukey** [ROCmSoftwarePlatform/tensorflow-upstream#389]
Hi! As far as I can see Tensorflow supports Python 3.7 in 1.13.1, as well as in Pypi. Is there any plan to make the tensorflow-rocm be available for Python 3.7 as well?

**Comment by parallelo** [comment]
Yes, we're working on Python 3.7 WHL support.  Will update this Issue when it becomes available.

**Comment by parallelo** [comment]
Update:  we have uploaded an experimental Python 3.7 `tensorflow-rocm` WHL to PyPI.  

https://pypi.org/project/tensorflow-rocm/1.13.1/#files

Closing this issue for now.  Please give the WHL a try, and feel free to reopen this issue if you hit any problems.

**Comment by timlueg** [comment]
Would you be able to provide a WHL for the latest tensorflow-rocm 1.13.2 version to to test with rocm 2.3 ? 
(Reason being that Ubuntu 19.04 now provides only python3.7 as default)

**Comment by sunway513** [comment]
@timlueg we have seen some issues while trying to build python3.7 package for ROCm2.3, we are working on the fix. 
Can you use our pre-built docker images before the tensorflow-rocm 1.13.2 whl package available? Here's the link to the dockerhub repo:
https://hub.docker.com/r/rocm/tensorflow

**Comment by parallelo** [comment]
Correct, there was an issue with our pipeline for building Python3.7 WHLs.  This has been fixed.  Just posted the 3.7 WHL for TF 1.13.2. 
https://pypi.org/project/tensorflow-rocm/1.13.2/#files

Please give it a try, and let us know if you hit any challenges.

**Comment by acowley** [comment]
I [updated](https://github.com/nixos-rocm/nixos-rocm/commit/b1698fd5af692ae07b4eb78887c1d60e279e115c) the [NixOS ROCm](https://github.com/nixos-rocm/nixos-rocm) packages to use the new Python 3.7 wheel without encountering any issues. This makes installing much faster on NixOS as we no longer serve binaries for Python 3.6 packages; thank you!
