### ISSUE TITLE
` tf.layers.conv2d(.., strides=(4, 4))` is extremely slow for ROCm than CUDA

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#393]
Operator: ```tf.layers.conv2d(.., strides=(4, 4))```

It is a beginning layer for Alexnet_Imagenet model, it makes Alexnet over ROCm much slower than CUDA.

**Comment by sunway513** [comment]
Thank you @ghostplant ! 
Just want to comment that the performance for Alexnet model has been well studied; we've identified some bottlenecks and working on optimizations across the stack.  
I'm closing this issue for now, will re-open it and update you when we have more information available.
