### ISSUE TITLE
tf_cnn_benchmark hangs on "running warm up" with ROCm 2.3

### ISSUE THREAD

**Issue by hongshaojichi** [ROCmSoftwarePlatform/tensorflow-upstream#410]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pop! OS 18.04 LTS based on Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 1.13.1 from pip3
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.3
- GPU model and memory: dual vega 64 8GB VRAM each

**Describe the current behavior**
python tf_cnn_benchmarks.py --num_gpus=1 --batch_size=64 --model=resnet50 hangs on "running warm up"
**Describe the expected behavior**
it shouldn't hang
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by hongshaojichi** [comment]
With ROCm 2.2, though not officially supported with kernel 4.18, the same benchmark can run. However warming up also takes one or two minutes. I didn't time it but it did take some time the first time I ran it.

**Comment by sunway513** [comment]
@hongshaojichi , TF1.13.1 is not compatible to ROCm2.3 user bit, please upgrade your pip package and test again:
`pip3 install --user tensorflow-rocm --upgrade`

If you can still see the system hang, please try to run the HIP unit tests and see if those can pass:
https://github.com/ROCm-Developer-Tools/HIP/tree/master/tests

**Comment by hongshaojichi** [comment]
@sunway513 Thanks for the quick response! I quickly tried it. It no longer hangs but performance doesn't look right:
Step	Img/sec	total_loss
1	images/sec: 3.8 +/- 0.0 (jitter = 0.0)	8.220
10	images/sec: 14.9 +/- 18.4 (jitter = 0.7)	7.880

I opened interactive python shell and did "import tensorflow as tf", tf.__version__ still shows 1.13.1
Did I miss anything?

**Comment by sunway513** [comment]
hi @hongshaojichi  it looks like your local ROCm environment is not properly configured. 
To help triage the issue, could you try the tensorflow-rocm docker image hosted in dockerhub:
https://cloud.docker.com/u/rocm/repository/docker/rocm/tensorflow
As for the tensorflow-rocm whl package, we only bump the whl package versions so that we can refresh the PyPI uploads (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/dac9920c89cc1516204cb7a5a9a47533f255abec). If you query the TF version from the Python interface it'll still show as 1.13.1, this is to align with the upstream tensorflow versions.

**Comment by hongshaojichi** [comment]
Hi @sunway513 thanks for the help! Looks your docker link doesn't work. 
Is this the correct location:
https://hub.docker.com/r/rocm/tensorflow

Thanks!

**Comment by sunway513** [comment]
@hongshaojichi , yes, that's the public link of the dockerbub repo :-)

**Comment by hongshaojichi** [comment]
@sunway513 Thanks man! Never used docker before. I'll set it up and get back to you.

**Comment by hongshaojichi** [comment]
@sunway513 docker is able to run warm up but also very slow performance. I figured out to use "TF_ROCM_FUSION_ENABLE=1 python3 tf_cnn_benchmarks.py --num_gpus=2 --batch_size=64 --model=resnet50 --variable_update=parameter_server --local_parameter_device=cpu" Fusion plus cpu as parameter device restored performance to okay level.

**Comment by sunway513** [comment]
Hi @hongshaojichi , thank you for the update. If bare metal support is still needed, you can follow the instructions I've posted [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/173#issuecomment-483334978) to clean up your ROCm user bit configurations. 
I'll close this issue for now, please let us know if you have further questions.
