### ISSUE TITLE
rocm 2.3 vega 64 performance slow on custom RNN

### ISSUE THREAD

**Issue by hongshaojichi** [ROCmSoftwarePlatform/tensorflow-upstream#430]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

The clock speed seems wrong when training on custom RNN:

========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan    Perf  PwrCap  SCLK OD  MCLK OD  GPU%  
0    36.0c  4.0W    852Mhz  167Mhz  29.8%  auto  220.0W  0%       0%       0%    
1    29.0c  5.0W    852Mhz  167Mhz  14.9%  auto  220.0W  0%       0%       0%    
================================================================================
==============================End of ROCm SMI Log ==============================

Resulting very slow training speed:

Epoch 1/1000
36373/36373 [==============================] - 27s 753us/step

On my thinkpad x1e with 1050ti i get 57us/step

However with tf_benchmark I get normal speed. Did I miss any setup?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.2
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.3
- GPU model and memory: dual vega 64

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sunway513** [comment]
Hi @hongshaojichi , could you provide us steps to repro your observations? 
If you have not, please try our docker images:
https://cloud.docker.com/u/rocm/repository/docker/rocm/tensorflow

**Comment by sunway513** [comment]
Hi @hongshaojichi , there's some community feedback that the RNN perf has been improved a bit with ROCm2.4, could you try your application with our latest docker image and see if the concern remains?

**Comment by sunway513** [comment]
I'm closing this issue for now, please feel free to re-open it if there are further updates.
