### ISSUE TITLE
Install Tensorflow on ROCm

### ISSUE THREAD

**Issue by quocdat32461997** [ROCmSoftwarePlatform/tensorflow-upstream#434]
Hi, 
I am having my AMD Radeon VII and installed ROCm stack.
Surprisingly, it could handle the graphic processing.
However, after I installed Tensorflow-rocm through pip3. Then, hit python3 and import Tensorflow. 
It produces error "Module not found". 
I am curious if I need to "pip3 install tensorflow-gpu" after installing tensorflow-rocm.

**Comment by sunway513** [comment]
HI @quocdat32461997 , thanks for trying out. 
No, you don't need to install tensorflow-gpu package, the tensorflow-rocm package is all-inclusive for Tensorflow support on ROCm.
Let's step back a bit, can you provide us the logs for the following commands?
`uname -a`
`apt --installed list | grep rock-dkms` 
`/opt/rocm/bin/rocminfo`

**Comment by sunway513** [comment]
@quocdat32461997 , any updates on the requested logs?

**Comment by sunway513** [comment]
I'm going to close this issue, for basic TF-ROCm installation please refer to the following document:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md
Please feel free to reopen it if you have further questions.
