### ISSUE TITLE
undefined symbol: _ZN8hip_impl19Bundled_code_header13magic_string_E

### ISSUE THREAD

**Issue by arlenh** [ROCmSoftwarePlatform/tensorflow-upstream#444]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from binary: 1.13.2
- Python version: 3.6.7
- ROCm/MIOpen version: 2.4 / 1.8.1
- GPU model and memory: vega 64 8G

When importing tensorflow in python, I got the undefined symbol error
ImportError: /home/user/rocm/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl19Bundled_code_header13magic_string_E

Does it a problem when I upgraded ROCm to 2.4 ?

**Comment by whchung** [comment]
@arlenh sorry for your inconveniences, we are preparing new whl packages and docker images be compatible with ROCm 2.4.
