### ISSUE TITLE
whats the best/proper way to use tensorflow 2.0 with rocm 2.4? :)

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#452]
whats the best/proper way to use tensorflow 2.0 with rocm 2.4? :)

**Comment by sunway513** [comment]
Hi @witeko , if you mean the TF2.0-alpha0 release, we have the following docker image readily available:
rocm/tensorflow:rocm2.4-tf2.0-alpha0-config-v2  
Please kindly try it out and let us know if anything needs our attention.
