### ISSUE TITLE
Building for ROCm on machine without GPU

### ISSUE THREAD

**Issue by chsigg** [ROCmSoftwarePlatform/tensorflow-upstream#508]
**System information**
- Ubuntu 14.04
- Docker from https://github.com/RadeonOpenCompute/ROCm-docker
- TensorFlow from upstream repo at HEAD
- GPU model and memory: None!

**Describe the problem**
I'm trying to build TF for ROCm on a machine without a GPU. 
The TF_ROCM_AMDGPU_TARGETS environment variable is not hooked up:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/43fa8c43f1efb4e80dbe5018338e8b7113c02253/third_party/gpus/rocm_configure.bzl#L653
I'm suspecting that the compiler invoked from `crosstool_wrapper_driver_is_not_gcc` tries to get the GPU installed from `/opt/rocm/bin/rocm_agent_enumerator` which returns `gfx000` and compilation fails. If I replace that tool with a script that prints `gfx803` I'm able to get past the issue.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
yes '' | TF_NEED_ROCM=1 TF_ENABLE_XLA=0 PYTHON_BIN_PATH=$(which python3) ./configure
bazel build tensorflow
```

**Comment by chsigg** [comment]
@whchung, are you able to help with this?

**Comment by whchung** [comment]
@chsigg I assume you don't have ROCm linux kernel driver installed in your baremetal. Please refer to https://github.com/RadeonOpenCompute/ROCm on how to install the driver on your baremetal.

On the other hand, if that's intentional that you don't want to install ROCm linux kernel driver, you can trick `rocm_agent_enumerator` inside the docker with a text file under `/opt/rocm/bin/target.lst`. In the file put each line of your desired AMD GCN ISA version inside. For example:

```
gfx803
gfx900
gfx906
```
 would trick `rocm_agent_enumerator` thinking you have 3 different AMD GPUs installed.

**Comment by sunway513** [comment]
Hi @chsigg , like @whchung  suggested, if you add the following line in your Dockerfile then the HIP/HCC toolchain would build applications for gfx803/gfx900/gfx906 targets:
`RUN bash -c 'echo -e "gfx803\ngfx900\ngfx906" >> /opt/rocm/bin/target.lst'`

**Comment by parallelo** [comment]
@chsigg - And if you need to use the `ci_build` infrastructure, here's how to do it on machines without GPUs:
```
#!/bin/bash -x

# Build-only mod:  remove docker's use of kfd and dri devices
sed -i 's|ROCM_EXTRA_PARAMS="--device=/dev/kfd --device=/dev/dri --group-add video"|ROCM_EXTRA_PARAMS=""|g' tensorflow/tools/ci_build/ci_build.sh

# Build Python2 whl files
export CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python2 -e PIP_TEST_ROOT=pip2_test -e NO_TEST_ON_INSTALL=1 -e NO_TEST_USER_OPS=1 -e NO_TEST_TFDBG_BINARIES=1"
tensorflow/tools/ci_build/ci_build.sh ROCM tensorflow/tools/ci_build/builds/pip.sh rocm -c opt --config=rocm
```

**Comment by srinivirt** [comment]
The workaround for no GPU can be found in line 74 of dockerfile
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.rocm
RUN bash -c 'echo -e "gfx803\ngfx900\ngfx906" >> /opt/rocm/bin/target.lst'

**Comment by chsigg** [comment]
Thanks a lot, I didn't notice that line before. Everything is working now.
