### ISSUE TITLE
Tensorflow built with rocm2.5 not uploaded to pypi

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#510]
Tensorflow built with rocm2.5 not uploaded to pypi:

- OS: Ubuntu 16.04/18.04;
- Python: 3.5 (for 16.04) / 3.6 (for 18.04);

PYPI Link: https://pypi.org/project/tensorflow-rocm/#files

So when can latest tensorflow-rocm2.5 be uploaded to pypi, or where can I download the prebuilt tensorflow wheel package for rocm2.5?

Currently, I can only get the prebuilt version from dockerhub: `rocm/tensorflow
` and it is based on 16.04 only, but I require a TF-rocm2.5 **wheel** package install-able on 18.04.

**Comment by sunway513** [comment]
Hi @ghostplant , we tested the current tensorflow-rocm whl packages generated with ROCm2.4 using the ROCm2.5 user-bit environment, it's compatible. Therefore we didn't bump the TF-ROCm minor version and refresh the whl packages. 
Did you see issues using the current TF-ROCM whl packages hosted on PyPI with ROCm2.5?

**Comment by sunway513** [comment]
Hi @ghostplant , I'm going to close this ticket. Please feel free to reopen it if you have further questions.

**Comment by ghostplant** [comment]
@sunway513 Hi, because there is a feature change in HIP-library 2.5 so that I need a tensorflow-rocm that is compiled base on that feature, and tensorflow-rocm for HIP 2.4 is not working for me. Till now, I still doesn't see it updated in the pypi.

**Comment by sunway513** [comment]
@ghostplant , can you please let us know the particular feature you were looking for and steps to repro?
After confirming we can update the whl packages in pypi.

**Comment by ghostplant** [comment]
After fixing the in-proper call from hip user-program to libhsa-runtime.so (since ROCm 2.5), there should be no directly call bypass HIP library, like:
```sh
nm -D /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so | grep "U hsa"
```
which should output nothing.

If you try on the ROCm-2.4 based tensorflow, it should output many inproper calls to HSA, which is not expected.
