### ISSUE TITLE
TensorFlow for Java Support

### ISSUE THREAD

**Issue by vsrikarunyan** [ROCmSoftwarePlatform/tensorflow-upstream#544]
Do we have access to the relevant TensorFlow for Java JNI libraries and jar files that are potentially created out of the ROCm TensorFlow repository? If not, what is the suggested approach to create the same?

**Comment by sunway513** [comment]
Hi @vsrikarunyan , we have reviewed the requirement to support Java for Tensorflow using the following document:
https://www.tensorflow.org/install/lang_java
Unfortunately, it's unlikely we'll be able to enable this feature in the short term. We can review this feature request after all TF-ROCm support is fully upstreamed, thank you.
