### ISSUE TITLE
Compilation error "undeclared inclusion(s) in rule '@rccl_archive//:rccl'"  on ROCm 2.4 with TF r1.12-rocm

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/tensorflow-upstream#549]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.12-rocm
- Python version: Python 2 and Python 3
- Installed using virtualenv? pip? conda?: pip 
- Bazel version (if compiling from source): 0.15.2
- GCC/Compiler version (if compiling from source): 7.4.0
- ROCm/MIOpen version: rocm-2.4
- GPU model and memory: gfx900

**Describe the problem**
Compilation error "undeclared inclusion(s) in rule '@rccl_archive//:rccl'"  on ROCm 2.4 without rccl-0.7.5.deb pacakge installed.

but, it is built successfully at a month ago. What changed at rccl_archive? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /home/motech/.cache/bazel/_bazel_root/2017a5f678c265a6d8e31ebda8938e6f/external/rccl_archive/BUILD.bazel:10:1: undeclared inclusion(s) in rule '@rccl_archive//:rccl':
this rule is missing dependency declarations for the following files included by 'external/rccl_archive/src/rccl.cpp':
  '/opt/rocm-2.4-0625/hcc/lib/clang/9.0.0/include/stddef.h'
  '/opt/rocm-2.4-0625/hcc/lib/clang/9.0.0/include/stdint.h'
  '/opt/rocm-2.4-0625/hcc/lib/clang/9.0.0/include/__stddef_max_align_t.h'
  '/opt/rocm-2.4-0625/hcc/lib/clang/9.0.0/include/limits.h'
  '/opt/rocm-2.4-0625/hcc/lib/clang/9.0.0/include/stdarg.h'

**Comment by wormwang** [comment]
stupid bazel. closed

**Comment by LaoFeng876** [comment]
Could you tell me how you solve that? I met a similar problem like yours, thanks

**Comment by LaoFeng876** [comment]
> 
> 
> stupid bazel. closed

Hi, could you tell me how you solve that? I met a similar problem like yours, thanks
