### ISSUE TITLE
cant "import tensorflow-rocm 2.0 beta1" after installing rocm 2.6

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#551]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tensorflow-rocm 2.0beta1 installed from source (worked fine with rocm 2.5)
- TensorFlow version (use command below):
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.6
- GPU model and memory: radeon vii x 2

**Describe the current behavior**
Error while trying to import:
ImportError                               Traceback (most recent call last)
/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/usr/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/usr/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: /mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl13program_state11executablesE11hsa_agent_s

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-3949b3a894b8> in <module>
----> 1 import tensorflow as tf
      2 AUTOTUNE = tf.data.experimental.AUTOTUNE
      3 import sys
      4 sys.path.append('rxrx1-utils')
      5 from tqdm import tqdm

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     38 import sys as _sys
     39 
---> 40 from tensorflow.python.tools import module_util as _module_util
     41 
     42 from tensorflow._api.v2 import audio

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl13program_state11executablesE11hsa_agent_s

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Describe the expected behavior** no error

**Code to reproduce the issue**
import tensorflow as tf

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sunway513** [comment]
Hi @witeko , it looks like your HIP version was not upgraded to ROCm2.6.
Could you try to purge all the ROCm user-bit components on your bare metal system and install ROCm2.6 from clean?
`sudo apt autoremove -y rocm_bandwidth_test rocminfo hsakmt-roct hsa-rocr-dev rocm-cmake hsa-ext-rocr-dev rocm-device-libs hip_base hip_samples`
`sudo apt update && sudo apt install rocm-libs miopen-hip cxlactivitylogger`

**Comment by witeko** [comment]
@sunway513 ive purged rocm components 2 times, and i also purged tensorflow. The issue persists.

**Comment by sunway513** [comment]
@witeko , does it work with the latest public docker container? Can you try with that:
rocm/tensorflow:rocm2.6-tf1.14-python3

**Comment by witeko** [comment]
@sunway513 Ive tried sth else - I used pip install tensorflow-rocm==2.0.0b1 this time instead of my "build from source" version, and this time it works. :)

**Comment by witeko** [comment]
@sunway513 thanks for your help. :)

**Comment by sunway513** [comment]
Great, thank you @witeko  for the update :-)
