### ISSUE TITLE
Instruction not supported on this GPU (from ROCm2.6) gfx803

### ISSUE THREAD

**Issue by Ukhupacha** [ROCmSoftwarePlatform/tensorflow-upstream#557]
**System information**
- Fedora 28:
- docker rocm/tensorflow:rocm2.6-tf1.13-python3  and rocm/tensorflow:rocm2.6-tf1.14-python3
- ROCm/MIOpen version:2.6
- GPU model and memory: Radeon E9171 4GB

**Describe the current behavior**
When I was using the rocm2.5 versions, the only issue I have is that it looks for the gf803_8.cd.pdb.txt file but at the end, it processes the benchmark. Now witth 2.6 version, I get a core dumped saying that the instruction is not supported
**Describe the expected behavior**
`<instantiation>:5:9: error: instruction not supported on this GPU
        v_sub_u32 v[input_storage], s[gid_hw], v[input_storage]
        ^
<instantiation>:6:9: note: while in macro instantiation
        get_global_Wtid vtid_w, vtmp, input_storage,  vtid_w
        ^
<stdin>:908:5: note: while in macro instantiation
    get_gloabl_H_W_tids vtid_h, vtid_w, input_storage, vtid_w`

**Code to reproduce the issue**
`python3 benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py -model=resnet50 -forward_only=True -batch_size=1`
on rocm2.6-tf1.13-python3 and rocm2.6-tf1.14-python3

[radeon E9171 rocm2.6 tf.13 docker.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3378279/radeon.E9171.rocm2.6.tf.13.docker.txt)

I also tried the rpms from the rocm repo and installing the pypi wheel tensorflow-rocm 1.14 with the same results.
Is there a way to surpass this? Or I should just use the rocm2.5 versions.

Thanks

**Comment by sunway513** [comment]
@Ukhupacha , could you refer to our TF1.14 release note below?
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/RELEASE.md#known-issues

**Comment by Ukhupacha** [comment]
@sunway513 Thanks a lot, but it is was an issue of ROCm 2.6 cause it occurs the same with TF1.13
