### ISSUE TITLE
cant load tf 1.14

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#558]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04 kernel 4.18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tensorflow-rocm 1.14
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.6
- GPU model and memory: 2xradeon7

**Describe the current behavior**
i get the following error while "import tensorflow as tf":
ImportError                               Traceback (most recent call last)
/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/usr/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/usr/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: librccl.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-2fb77ec0620b> in <module>
----> 1 import tensorflow as tf
      2 import numpy as np
      3 import pandas as pd
      4 import sys
      5 from PIL import Image

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     26 
     27 # pylint: disable=g-bad-import-order
---> 28 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     29 from tensorflow.python.tools import module_util as _module_util
     30 

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/mnt/big_fast/CELLS/tf20cells/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: librccl.so: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Describe the expected behavior**
there should be no error

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
I already tried purging rocm and purging tensorflow.
The newest working tensorflow is 1.13.3

**Comment by witeko** [comment]
OK, I solved it - after purging rocm i needed to run the full:
sudo apt-get update && \
    sudo apt-get install -y --allow-unauthenticated \
    rocm-dkms rocm-dev rocm-libs rccl \
    rocm-device-libs \
    hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev \
    rocm-opencl rocm-opencl-dev \
    rocm-utils \
    rocm-profiler cxlactivitylogger \
    miopen-hip miopengemm

**Comment by vegabook** [comment]
> OK, I solved it - after purging rocm i needed to run the full:
> sudo apt-get update &&
> sudo apt-get install -y --allow-unauthenticated
> rocm-dkms rocm-dev rocm-libs rccl
> rocm-device-libs
> hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev
> rocm-opencl rocm-opencl-dev
> rocm-utils
> rocm-profiler cxlactivitylogger
> miopen-hip miopengemm

This does not work for me, causing a segmentation fault.

**Comment by vnikiti** [comment]
I get the following error after installing `rccl`
```
*** stack smashing detected ***: <unknown> terminated
Fatal Python error: Aborted
```

**Comment by sunway513** [comment]
@vnikiti , can you provide the output for the following command:
apt --installed list | grep -E 'hip|hcc|roc|miopen|amdgpu|hsa|rccl'
It would be helpful if you can try our docker container and see if the issue remains:
https://hub.docker.com/r/rocm/tensorflow

**Comment by crr0004** [comment]
I had the same issue, it went away when I downgraded to python3.5 from python3.6, and installed tensorflow-rocm==1.14.1

I was comparing the invocation against the provided ROCM image to find it

**Comment by frederickayala** [comment]
I had the same issue. Changing to python 3.5 and installing tensorflow with `pip install tensorflow-rocm==2.0.0b3
` solved it. Thanks.
