### ISSUE TITLE
tensorflow-rocm and ROCm 2.6 issues

### ISSUE THREAD

**Issue by elukey** [ROCmSoftwarePlatform/tensorflow-upstream#559]
Hi everybody,

I have recently upgraded ROCm 2.4 to 2.6, and tensorflow-rocm seems not to work as expected. I was running tensorflow-rocm 1.13.1 (installed in a Python venv via pip) and after the upgrade to ROCm 2.6, I had to upgrade to 1.14.0 since the GPU was not recognized anymore. With 1.14.0 the GPU us recognized, but a trivial tensorflow session hangs after sending kernels to the GPU. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Buster (Kernel 4.19.37)
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7
- ROCm/MIOpen version: 2.6
- GPU model and memory: Radeon PRO WX 9100 (Vega 10 TX)

**Describe the current behavior**
Executing the following trivial Tensorflow example leads to a complete stall, and cpu usage up to 100%:
```
import tensorflow as tf
# Creates a graph.
with tf.device('/device:GPU:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
  c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))
```
I am attaching to this report logs related to:
1) gdb thread apply all bt
2) dmesg during the timeframe
3) tensorflow's output

**Describe the expected behavior**
TF Session correctly finishing reporting the result.

**Other info / logs**
I tested also TF-rocm 1.13.4 and the result was the same. I downgraded ROCm to 2.5, and with 1.14.0 and 1.13.4 I got a different error:

```
Traceback (most recent call last):
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/srv/home/elukey/test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/srv/home/elukey/test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl7kernarg6resizeEm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_tf.py", line 1, in <module>
    import tensorflow as tf
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/srv/home/elukey/test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/srv/home/elukey/test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl7kernarg6resizeEm


Failed to load the native TensorFlow runtime.
```

The above error seems to be due to libhip_hcc.so. The following is `nm`  applied to the the .so file from ROCm 2.6:

```
nm ./opt/rocm/hip/lib/libhip_hcc.so | grep _ZN8hip_impl13agent_globalsD1Ev
00000000000d3820 T _ZN8hip_impl13agent_globalsD1Ev
```

Using ROCm 2.5 and TF-rocm 1.13.3 works fine (the above example and others all run correctly). I am not sure if I am missing data or something trivial to do/check, please let me know in case and I'll add it.

Thanks in advance!

**Comment by sunway513** [comment]
Hi @elukey , this looks like an environmental issue. Please note you need the latest TF-ROCm release whl packages to run with ROCm2.6 environment, those includes:
tensorflow-rocm==1.13.4 
tensorflow-rocm==1.14.0
tensorflow-rocm==2.0.0b1

I'd suggest you clean up your ROCm installation using the following steps:
`sudo apt autoremove -y rocm_bandwidth_test rocminfo hsakmt-roct hsa-rocr-dev rocm-cmake hsa-ext-rocr-dev rocm-device-libs hip_base hip_samples`
And then follow our official doc here to configure the bare metal TF-ROCm environment:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md

Also, you can try to launch a docker container and see if that can work:
https://hub.docker.com/r/rocm/tensorflow

**Comment by elukey** [comment]
Hi @sunway513, thanks for the answer. There are two issues that I am currently facing:
1) ROCm 2.6 on my system doesn't work with tf-rocm 1.14.0 and 1.13.4 as described. Downgrading ROCm to 2.5 + tensorflow-rocm 1.13.3 works fine, so something else must be the problem. I'd probably need some suggestions about how to debug further, the downgrade to 2.5 seems to me a good indication that I did a clean up but only ROCm 2.5 seems to work.

2) ROCm 2.5 seems not working with tensorflow-rocm 1.13.4+. The bug report explicitly mentions the fact that a library seems not ABI compatible, so the suspicion is that certain versions of tensorflow-rocm (at least in pypi) are built with specific versions of ROCm, dropping support for the older ones. Running 2.5 with the last version of tensorflow-rocm seems a valid use case to me, but if this is not possible it should be advertised somehow (I may have missed it, in case apologies).

**Comment by sunway513** [comment]
Hi @elukey , did you try to follow the quoted commands and re-install your ROCm environment from clean? That should hopefully resolve your issue #1. 
Issue #2 is as expected -- changes of HIP from ROCm2.5 and ROCm2.6 broke the TF WHL compatibility; please try to stick with the following combination for bare metal deployment:
ROCm 2.5 + TF1.13.3
ROCm 2.6 + TF1.13.4/TF1.14.0/TF2.0.0b1
There are no material changes in TF between TF1.13.3 and TF1.13.4.

**Comment by sunway513** [comment]
@elukey , if you still see issues, please help provide the logs from the following command:
`apt --installed list | grep -E 'hip|hcc|roc|miopen|amdgpu|hsa'`

**Comment by elukey** [comment]
@sunway513, thanks for following up. Some comments:

Issue 1: Will retry to deploy rocm 2.6 and provide feedback. Is there anything else besides package lists that I can provide/check to debug why tensorflow hangs? 
Issue 2: The fact that the breakage is expected is not really great, tensorflow-rocm should keep some ABI compatibility with previous versions whenever possible. It is not great that moving from a patch version to another (1.13.3 -> 1.13.4) or from a minor to minor (1.13.3 -> 1.14.0) breaks ABI compatibility. In this case ROCm 2.6 seems to cause issues with my GPU (to be rechecked again), and I am stuck with tensorflow-rocm 1.13.3 without any possibility to use newer versions from pypi. Is there a place where the compatibility list that you outlined is written/updated? Some notes in https://pypi.org/project/tensorflow-rocm/ would be great..

**Comment by sunway513** [comment]
Hi @elukey , for issue 1, if you look at the failure log below:
`ImportError: /srv/home/elukey/test/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN8hip_impl7kernarg6resizeEm`
It shows the tensorflow shared library is not compatible with the HIP runtime library that currently installed on your system. If you want to upgrade to ROCm2.6, please do follow the instructions I've provided in the previous comments so you can install from a clean system.

For compatibility information, please refer to our release document:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/RELEASE.md#release-1134
Please note ROCm toolchain and user-bit environment doesn't guarantee backward compatibility, which means the binaries compiled with ROCm2.5 toolchain might not work with ROCm2.6 runtime. TF-ROCm project has to follow the same guideline when deciding if we would release updated whl packages along with ROCm release. 
Frankly, the best option to avoid such environment configuration issues is to go with Docker-based deployment.

**Comment by elukey** [comment]
Hi @sunway513, good news: after starting from a clean state as you indicated, tf-rocm 1.14.0 seems to work with basic tests on ROCm 2.6. I'll do more test and report back, but so far everything looks good.

I have also updated all my notes about deploying new versions and testing them (available to everybody interested in running ROCm on Debian at https://wikitech.wikimedia.org/wiki/Analytics/Systems/Cluster/AMD_GPU).

**Comment by sunway513** [comment]
Hi @elukey , thank you for the updates.
The document on wikimedia looks very helpful! Please consider submitting PRs if you have any suggestions for us to improve on the document, we very appreciate contributions from the community. 
I'm going to close this ticket, for now, feel free to re-open it if you have further questions.
