### ISSUE TITLE
ROCm version of TF for higher-level libraries that use TF?

### ISSUE THREAD

**Issue by juliuskittler** [ROCmSoftwarePlatform/tensorflow-upstream#563]
My question is, whether I can use the ROCm Version of TF with an AMD GPU for libraries that are based on TF (and also support the GPU version if it), such as:

- TensorLayer (https://github.com/tensorlayer/tensorlayer)
- Dopamine (https://github.com/google/dopamine)
- TFlearn (https://github.com/tflearn/tflearn)
- OpenAI Gym (https://github.com/openai/gym)

My concern is that these libraries that are build on or use TF won't support the ROCm Version of Tensorflow. Unfortunately, I have not found any experience reports of people using AMD GPUs with the above mentioned libraries. I am currently evaluating whether I should get an AMD or Nvidia GPU. As of right now, I am still very skeptical about the AMD option. In any case, thanks a lot for your reply in advance.

**Comment by sunway513** [comment]
Hi @juliuskittler , I've taken a brief look at the four projects you've referred, those all built on top of the tensorflow stack, and deployed tensorflow using `pip install` - that said, those are essentially tensorflow applications. 
Given the experiences we've had with various TF models and applications, I'd assume those might work. Feel free to pull our team members in those project repositories, if anything we can help clarify there.

**Comment by juliuskittler** [comment]
@sunway513, thank you for getting back to me. Can you give examples of libraries that use TF, where the ROCm TF version (with GPU) worked well? Overall, I think it would be very helpful if there were some experience/test reports made available (by AMD or third parties). If the above listed libraries really do work well with the ROCm TF version (with GPU), this will get more people to seriously consider buying an AMD Graphics card. (Ultimately, people in the ML community do want AMD to be able to compete with Nvidia.) As of right now, I am still not sure if I can get these libraries to work on an AMD graphics card with the ROCm TF version (with GPU) and I don't want to risk being unable to use the libraries that I will use the most.
