### ISSUE TITLE
Eager execution should be enabled by default for TensorFlow 2.0

### ISSUE THREAD

**Issue by jdoe0** [ROCmSoftwarePlatform/tensorflow-upstream#564]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu GNU/Linux 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): merge-190422-3300-g95338be 2.0.0-beta1
- Python version: 3.6.5
- ROCm/MIOpen version: 2.6.22
- GPU model and memory: Vega64 8GB

**Describe the current behavior**
Eager execution is not enabled by default.

**Describe the expected behavior**
Eager execution should be enabled by default as does upstream.

**Code to reproduce the issue**
```
import tensorflow as tf
print(tf.executing_eagerly())
```
With upstream `tensorflow`, the output will be `True`. With `tensorflow-rocm`, the output will be `False`.

**Comment by witeko** [comment]
seems like it hasnt been build for V2 (build_rocm_v2).

**Comment by sunway513** [comment]
Hi @jdoe0 , thank you for reporting this issue. 
We'll review the Jenkins builds and update the whl packages built with r2.0.0-beta1-v2 option.
In the meanwhile, you can use our docker container:
rocm/tensorflow:rocm2.6-tf2.0-beta1-config-v2

**Comment by sunway513** [comment]
Hi @jdoe0 and @witeko  could you help review the following whl package?
`pip3 install tensorflow-rocm==2.0.0b2 `

**Comment by witeko** [comment]
@jdoe0, @sunway513, works fine for me. :)

**Comment by sunway513** [comment]
Thank you @witeko , will submit a patch to update the doc.
