### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by robzor92** [ROCmSoftwarePlatform/tensorflow-upstream#567]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary pip
- TensorFlow version (use command below): 1.14
- Python version: 2.7 and 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: ROCm 2.6 / MiOpen 2.0
- GPU model and memory: AMD Radeon VII

**Describe the current behavior**

I installed ROCm 2.6 on CentOS 7.5 and tensorflow-rocm in an Anaconda environment. Then I tried to import tensorflow-rocm 1.14 which resulted in:

> ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

as far as I understand the last supported glibc version for CentOS 7 is 2.17 as indicated here:
1. https://www.centos.org/forums/viewtopic.php?t=68406
2. https://centos.pkgs.org/7/centos-x86_64/glibc-2.17-260.el7.x86_64.rpm.html

I did not have this problem importing tensorflow-gpu, which leads me to think this is a tensorflow-rocm specific problem as both rely on native libraries.

**Describe the expected behavior**

It should import tensorflow-rocm correctly on CentOS 7.5 using latest glibc available for CentOS 7.

**Code to reproduce the issue**

import tensorflow

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

**Comment by sunway513** [comment]
Hi @robzor92 , could you refer to this [comment ](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/522#issuecomment-506886220)from issue #522 ?

**Comment by robzor92** [comment]
Thanks @sunway513
