### ISSUE TITLE
Centos 7.6 Radeon VII - X470 - Ryzen 2600x - Latest Tensorflow Build

### ISSUE THREAD

**Issue by aristeidist** [ROCmSoftwarePlatform/tensorflow-upstream#593]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Centos 7.6
- Downloaded Tensorflow.org
- TensorFlow version: hopefully 2.0.0b1
- Python version: 2.7 & 3.6
- Bazel version: latest
- GCC/Compiler version: as specified
- ROCm/MIOpen version: 2.6 (Latest as of writing)
- GPU model and memory: 2xRadeon VII 16GB
- Ryzen 7 2600x | X470 board |16GB  DDR4 | 

ROCm utils all report proper operation.

Basically, my question is this:

Trying to figure out a way to build Tensorflow source code (the latest one 2.0.0b1) natively on my machine (don't want to use Docker) as the Ubuntu binaries present a Glibc error (i.e they're not compatible).

Obviously, the 1.14 version (On this git) would probably work (haven't tested) but would like to know if there's any guide or way to do this, again I'm keen on using the latest beta version of Tensorflow.

I've checked on 

a) https://hub.docker.com/r/rocm/tensorflow-autobuilds
and 
b) https://www.tensorflow.org/install/source

But have been unsuccessful so far with: 
a) either timing out when downloading certain things or finishing with a python error after all 30 steps are completed (docker settings where correct) plus I don't know exactly if this method produces a .whl to use natively on my machine or if that would be just an Ubuntu docker.

Here are the results (from an apparently succesful build??)

> Step 27/30 : RUN /install/install_bazel.sh
>  ---> Running in b08afafcf9a9
> Bazel installer
> ---------------
> 
> Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
> You can find the sources next to the installer on our release page:
>    https://github.com/bazelbuild/bazel/releases
> 
> # Release 0.24.1 (2019-04-02)
> 
> Baseline: 235e76b0e756d05599a6cbe1663ff8e13df84a86
> 
> Cherry picks:
> 
>    + badd82e4c5cda7b3232481e1c63a5550ac898cd8:
>      Automated rollback of commit
>      1b4c37c38804559b5c1ade6f9c93501875e231b0.
>    + 33e571939085dd158422e1b3503cfc738e0a3165:
>      Fix the Python version select() mechanism to handle
>      PY3-as-default
>    + 56366ee3a73e2c92b2fa36a9840478202b9618ca:
>      Set non-empty values for msvc_env_* when VC not installed
>    + 22b3fbf4800113df51d603d943bd9eb9517ef904:
>      Windows, test wrapper: fix broken integration test
>    + f14d447cb56aee563f6e686b8f5b086a3bb55d47:
>      Add whitelist file for starlark transitions
>    + d99bc478db1f3414b4f6cd3dc14ca70aacf6b375:
>      Update BUILD
>    + 3529ad7ccf0c26dfb20a9d67b9d96de15f309f8b:
>      Rename tools/function_transition_whitelist/BUILD to
>      tools/whitelists/function_transition_whitelist/BUILD
>    + de0612ad3ef7cc8c44069261befdeb0d15b97c10:
>      Update bazel_toolchains to latest release and add toolchain
>      config target for BuildKite CI (rbe_ubuntu1604)
>    + 3e660ad178926648e8e10e2ee7a1a30b12f9b3d1:
>      Automated rollback of commit
>      087734009801242b83655efb863b2d5a761ae3dc.
>    + 314cf1f9e4b332955c4800b2451db4e926c3e092:
>      Pass -undefined dynamic_lookup to dynamic library linking
>      actions on Mac
>    + fc586a86b614667a21e5a01aea3544ac0338de78:
>      Move cc_flags target into @bazel_tools//tools/cpp.
>    + ea1703b30f9ac43a0c3262f5729c34658ed8d473:
>      C++: Fix crash reported in #7721
>    + 803801d1494f06f0ce977a1f2241ef6a4d85df09:
>      Pass execution info to xml generating spawn. Fixes #7794
>    + f092ec388a4b58788285b928c86f0f81561d4be4:
>      Release 0.24.0 (2019-03-26)
>    + c56c489119e6587975964c44ceb9e429ad950736:
>      Wrap StatusRuntimeExceptions from GrpcRemoteCache
> 
> Baseline: f092ec388a4b58788285b928c86f0f81561d4be4
> 
> Cherrypicks:
> + c56c489119e6587975964c44ceb9e429ad950736: Wrap StatusRuntimeExceptions from GrpcRemoteCache
> 
> ## Build information
>    - [Commit](https://github.com/bazelbuild/bazel/commit/e2e243e)
> Uncompressing.......
> 
> Bazel is now installed!
> 
> Make sure you have "/usr/local/bin" in your path. You can also activate bash
> completion by adding the following line to your ~/.bashrc:
>   source /usr/local/lib/bazel/bin/bazel-complete.bash
> 
> See http://bazel.build/docs/getting-started.html to start a new project!
> Removing intermediate container b08afafcf9a9
>  ---> d451fbfea917
> Step 28/30 : RUN /install/install_golang.sh
>  ---> Running in cf7e5a177874
> + GOLANG_URL=https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz
> + sudo mkdir -p /usr/local
> + wget -q -O - https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz
> + sudo tar -C /usr/local -xz
> Removing intermediate container cf7e5a177874
>  ---> 559c23b881ae
> Step 29/30 : COPY install/.bazelrc /etc/bazel.bazelrc
>  ---> c072ab3cc4ad
> Step 30/30 : ENV TF_NEED_ROCM 1
>  ---> Running in 9ed7a7607e38
> Removing intermediate container 9ed7a7607e38
>  ---> 7a894aea77a9
> Successfully built 7a894aea77a9
> Successfully tagged tf-tensorflow-rocm:latest
> + docker run --rm --pid=host -v /home/tensorflow/tensorflow/tools/ci_build/linux/../../../../:/workspace -w /workspace -e PYTHON_BIN_PATH=/usr/bin/python -e TF_NEED_HDFS=0 -e TF_NEED_CUDA= -e TF_NEED_TENSORRT= -e TF_NEED_ROCM=1 -e TF_NEED_OPENCL_SYCL=0 tf-tensorflow-rocm /workspace/tensorflow/tools/ci_build/linux/libtensorflow.sh
> +++ dirname /workspace/tensorflow/tools/ci_build/linux/libtensorflow.sh
> ++ cd /workspace/tensorflow/tools/ci_build/linux
> ++ pwd
> + SCRIPT_DIR=/workspace/tensorflow/tools/ci_build/linux
> + source /workspace/tensorflow/tools/ci_build/linux/../builds/libtensorflow.sh
> + SUFFIX=-cpu-linux-
> + '[' '' == 1 ']'
> + '[' 1 == 1 ']'
> + SUFFIX=-rocm-linux-
> ++ uname -m
> + build_libtensorflow_tarball -rocm-linux-x86_64
> + '[' '!' -e WORKSPACE ']'
> + DIR=lib_package
> + rm -rf lib_package
> + TARBALL_SUFFIX=-rocm-linux-x86_64
> + BAZEL_OPTS='--config=opt --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0'
> + export 'CC_OPT_FLAGS=-mavx -msse4.2'
> + CC_OPT_FLAGS='-mavx -msse4.2'
> + '[' '' == 1 ']'
> + bazel clean --expunge
> Extracting Bazel installation...
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=0 --terminal_columns=80
> INFO: Reading rc options for 'clean' from /etc/bazel.bazelrc:
>   Inherited 'common' options: --color=yes
> INFO: Reading rc options for 'clean' from /etc/bazel.bazelrc:
>   Inherited 'build' options: --verbose_failures --spawn_strategy=standalone --strategy=Genrule=standalone
> INFO: Reading rc options for 'clean' from /workspace/.bazelrc:
>   Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
> INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
> + yes ''
> + ./configure
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> You have bazel 0.24.1 installed.
> Found possible Python library paths:
>   /usr/local/lib/python2.7/dist-packages
>   /usr/lib/python2.7/dist-packages
> Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
> Do you wish to build TensorFlow with XLA JIT support? [Y/n]: XLA JIT support will be enabled for TensorFlow.
> 
> Traceback (most recent call last):
>   File "./configure.py", line 1602, in <module>
>     main()
>   File "./configure.py", line 1459, in main
>     int(get_var(environ_cp, 'TF_NEED_CUDA', 'CUDA', False)))
>   File "./configure.py", line 347, in get_var
>     (var_name, ', '.join(true_strings), ', '.join(false_strings), var))
> __main__.UserInputError: Environment variable TF_NEED_CUDA must be set as a boolean indicator.
> The following are accepted as TRUE : 1, t, true, y, yes.
> The following are accepted as FALSE: 0, f, false, n, no.
> Current value is .

This is what I see on docker now:

> 
> # docker image ls
> REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
> tf-tensorflow-rocm   latest              7a894aea77a9        23 minutes ago      5.2GB
> ubuntu               xenial              5e13f8dd4c1a        11 days ago         120MB

Can I do anything with this?

and 
b) Well, this one I don't know what to do exactly - Followed some Bazel build guides there, but these didn't work, plus not sure how to set it up for a ROCm build, and not sure which bazel switch(??) would do that.

Any help or ideas would be immensely appreciated. 

Thank you!

**Comment by aristeidist** [comment]
Some updates.

I was able to get past some issues and start the build - Some due to my lack of understanding of numerous items.

First off, the WORKSPACE needs updating (after the first line) with this :


```
# Download the rules_docker repository at release v0.9.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "e513c0ac6534810eb7a14bf025a0f159726753f97f74ab7863c650d26e01d677",
    strip_prefix = "rules_docker-0.9.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.9.0.tar.gz"],
)
```

Taken from here: [](https://github.com/bazelbuild/rules_docker)

Tried building from Tensorflow.org main git.

Also tried building from here I get the same error:

> 
> ERROR: /home/tensorflow-upstream/tensorflow/stream_executor/rocm/BUILD:158:1: C++ compilation of rule '//tensorflow/stream_executor/rocm:rocblas_plugin' failed (Exit 1)
> In file included from bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas-types.h:16:0,
>                  from bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas.h:19,
>                  from tensorflow/stream_executor/rocm/rocm_blas.cc:16:
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:15: error: 'is_trivially_copyable' is not a member of 'std'
>  static_assert(std::is_trivially_copyable<rocblas_bfloat16>{},
>                ^
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:58: error: expected primary-expression before '>' token
>  static_assert(std::is_trivially_copyable<rocblas_bfloat16>{},
>                                                           ^
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:59: error: expected primary-expression before '{' token
>  static_assert(std::is_trivially_copyable<rocblas_bfloat16>{},
>                                                            ^
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:59: error: expected ',' before '{' token
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:59: error: expected string-literal before '{' token
> bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocblas_bfloat16.h:126:59: error: expected ')' before '{' token
> tensorflow/stream_executor/rocm/rocm_blas.cc: In function 'rocblas_operation stream_executor::gpu::{anonymous}::ROCMBlasTranspose(stream_executor::blas::Transpose)':
> tensorflow/stream_executor/rocm/rocm_blas.cc:363:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> tensorflow/stream_executor/rocm/rocm_blas.cc: In function 'rocblas_fill stream_executor::gpu::{anonymous}::ROCMBlasUpperLower(stream_executor::blas::UpperLower)':
> tensorflow/stream_executor/rocm/rocm_blas.cc:374:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> tensorflow/stream_executor/rocm/rocm_blas.cc: In function 'rocblas_diagonal stream_executor::gpu::{anonymous}::ROCMBlasDiagonal(stream_executor::blas::Diagonal)':
> tensorflow/stream_executor/rocm/rocm_blas.cc:385:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> tensorflow/stream_executor/rocm/rocm_blas.cc: In function 'rocblas_side stream_executor::gpu::{anonymous}::ROCMBlasSide(stream_executor::blas::Side)':
> tensorflow/stream_executor/rocm/rocm_blas.cc:396:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
Any Ideas?

**Comment by sunway513** [comment]
Hi @aristeidist , can you refer to the following comment wrt TF-ROCm support for CentOS?
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/522#issuecomment-506886220
