### ISSUE TITLE
Doesn't work on Ubuntu 19.04 Disco anymore, but it did before......

### ISSUE THREAD

**Issue by vegabook** [ROCmSoftwarePlatform/tensorflow-upstream#599]
Upgraded to rocm 2.6:

```
tbrowne@KubuntuK5:~$ apt show rocm-libs -a
Package: rocm-libs
Version: 2.6.22
.....
```

Everything fine with Rocm:
```
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 2700X Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB         
...
```
Including my Radeon VII:

```
*******                  
Agent 2                  
*******                  
  Name:                    gfx906                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26287                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1802                               
  BDFID:                   2816                               
  Compute Unit:            60                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE        
...
```

So was on 1.13 tensorflow-rocm and decided to upgrade to 1.14. 

Pip installed tensorflow-rocm as per instructions. Then got the expected librccl.so error tracked here:

https://stackoverflow.com/questions/57042429/deep-learning-with-python-using-tensorflow-and-keras-on-amd-gpu-with-rocm-gives

But when following the answer: 

```
sudo apt-get update && sudo apt-get install -y --allow-unauthenticated  rocm-dkms rocm-dev rocm-libs rccl rocm-device-libs hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev rocm-opencl rocm-opencl-dev   rocm-utils  rocm-profiler cxlactivitylogger miopen-hip miopengemm
```

I get a segfault. Admittedly this is Ubuntu 19.04 not the "official" 18.04 support, but 19.04 was working fine the last time I checked it a few weeks ago. But a "apt-get update" or two happend since then and now this. I've tried it also on a brand new install of 19.04 and exactly the same behaviour. 

```
tbrowne@KubuntuK5:~$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'

Segmentation fault (core dumped)
```

This was working 100% fine before as can be seen on this asciinema, and that was also on Ubuntu 19.04 "Disco":

https://asciinema.org/a/5huTdTTaRDqQqdjfPwcdGdI6A

**Comment by sunway513** [comment]
Hi @vegabook , is using docker container an option to you?
ROCm doesn't officially support UB19.04.

**Comment by vegabook** [comment]
Personally find Docker clunky and inelegant as a solution but of course it is a fallback option. 

Look I know it doesn't support 19.04 officially but I guess I was hoping there was an easy fix, since it was working fine with a combination of Tensorflow 1.13 and Rocm 2.4.x on Disco. If not then don't worry and please feel free to close the issue but let's be honest 18.04 is now almost 1.5 years old so it's getting a bit long in the tooth. Thanks for attention anyway and thank you for all the hard work getting AMD competitive again especially with such a great card as Vega VII

**Comment by sunway513** [comment]
Hi @vegabook , thanks for the comment, TF-ROCm would work okay for Ubuntu18.04 user bit environment. It would be difficult for us to comment on the status of TF-ROCm for Ubuntu19.04, as those not part of any coverage we have had.
I'll close this issue for now, we can revisit this issue when Ubuntu19.04 is part of ROCm support list.
