### ISSUE TITLE
ROCM2.5 build tensorlfow failed

### ISSUE THREAD

**Issue by XuanBaby** [ROCmSoftwarePlatform/tensorflow-upstream#600]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):CentOS Linux release 7.4.1708 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:r1.13-rocm-centos
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.21
- GCC/Compiler version (if compiling from source):7.3.1
- ROCm/MIOpen version:2.5
- GPU model and memory:gfx906

**Describe the problem**
when I build tensorflow1.13 on rocm2.5 ,it make some error，could you give me some advice about how to solve it 
Can't exec "g++": No such file or directory at /opt/rocm/bin/hipcc line 243.
Use of uninitialized value $GPP_CUR_VER in substitution (s///) at /opt/rocm/bin/hipcc line 245.
Use of uninitialized value $GPP_CUR_VER in split at /opt/rocm/bin/hipcc line 247.
Use of uninitialized value $GPP_CUR_VER in string eq at /opt/rocm/bin/hipcc line 252.
ld: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/crtbeginS.o: unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
hcc: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: /home/tensorflow-upstream-r1.13-rocm-centos/tensorflow/python/BUILD:5919:1: output 'tensorflow/python/framework/fast_tensor_util.so' was not created
ERROR: /home/tensorflow-upstream-r1.13-rocm-centos/tensorflow/python/BUILD:5919:1: not all outputs were created or valid

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1、scl enable sevtoolset-7 bash
2、./build_rocm_python3

**Any other info / logs**
SUBCOMMAND: # @aws//:aws [action 'Compiling external/aws/aws-cpp-sdk-s3/source/model/PutBucketNotificationConfigurationRequest.cpp [for host]']
(cd /root/.cache/bazel/_bazel_root/7a57ed89673debedf9020bafdda56412/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections
 -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/external/aws/_objs/aws/PutBucketNotificationConfigurationRequest.pic.d '-frandom-seed=bazel-out/host/bin/external/aws/_objs/aws/PutBucketNotificationConfigurationRequest.pic.o' -fPIC -DCURL_STATICLIB -DPLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_NO_ENCRYPTION -iquote external/aws -iquote bazel-out/host/genfiles/external/aws -iquote bazel-out/host/bin/external/aws -iquote external/curl -iquote bazel-out/host/genfiles/external/curl -iquote bazel-out/host/bin/external/curl -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/boringssl -iquote bazel-out/host/genfiles/external/boringssl -iquote bazel-out/host/bin/external/boringssl -isystem external/aws/aws-cpp-sdk-core/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-core/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-core/include -isystem external/aws/aws-cpp-sdk-kinesis/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-kinesis/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-kinesis/include -isystem external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-s3/include -isystem external/curl/include -isystem bazel-out/host/genfiles/external/curl/include -isystem bazel-out/host/bin/external/curl/include -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/boringssl/src/include -isystem bazel-out/host/genfiles/external/boringssl/src/include -isystem bazel-out/host/bin/external/boringssl/src/include -g0 '-march=haswell' -g0 -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c external/aws/aws-cpp-sdk-s3/source/model/PutBucketNotificationConfigurationRequest.cpp -o bazel-out/host/bin/external/aws/_objs/aws/PutBucketNotificationConfigurationRequest.pic.o)INFO: From Linking tensorflow/python/framework/fast_tensor_util.so [for host]:
Can't exec "g++": No such file or directory at /opt/rocm/bin/hipcc line 243.
Use of uninitialized value $GPP_CUR_VER in substitution (s///) at /opt/rocm/bin/hipcc line 245.
Use of uninitialized value $GPP_CUR_VER in split at /opt/rocm/bin/hipcc line 247.
Use of uninitialized value $GPP_CUR_VER in string eq at /opt/rocm/bin/hipcc line 252.
ld: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/crtbeginS.o: unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
hcc: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: /home/tensorflow-upstream-r1.13-rocm-centos/tensorflow/python/BUILD:5919:1: output 'tensorflow/python/framework/fast_tensor_util.so' was not created
ERROR: /home/tensorflow-upstream-r1.13-rocm-centos/tensorflow/python/BUILD:5919:1: not all outputs were created or valid
SUBCOMMAND: # @aws//:aws [action 'Compiling external/aws/aws-cpp-sdk-kinesis/source/KinesisEndpoint.cpp [for host]']
(cd /root/.cache/bazel/_bazel_root/7a57ed89673debedf9020bafdda56412/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections
 -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/external/aws/_objs/aws/KinesisEndpoint.pic.d '-frandom-seed=bazel-out/host/bin/external/aws/_objs/aws/KinesisEndpoint.pic.o' -fPIC -DCURL_STATICLIB -DPLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_NO_ENCRYPTION -iquote external/aws -iquote bazel-out/host/genfiles/external/aws -iquote bazel-out/host/bin/external/aws -iquote external/curl -iquote bazel-out/host/genfiles/external/curl -iquote bazel-out/host/bin/external/curl -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/boringssl -iquote bazel-out/host/genfiles/external/boringssl -iquote bazel-out/host/bin/external/boringssl -isystem external/aws/aws-cpp-sdk-core/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-core/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-core/include -isystem external/aws/aws-cpp-sdk-kinesis/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-kinesis/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-kinesis/include -isystem external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/host/genfiles/external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/host/bin/external/aws/aws-cpp-sdk-s3/include -isystem external/curl/include -isystem bazel-out/host/genfiles/external/curl/include -isystem bazel-out/host/bin/external/curl/include -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/boringssl/src/include -isystem bazel-out/host/genfiles/external/boringssl/src/include -isystem bazel-out/host/bin/external/boringssl/src/include -g0 '-march=haswell' -g0 -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c external/aws/aws-cpp-sdk-kinesis/source/KinesisEndpoint.cpp -o bazel-out/host/bin/external/aws/_objs/aws/KinesisEndpoint.pic.o)Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 27.182s, Critical Path: 16.52s
INFO: 702 processes: 702 local.
FAILED: Build did NOT complete successfully

**Comment by sunway513** [comment]
Hi @XuanBaby , please refer to the following comment to your last issue:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/581#issuecomment-516235480
