### ISSUE TITLE
Convergence problems with vega7 and tensorflow 1.14/2.0

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#602]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 (kernel 4.18)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): always binary
- TensorFlow version (use command below): 1.14 and 2.0
- Python version: 3.6
- ROCm/MIOpen version: 2.6/2.7
- GPU model and memory: 2 x vega7

**Describe the current behavior**
I am aware that from a "developer point o view" this is a "bad" issue report because I have no easy way to show the code and data I'm using atm (big dataset 50gb+, lots of pre-transformations, ...), but I think that You should look into some simple but serious bugs.
Im using CNN (densenet121) with some additions.

My experience:

On tf 1.13 and rocm 2.6 most things work properly.
But on 1.14 and 2.0 the same NNs that behave correctly in 1.13 show increasing validation results like val_loss (where they should be decreasing), results of training validations seem to be very similar to the ones observed in 1.13 though. Maybe this is a similar issue to #449 (im not sure).

Issues that cause NNs not to converge are very serious imho.

**Comment by witeko** [comment]
OK, so I pinpointed the bug a little bit, it only occurs when using "features.trainable=False" where feauters=Densenet121. When "features.trainable=True" validation results seem to be correct.
Do You think it's a rocm-related bug or pure tensorflow's?

**Comment by sunway513** [comment]
Hi @witeko , can you first try the following two docker containers? 
Those would confirm if the issue you are observing is related to ROCm regressions or not:
Docker container 1: 
rocm/tensorflow-autobuilds:rocm2.6-596cf5d
Docker container 2:
rocm/tensorflow-autobuilds:rocm2.7-0ac93cf

**Comment by witeko** [comment]
@sunway513 I can 100% confirm that the problem exists on both rocm versions (I encountered it before even upgrade to 2.7 was available) - I just didnt know that the numbers were wrong... maybe it's a pure tensorflow bug? Later on I can check on pure cpu-tensorflow.

**Comment by witeko** [comment]
@sunway513 excluding the bug, my experience with tf-rocm2.0 is much better comparing to 1.13. It works much faster and I'm able to use bigger batches (before I go oom).

**Comment by witeko** [comment]
![tensorbug](https://user-images.githubusercontent.com/34566457/63200184-99c9d900-c080-11e9-8ca8-44f2aa058c51.png)

**Comment by witeko** [comment]
@sunway513 
also not reshaping input (for validation) images makes the val statistics go crazy.
i prepare my data like this:
def parse_image_function(example_proto):
    image=tf.io.parse_single_example(example_proto, features)
    img=tf.image.decode_png(image['image'], channels=3, dtype=tf.dtypes.uint8)
    s=image['output']
    
    img=tf.image.resize(img,[512,512]) <--without this line my val_loss and val_acc go crazy bad, but the optimizer itself seems to do its work properly.
    img=tf.image.random_crop(img,[base,base,6])
    
    img=tf.image.convert_image_dtype(img,dtype=tf.dtypes.float32,saturate=False,name=None) #costly
    img = img/255.0
    
    return ({'input': img}, {'out':tf.cast(s,tf.uint16)})

**Comment by sunway513** [comment]
Thanks @witeko , have you been able to confirm if this issue is specific to TF-ROCm or generic to TF even with CPU?
If you believe it's a legitimate issue for TF-ROCm, we'd need the exact steps to repro the issue, thanks :-)

**Comment by sunway513** [comment]
gentle ping @witeko

**Comment by witeko** [comment]
@sunway513 ok, i will try to check it on my cpu.

**Comment by witeko** [comment]
@sunway513 looks like the same bug is also on CPU: I used tf-rocm2.0b3 with os.environ["HIP_VISIBLE_DEVICES"]=""

**Comment by sunway513** [comment]
Thanks @witeko  to confirm this issue is not specific to TF-ROCm.
Can we move to the upstream TF repo for this issue?
