### ISSUE TITLE
tensorpack FasterRCNN failed with DeadlineExceededError

### ISSUE THREAD

**Issue by materia9** [ROCmSoftwarePlatform/tensorflow-upstream#607]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I use tensorpack 0.9.7
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (4.15.0-58-generic)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): via the docker image rocm/tensorflow:rocm2.7-tf1.14-dev 
- TensorFlow version (use command below): 1.14.1
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: miopen-hip/now 2.0.1.7405-rocm-rel-2.7-22-4e39a83
- GPU model and memory: Radeon VII 16GB

**Describe the current behavior**
tensorpack FasterRCNN training failed with DeadlineExceededError during the auto-tuning. 

**Describe the expected behavior**
No fail during training.

**Code to reproduce the issue**

In the tensorpack/examples/FasterRCNN/, run

python3 train.py --config DATA.BASEDIR=/path/to/your/coco/data TRAIN.STEPS_PER_EPOCH=5 TRAIN.EVAL_PERIOD=3

**Other info / logs**

A part of the error log is here
[log.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3514393/log.txt)

Before installing rocm 2.7, I have been struggling with rocm2.6 and tensorpack FasterRCNN, and I ended up without success.

**Comment by sunway513** [comment]
Hi @materia9 , I was able to reproduce the issue, however, the failure seems a result of the following error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/prof.py", line 108, in worker
    with NVMLContext() as ctx:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/nvml.py", line 163, in __enter__
    _NVML.load()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/nvml.py", line 63, in load
    self._nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```
With the above log I don't think tensorpack is compatible with ROCm yet.
Please create your issue on tensorpack repository instead, and let us know if anything we can help with there.

**Comment by materia9** [comment]
Thank you for the analysis. I did not understand the OSError well. And now I believe it is not a fatal error (failure of monitoring things). I upgraded my tensorpack package to the latest one (commit 1870496 on Aug 18, 2019), and the error was changed; there was no DeadlineExceededError but there were the OSError and another error (NotFoundError). Commenting out of train.py L91-L94 and L102-L103 can remove the OSError, but I still have the NotFoundError. Is this a compatibility issue of the tensorpack on the rocm?

train.py L90-L104 after modification to remove the OSError

>         ScheduledHyperParamSetter('learning_rate', lr_schedule),
>         #GPUMemoryTracker(),
>         #HostMemoryTracker(),
>         #ThroughputTracker(samples_per_step=cfg.TRAIN.NUM_GPUS),
>         #EstimatedTimeLeft(median=True),
>         SessionRunTimeout(60000),   # 1 minute timeout
>     ]
>     if cfg.TRAIN.EVAL_PERIOD > 0:
>         callbacks.extend([
>             EvalCallback(dataset, *MODEL.get_inference_tensor_names(), args.logdir)
>             for dataset in cfg.DATA.VAL
>         ])
>     #if not is_horovod:
>     #    callbacks.append(GPUUtilizationTracker())
> 

And a part of the error log is

> W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue:
> Skipping cancelled enqueue attempt with queue not closed
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1356, in _
> do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1341, in _
> run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)                                        File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1429, in _
> call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.NotFoundError: Failed to find backward filter algorithm!
>          [[{{node tower0/gradients/tower0/group3/block2/conv2/Conv2D_grad/Conv2DBackpropFilter}}]]
