### ISSUE TITLE
TensorFlow 2.0.0-rc1

### ISSUE THREAD

**Issue by Bengt** [ROCmSoftwarePlatform/tensorflow-upstream#641]
The release candidate 1 of TensorFlow 2.0.0 has been tagged:

https://github.com/tensorflow/tensorflow/tree/v2.0.0-rc1

PyPI has packages for all the betas, but not this release candidate:

https://pypi.org/project/tensorflow-rocm/#history

Is there a package coming up?

**Comment by sunway513** [comment]
Hi @Bengt , yes, we're planning to publish the PyPi packages when ROCm2.8 is out. 
The package will be built using the following branch:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/tree/r2.0-rocm-rc1
You can build it from source if you want to try it earlier.

**Comment by Bengt** [comment]
Hi @sunway513, thanks for the pointer, I will give that branch a spin on ROCm 2.7.

**Comment by sunway513** [comment]
@Bengt , we have released the tensorflow-rocm 2.0.0 whl package, please try it out and let us know if you have any feedback. 
Thanks!

**Comment by Bengt** [comment]
Awesome! Thanks for the update. I will give that a spin next week.

Peng <notifications@github.com> schrieb am Fr., 11. Okt. 2019, 03:40:

**Comment by kinred** [comment]
@sunway513 Congrats! Could you give a hint with which ROCM version it was compiled with, always some guess work to do to get the pip and ROCM version right.

Yes, I know there are docker images :)

**Comment by witeko** [comment]
@sunway513 what is the branch/tag of the newly released whl? :)

**Comment by sunway513** [comment]
> @sunway513 Congrats! Could you give a hint with which ROCM version it was compiled with, always some guess work to do to get the pip and ROCM version right.
> 
> Yes, I know there are docker images :)
> 
> Ah, got it to work with ROCM 2.8!

Thanks! 
TF2.0.0 whl package was built with ROCm2.9 user bit, it might also work with ROCm2.8. 
I'm working on a document that specifies the ROCm compatibility against our released whl packages on PyPI, will keep you posted.

**Comment by sunway513** [comment]
@witeko , you can find the release tag here:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/releases/tag/v2.0.0-rocm

Please note the source code is pretty much identical to what we have been able to upstreamed to official tensorflow r2.0 release branch, other than minor cleanups to build with ROCm2.9 user bit packages:
https://github.com/tensorflow/tensorflow/commits/r2.0

**Comment by sunway513** [comment]
Hi @kinred , please refer to the following doc that specifies the tensorflow-rocm ROCm build version and the compatibility:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
