### ISSUE TITLE
TensorFlow ROCm stack smashing detected

### ISSUE THREAD

**Issue by WeiChunyu** [ROCmSoftwarePlatform/tensorflow-upstream#652]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System informat ion**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04 Linux version 4.15.0-64-generic (buildd@lgw01-amd64-038) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019

- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):TensorFlow-rocm==2.0.0b3
- Python version:3.6
- ROCm/MIOpen version:ROCm2.8, MIOpen2.1.0.7487-rocm-rel-2.8-13-a5a4129
- GPU model and memory:RX570 4GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
merge-190422-3306-g4d8fdbe 2.0.0-beta3

2019-09-30 17:26:47.559056: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

 dmesg | grep gpu
[   20.712614] [drm] amdgpu kernel modesetting enabled.
[   20.712615] [drm] amdgpu version: 5.0.79
[   20.912825] fb: switching to amdgpudrmfb from EFI VGA
[   20.912978] amdgpu 0000:09:00.0: enabling device (0006 -> 0007)
[   21.200915] amdgpu 0000:09:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[   21.200916] amdgpu 0000:09:00.0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF
[   21.201004] [drm] amdgpu: 4096M of VRAM memory ready
[   21.201006] [drm] amdgpu: 7991M of GTT memory ready.
[   21.201017] [drm] GART: num cpu pages 65536, num gpu pages 65536
[   21.515494] amdgpu: [powerplay] hwmgr_sw_init smu backed is polaris10_smu
[   22.125741] fbcon: amdgpudrmfb (fb0) is primary device
[   22.125838] amdgpu 0000:09:00.0: fb0: amdgpudrmfb frame buffer device
[   22.147189] [drm] Initialized amdgpu 3.34.0 20150101 for 0000:09:00.0 on minor 0

**Comment by twuebi** [comment]
Getting the same when running ELMo (https://github.com/allenai/bilm-tf/).

```
2019-09-30 17:22:51.188870: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

**Comment by sunway513** [comment]
Hi @WeiChunyu @twuebi , we have not yet pushed out compatible TF whl packages for ROCm2.8 environment, those will be available by the end of the week. We'll keep this thread updated, thanks.

**Comment by twuebi** [comment]
Would building the `r1.15-rocm` branch against 2.8 work?

**Comment by sunway513** [comment]
@twuebi  yes, that would work.

**Comment by sunway513** [comment]
@WeiChunyu  @twuebi  we have pushed ROCm2.8 compatible whl packages for TF1.14, please use the following option to upgrade, e.g. for python3
`pip3 install --user tensorflow-rocm --upgrade`
Make sure the TF version is 1.14.2:
`python3 -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 3`
