### ISSUE TITLE
(trivial issue) Error in last line of rocm_install script.

### ISSUE THREAD

**Issue by emerth** [ROCmSoftwarePlatform/tensorflow-upstream#656]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 19.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.14-rocm
- Python version: Python 2.7.16
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): Build label: 0.24.1
- GCC/Compiler version (if compiling from source): g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- ROCm/MIOpen version: 2.7.2
- GPU model and memory: 2080ti 11GB

**Describe the problem**

Pretty simple:

As of Sept 30 2019 build_rocm is building this:
 /tmp/tensorflow_pkg/tensorflow-1.14.2-cp27-cp27mu-linux_x86_64.whl, 

but it is attempting to install this:
/tmp/tensorflow_pkg/tensorflow-1.12.0rc0-cp27-cp27m-linux_x86_64.whl.

ie: the last line of build_rocm needs to be updated to install the TF 1.14 WHL not the 1.12 WHL.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Follow the exact instructions at https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-build-from-source.md.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Have a great day!

**Comment by sunway513** [comment]
Thank you @emerth for the heads up, will fix it and update here.

**Comment by sunway513** [comment]
Hi @emerth , the issue has been fixed in the following PR:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/657
Thank you for reporting the issue!
