### ISSUE TITLE
Error while importing tensorflow-rocm

### ISSUE THREAD

**Issue by limapedro** [ROCmSoftwarePlatform/tensorflow-upstream#669]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Hi, I followed the instructions to install rocm on Ubuntu 18.04 everythings seems to work fine, running  /opt/rocm/bin/rocm-smi outputs 

========================ROCm System Management Interface========================
================================================================================
WARNING: GPU[0]	: Unable to read /sys/class/drm/card0/device/gpu_busy_percent
GPU  Temp   AvgPwr  SCLK    MCLK     Fan    Perf  PwrCap  VRAM%  GPU%  
0    37.0c  N/A     300Mhz  1200Mhz  None%  auto  N/A     N/A    N/A   
================================================================================
==============================End of ROCm SMI Log ==============================

I trying to use Vega 11 on my Ryzen 3400G, I'm aware that I cannot run HIP, but I possibly could run opencl on this APU, my first step is to import tensorflow, but I got an error, this one:

Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Are there any guides on how to install Tensorflow for opencl?
I'll give updates with regards to this soon. meanwhile thank you guys for this project, it really is a great thing. Cheers!

**Comment by sunway513** [comment]
Hi @limapedro , tensorflow-rocm project depends on ROCm HIP toolchain - therefore if your platform can not run HIP applications, it would not support tensorflow-rocm project. 
Please consult with the following wiki for supported HWs for ROCm:
https://rocm.github.io/hardware.html
