### ISSUE TITLE
TF autotune enforce search

### ISSUE THREAD

**Issue by XuanBaby** [ROCmSoftwarePlatform/tensorflow-upstream#704]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.13.1
- Python version:3.6.8
- Bazel version (if compiling from source):0.19
- GCC/Compiler version (if compiling from source):7.2.1
- ROCm/MIOpen version:rocm2.8
- GPU model and memory:gfx906 16G

**Describe the current behavior**
![image](https://user-images.githubusercontent.com/29744738/68833430-65e96880-06ee-11ea-8cf9-5b6b4b781fee.png)
this code form https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/r1.13-rocm-centos/tensorflow/core/kernels/conv_grad_input_ops.cc#L1027
I want to know  how could I disable the force a research? In my code I add 
export MIOPEN_DEBUG_DISABLE_FIND_DB=1
export MIOPEN_USER_DB_PATH=/tmp/tensorflow 
I know MIOPEN_DEBUG_DISABLE_FIND_DB=1 will make performance lower,but it can solve the problem https://github.com/ROCmSoftwarePlatform/MIOpen/issues/124  
and  now I find the time of autu-tune is too long to complete a object-detection task (faster_rcnn-resnet50 network) training. so I want disable the force a research ,could you give me some advice? Thank you very much!

**Comment by sunway513** [comment]
Hi @XuanBaby , in the current tensorflow-rocm implementation there's no option to disable the namely "auto-tune" stage. During this stage, MIOpen would find the fast algorithm and call the OpenCL toolchain to compile the kernels whenever needed. 
Please note this is a "one-time" effort - after the MIOpen cache been generated, the second run of the workloads will be much faster in the "auto-tune" stage. 

Besides, we are working on the MIOpen intermedia mode integration, which will cut down the time spend to "get" the best algorithm. This feature is in planning to be part of Tensorflow-rocm 2.1 release.

**Comment by qixiang109** [comment]
> Hi @XuanBaby , in the current tensorflow-rocm implementation there's no option to disable the namely "auto-tune" stage. During this stage, MIOpen would find the fast algorithm and call the OpenCL toolchain to compile the kernels whenever needed.
> Please note this is a "one-time" effort - after the MIOpen cache been generated, the second run of the workloads will be much faster in the "auto-tune" stage.
> 
> Besides, we are working on the MIOpen intermedia mode integration, which will cut down the time spend to "get" the best algorithm. This feature is in planning to be part of Tensorflow-rocm 2.1 release.

Do you mean that in before Tensorflow-rocm 2.1, we must wait for the long run "auto-tune" stage before 1st batch running,  even if the model structure is only very、very slightly modified, even if a change in batch_size? does TF_ROCM_USE_IMMEDIATE_MODE=1 work in tensorflow-rocm 1.14 to enable immediate mode? To me, the forced find mode ruined my experience, you change the network or batch size a little, you can go out for a movie waiting for MIOpen finding.
