### ISSUE TITLE
have problem with tensorflow.keras.layers.LSTM

### ISSUE THREAD

**Issue by wellhowtosay** [ROCmSoftwarePlatform/tensorflow-upstream#706]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):v2.0.0-rc0-199-g0bd29e2 2.0.0
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version:2.9.6
- GPU model and memory:Radeon vii 16GB

met some bug when I was using keras.layers.LSTM 

> 2019-11-18 04:36:20.298226: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented
2019-11-18 04:36:20.298246: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unimplemented: createRnnDescriptor is unimplemented

I replace it with tf.compat.v1.keras.layers.LSTM or tf.keras.layers.RNN(LSTMCell), it worked fine ,except it was very slow,actually as slow as training on a CPU, and I deeply doubt that the program **was** running on CPU.

here is a comment on [https://tensorflow.google.cn/api_docs/python/tf/keras/layers/LSTM?hl=en](url)

> Based on available runtime hardware and constraints, this layer will choose different implementations (cuDNN-based or pure-TensorFlow) to maximize the performance. If a GPU is available and all the arguments to the layer meet the requirement of the CuDNN kernel (see below for details), the layer will use a fast cuDNN implementation.

**Code to reproduce the issue**
`import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(10, 16, mask_zero=True))
model.add(tf.keras.layers.LSTM(16, return_sequences=True, return_state=False, recurrent_dropout=0.1))
model.add(tf.keras.layers.Dense(10))

def gen():
    for i in range(10):
        yield ([i] * i, [i] * i)

ds = tf.data.Dataset.from_generator(
    gen, (tf.int64, tf.int64), (tf.TensorShape([None]), tf.TensorShape([None])))

ds = ds.padded_batch(
    batch_size=4,
    padded_shapes=tf.compat.v1.data.get_output_shapes(ds),
    drop_remainder=False
)

def crossentropy_loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

model.compile(optimizer='adam', loss=crossentropy_loss)
model.fit(ds, epochs=3)
`

**Other info / logs**

**Comment by sunway513** [comment]
Hi @wellhowtosay , I see you have been using 2.0.0RC0 whl package, can you try the latest releases inside the following docker container:
`rocm/tensorflow:rocm2.9-tf2.0.0-dev

**Comment by wellhowtosay** [comment]
> Hi @wellhowtosay , I see you have been using 2.0.0RC0 whl package, can you try the latest releases inside the following docker container:
> `rocm/tensorflow:rocm2.9-tf2.0.0-dev


> Hi @wellhowtosay , I see you have been using 2.0.0RC0 whl package, can you try the latest releases inside the following docker container:
> `rocm/tensorflow:rocm2.9-tf2.0.0-dev

thank you,I tried tensorflow.keras.layers.LSTM, and this time it works with no bug report. But,I didn't see any performance improvement. So I tried tf.compat.v1.keras.layers.CuDNNLSTM, and I received following exception
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 143, in model_iteration
    model, inputs, steps_per_epoch, epochs=epochs, steps_name=steps_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1650, in infer_steps_for_dataset
    size = K.get_value(cardinality.cardinality(dataset))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/backend.py", line 3164, in get_value
    return x.eval(session=get_session((x,)))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/backend.py", line 486, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/backend.py", line 903, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNV2' used by node cu_dnnlstm/CudnnRNNV2 (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [dropout=0, seed=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]

	 [[cu_dnnlstm/CudnnRNNV2]]

**Comment by sunway513** [comment]
@jerryyin , can you take a look here?

**Comment by jerryyin** [comment]
@wellhowtosay does the tf.test.is_gpu_available return False? If that's the case, then it means the GPU is not configured correctly. Also, the error message somehow indicating that the GPU device is not there: `Registered devices: [CPU, XLA_CPU]`.

**Comment by wellhowtosay** [comment]
@jerryyin tf.test.is_gpu_available returned Falses, and I ignored following error report

2019-12-03 14:01:23.802669: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
2019-12-03 14:01:23.803516: E tensorflow/stream_executor/rocm/rocm_driver.cc:1031] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2019-12-03 14:01:23.803534: E tensorflow/stream_executor/rocm/rocm_driver.cc:1031] could not retrieve ROCM device count: HIP_ERROR_NoDevice

**Comment by jerryyin** [comment]
@sunway513 Could you help point to resources to setup his GPU correctly? Based on the conversation this is not a problem of LSTM module.

**Comment by sunway513** [comment]
@wellhowtosay , were you able to execute the rocminfo in your environment?
`/opt/rocm/bin/rocminfo`
If not, please review the following ROCm document and make sure your ROCm software stack is properly configured:
https://github.com/RadeonOpenCompute/ROCm.git

For questions regarding ROCm configuration, please open an issue on the ROCm main repository.
