### ISSUE TITLE
Will AMD Radeon Pro 5500M be supported?

### ISSUE THREAD

**Issue by cyyeh** [ROCmSoftwarePlatform/tensorflow-upstream#718]
Since I didn't find AMD Radeon Pro 5500M, which is used by the latest Macbook Pro 16-inch in the hardware support list of ROCm, would it be supported in the near future?

**Comment by sunway513** [comment]
Hi @cyyeh , can you post your question on ROCm github main repo instead?
https://github.com/RadeonOpenCompute/ROCm
Please note we only take tensorflow-rocm specific issues in this forum, thank you for your understanding.
