### ISSUE TITLE
Cannot test GPU running on Tensorflow 2.0 on Radeon VII

### ISSUE THREAD

**Issue by quocdat32461997** [ROCmSoftwarePlatform/tensorflow-upstream#719]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: tensorflow-rocm 2.0.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 
- GPU model and memory:

**Problem Description**
I followed instructions to install Rocm and Tensorflow-Rocm. I tried to test if GPU is in use. However, when executing "tf.test.is_gpu_available() in Jupyter Notebook crashes. Error logs below. Attempt to build model but GPU not running only CPU. Please help.

print(tf.__version__) -> 2.0.0
tf.test.is_gpu_available()
2019-11-26 01:43:16.959390: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-11-26 01:43:16.982689: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2593725000 Hz
2019-11-26 01:43:16.983518: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x40d33d0 executing computations on platform Host. Devices:
2019-11-26 01:43:16.983546: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-26 01:43:16.983763: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

**Comment by sunway513** [comment]
Hi @quocdat32461997 , can you confirm the ROCm version been installed in your system?
If you are using ROCm2.10, we'll release the compatible packages for TF 1.14.4 and TF2.0.1 by end of the day today.

**Comment by quocdat32461997** [comment]
Rocm version is 2.10

rocm-libs -a
Package: rocm-libs
Version: 2.10.14
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 13.3 kB
Depends: rocfft, rocrand, rocblas, hipblas, rocsparse, hipsparse, rocalution, rocprim, rocthrust, hipcub
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 798 B
APT-Manual-Installed: yes
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack

**Comment by quocdat32461997** [comment]
Re-installed with ROCm version: 2.10.14. GPU is working well. 
However, bugs in #690 appears with tensorflow.keras.layers.LSTM.

**Comment by sunway513** [comment]
@quocdat32461997 , thanks for the update. 
The issue in #690 will be fixed in the coming TF2.1.0 release, we'll keep you posted. 
cc @jerryyin

**Comment by quocdat32461997** [comment]
Thanks
