### ISSUE TITLE
Is a Windows version of Tensorflow-ROCM planned for the future?

### ISSUE THREAD

**Issue by The-real-Han-Chen** [ROCmSoftwarePlatform/tensorflow-upstream#731]
I don't have access to Linux currently but I have a windows PC. I just wonder if a windows version of TF-rocm is planned in the future. Thanks.

**Comment by Mnkach** [comment]
See the answer here: https://github.com/RadeonOpenCompute/ROCm/issues/666.

**Comment by The-real-Han-Chen** [comment]
I see, thank you. I guess I have to try other things then.
