### ISSUE TITLE
Compilation error "undeclared inclusion(s) in rule '//tensorflow/core/kernels:softmax_op_gpu''" on ROCm 2.4 with TF 1.13.2-rocm

### ISSUE THREAD

**Issue by LaoFeng876** [ROCmSoftwarePlatform/tensorflow-upstream#732]
lease make sure that this is a build/installation issue. As per our GitHub Policy, we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    TensorFlow installed from (source or binary): source
    TensorFlow version: 1.13.2-rocm
    Python version: Python 3
    Installed using virtualenv? pip? conda?: conda
    Bazel version (if compiling from source): 0.15.2
    GCC/Compiler version (if compiling from source): 7.2.1
    ROCm/MIOpen version: rocm-2.4
    GPU model and memory: gfx900

Describe the problem
I tried to compile the tensorflow c++ api with bazel, and it occurs an undeclared inclusion(s) fault.The details are in below. 

Provide the exact sequence of commands / steps that you executed before running into the problem

Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR:/public/tensorflow-upstream-1.13.2/tensorflow/core/kernels/BUILD:3774:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:softmax_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/softmax_op_gpu.cu.cc':
  '/opt/rocm/hcc/lib/clang/10.0.0/include/stddef.h'
  '/opt/rocm/hcc/lib/clang/10.0.0/include/__stddef_max_align_t.h'
  '/opt/rocm/hcc/lib/clang/10.0.0/include/stdarg.h'
  '/opt/rocm/hcc/lib/clang/10.0.0/include/stdint.h'
  '/opt/rocm/hcc/lib/clang/10.0.0/include/limits.h'
clang-10: warning: /opt/rh/devtoolset-7/root/usr/bin/gcc: 'linker' input unused [-Wunused-command-line-argument]
clang-10: warning: /opt/rh/devtoolset-7/root/usr/bin/gcc: 'linker' input unused [-Wunused-command-line-argument]
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1019.499s, Critical Path: 692.84s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 4135 processes: 4135 local.
FAILED: Build did NOT complete successfully

**Comment by XuanBaby** [comment]
@LaoFeng876  hello  i meet the same error  , could you tell me how to solve this?
