### ISSUE TITLE
Available Tensorflow 1.15 for ROCm-2.10.0

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/tensorflow-upstream#736]
Tensorflow 1.14.x contains some functional bugs not related to ROCM, but fixed in 1.15.0. Currently there is no prebuilt Tensorflow 1.15 for ROCm-2.10.0 available in PYPI.
Tensorflow 1.15 for ROCm-2.9.0 is also an unstable version.

**Comment by sunway513** [comment]
Hi @ghostplant , we are waiting for the upstream TF maintainer to merge the PR that cherry-picked some RCCL enhancement, for details please refer to:
https://github.com/tensorflow/tensorflow/pull/34532
Tensorflow 1.15 whl package will be built from upstream [r1.15 branch](https://github.com/tensorflow/tensorflow/tree/r1.15) after the above PR got merged.
Thanks for the patience, I'll keep you posted in this thread.

**Comment by ghostplant** [comment]
@sunway513 Thanks!

**Comment by sunway513** [comment]
Hi @ghostplant , we have released the whl packages built with ROCm2.10 user bit, please take a look there and let us know your feedbacks if any:
https://pypi.org/project/tensorflow-rocm/1.15.0/

For PYPi release histories and compatibilities with ROCm versions, please refer to the following doc:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
