### ISSUE TITLE
Segmentation fault on import of tensorflow-rocm 2.0.2

### ISSUE THREAD

**Issue by seesturm** [ROCmSoftwarePlatform/tensorflow-upstream#766]
**System information**
- Ubuntu 18.04.03 LTS
- TensorFlow-rocm installed from: binary
- TensorFlow-rocm version: 2.0.2
- Python version: 3.6.9
- ROCm version: 2.10
- GPU model: gfx900 / Vega 10 XT / Radeon RX Vega 56

**Describe the current behavior**
When performing "import tensorflow" following is seen on console:
```
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

**Describe the expected behavior**
Tensorflow is imported correctly, e.g. as it was with tensorflow-rocm==2.0.1

**Code to reproduce the issue**
```python
#!/usr/bin/python3
import tensorflow
```

**Comment by sunway513** [comment]
Hi @seesturm , the issue seems related to your local configuration.
Can you try to pull the tensorflow-rocm docker containers and see if you can reproduce it there?
https://hub.docker.com/r/rocm/tensorflow

**Comment by seesturm** [comment]
I've googled a lot for this error message and found no conclusive information yet. I guess that it is even not python specific. After (re-)installation of rocm-3.0.6 and tensorflow-rocm-2.0.2 it works now. Would be really interesting to know what was the problem.

Whatever it was, apparently nothing is wrong with 2.0.2. So I'm closing this issue.
