### ISSUE TITLE
host_copt is forced to use march=haswell 

### ISSUE THREAD

**Issue by syoyo** [ROCmSoftwarePlatform/tensorflow-upstream#80]
We cannot change `host_copt` parameter by `configure`, since its hard coded in `configure.py`

```
  if not is_ppc64le() and not is_windows():
    write_to_bazelrc('build:opt --host_copt=-march=native')
```

This results to compilation error in some CPU architecture(e.g. KabyLake Celeron processor, pre-haswell CPU, and probably newer CPU architecture). Specifically, built `nasm` or `protoc` program failed to execute with `Illegal Instruction` error.

Is there any strong reason to use `march=haswell`? if not, it would be better to revert to use `march=native` as in `tensorflow` master(or it would be better to provide a way to change `host_copt` parameter from `configure` setting)

**Comment by sunway513** [comment]
Hi @syoyo , 
We hardcoded `march=haswell` because ROCm only supports CPU `haswell` or newer, please refer to ROCm document here:
`https://github.com/RadeonOpenCompute/ROCm#supported-cpus
`
Besides, TF can achieve better portability across different Linux flavors with this option.

**Comment by sunway513** [comment]
Hi @syoyo , `Haswell` is still a substantial requirement to run TF on ROCm, unfortunately.
Besides, neither of the two CPUs you mentioned are supported - SandyBridge is pre-Haswell, and Celeron family is not recommended. 
PR would be appreciated but just want you to know the above HW requirement.

**Comment by syoyo** [comment]
Close as PR #81 has been merged.
