### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by Bengt** [ROCmSoftwarePlatform/tensorflow-upstream#890]
Python 3.8 has was released on 2019-10-14, which is about 5 months ago:

<https://docs.python.org/3/whatsnew/3.8.html>

Python 3.9 is scheduled to be released on 2020-10-05, which is in about 7 months:

<https://www.python.org/dev/peps/pep-0596/>

There are no packages for Python 3.8, as of yet:

<https://pypi.org/project/tensorflow-rocm/2.1.0/#files>

Currently, Python 3.7 seems to have the broadest library support. However, this is changing quickly and Python 3.8 is becoming more relevant by the day. So to stay applicable for many use cases, tensorflow-rocm should support Python 3.8 with pre-built wheel packages.

**Comment by Bengt** [comment]
Here is a build which demonstrates the kind of errors one can encounter when using a non-supported python interpreter:

https://gitlab.com/pfasdr/code/main/-/jobs/471398301

```
ERROR: Could not find a version that satisfies the requirement tensorflow-rocm==2.1.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-rocm==2.1.0
```

**Comment by sunway513** [comment]
Hi @Bengt , in general, we would match the upstream Tensorflow support level. In the last Tensorflow 2.1 release, there's no Python 3.8 supported whl package yet:
https://pypi.org/project/tensorflow/#files
Can you create the issue on upstream Tensorflow repository instead?

**Comment by Bengt** [comment]
There are nightly builds for Python 3.8:

https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-599226072

So maybe try to match this support level, before it gets official with TensorFlow 2.2:

https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-603322215

**Comment by sunway513** [comment]
Hi @Bengt, we'll investigate and let you know. Thanks for bringing it to our attention!

**Comment by Bengt** [comment]
You are very welcome. Thanks for all your efforts!

**Comment by mihaimaruseac** [comment]
RC2 has py3.8 releases (except mac, due to an upstream issue)

**Comment by parallelo** [comment]
An update on this topic.  We are able to build Python 3.8 TF WHLs via our CI process.  However, our WHL files no longer fit within the limits set by the maintainers of PyPI, and they have not approved our request to host larger WHL files.  We are actively working on this blocker.

**Comment by Bengt** [comment]
Thanks for the update.

Wow, that is quite something. I guess, you are pushing the limits when the package index fails to handle your packages.

I do not see packages for Python 3.8 in the public Jenkins, though. Are you talking about another CI process, @parallelo? The last successful nightly is currently this one:

http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/271/

**Comment by parallelo** [comment]
Yes, these are still internal WHL builds.  We'll plan to make it public though.  Will update this thread when we do.  Sorry for the wait, and thanks for your patience.

**Comment by parallelo** [comment]
Okay, we've tested this on Py3.8 and have updated the public nightly build.  

This build has been kicked off: http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/274/

**Comment by parallelo** [comment]
The mentioned build with the Py3.8 artifact was successful.  Please give it a try, and give us feedback.

**Comment by parallelo** [comment]
Closing now that Python 3.8 WHLs exist in our [public nightly build](http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/).
