### ISSUE TITLE
*** stack smashing detected ***: <unknown> terminated Aborted (core dumped)

### ISSUE THREAD

**Issue by sumannelli-Ib** [ROCmSoftwarePlatform/tensorflow-upstream#897]
Hi Team,

**System information**
- OS Platform and Distribution: Ubuntu 18.04

- TensorFlow installed from (source or binary): pip install tensorflow-gpu==1.15.0
- TensorFlow version:1.15.
- Python version:3.6.69
- GCC/Compiler version (if compiling from source):8.3
- ROCm/MIOpen version:1.15.0(tensorflow_rocm-1.15.0-cp36-cp36m-manylinux1_x86_64.whl)
--
- GPU model and memory:AMD GPU vega 20

I am using AMD vega 20 gpu. This is working fine when running under tensorflow2.1.0 and rocm2.1 versions. But when I am working under tensorflow 1.15 with rocm-2.0 I am getting the above mentioned error.
I am running a object detection api of tensorflow model.
Also checked with basic keras model with mnist dataset, when using the model.fit() getting the bove error.

Please suggest me rocm compatible version with tensorflow 1.15.
Thanks

**Comment by sunway513** [comment]
Hi @sumannelli-Ib , please use the following document for compatibility information between tensorflow-rocm whl package with ROCm versions:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
