### ISSUE TITLE
MirroredStrategy working?

### ISSUE THREAD

**Issue by MarcelSimon** [ROCmSoftwarePlatform/tensorflow-upstream#932]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or
binary): pip tensorflow-rocm
- TensorFlow version (use command below): 2.1
- Python version: 3.7
- GPU model and memory: 4x Radeon VII

Could anybody confirm if the MirroredStrategy in ROCm Tensorflow 2.x is working? I came across this issue here and couldn't find any further information on distributed training with ROCm:
https://www.reddit.com/r/tensorflow/comments/esz6n1/rocm_tf21_mirroredstrategy_error/

Also, are there any benchmarks available for the performance scaling?

I am planning to build a multi GPU setup with Radeon VII cards and it would be good to know any issues before actually buying something ;) 

If it helps, here is a simple snipped for the kind of multi-GPU training:

```python
import psutil  # pip install psutil
import tensorflow as tf  # pip install tensorflow-gpu
import tensorflow_datasets as tfds  # pip install tensorflow-datasets

# Pre-processing functions
@tf.function
def _preprocess_data(img, label):
    img = tf.cast(img, tf.float32)
    img = tf.slice(img, [0, 0, 0], [112, 112, 3])
    img = tf.expand_dims(img, 0)
    label = tf.expand_dims(label, 0)
    return img, label

dataset = tfds.load('caltech_birds2011', split='train', as_supervised=True)
dataset = dataset.map(_preprocess_data)

mirrored_strategy = tf.distribute.MirroredStrategy(devices=["/gpu:0", "/gpu:1"])
with mirrored_strategy.scope(): 
    model = tf.keras.models.Sequential([
        tf.keras.layers.GlobalMaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(200)
    ])

    model.compile(
        optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy']
    )

def print_mem_usage(*args):
    print('Mem (MiB):', psutil.Process().memory_info().rss / (1024**2))
mem_log_cb = tf.keras.callbacks.LambdaCallback(on_epoch_end=print_mem_usage)
mirrored_strategy = tf.distribute.MirroredStrategy()

model.fit(
    dataset,
    epochs=100000,
    verbose=0,
    callbacks=[mem_log_cb]
)
```

Thanks!

**Comment by jeffdaily** [comment]
Can confirm that your sample code runs successfully on my mGPU system.  RadeonVII are supported.

**Comment by MarcelSimon** [comment]
I can confirm that everything runs flawlessly with near linear scaling on Threadripper 1920x, X399 board, and 4 Radeon VII.

Issue can be closed.
