### ISSUE TITLE
podman container work!

### ISSUE THREAD

**Issue by Djip007** [ROCmSoftwarePlatform/tensorflow-upstream#935]
First it is not a issue juste to report what work for me!
Because I use Fedora31 docker is a no way (cgroup v2 not supported) so I test with podman... and it work on stock kernel:
```
#> podman run -it \
    --network=host \
    --device=/dev/kfd \
    --device=/dev/dri \
    --ipc=host \
    --shm-size 16G \
    -v $PWD:/root/home\
    rocm/tensorflow:latest
```
work... no nead for sudo or any other option.

to be exact I use it with jupyterlab like that:
```
podman run --rm \
    --network=host \
    --device=/dev/kfd \
    --device=/dev/dri \
    --ipc=host \
    --shm-size 16G \
    -v $PWD:/root/home \
    rocm/tensorflow:latest bash -c \
    "python3 -m pip install jupyterlab pillow matplotlib && jupyter lab --allow-root"
```

so great job 

(note: for me it is with a RX560M ...)

May be it can work on other OS (centos8...) to and it can be add to the README.md for others.

**Comment by parallelo** [comment]
Many thanks for letting us know.  Happy to hear it!

**Comment by dcunited001** [comment]
@Djip007 thanks for sharing my dude!
