### ISSUE TITLE
depthwise_conv_op_test compute error

### ISSUE THREAD

**Issue by XuanBaby** [ROCmSoftwarePlatform/tensorflow-upstream#937]
**System information** 
images:   rocm/tensorflow:rocm3.3-tf1.15-dev

**Describe the current behavior**
python3 tensorflow/tensorflow/python/kernel_tests/depthwise_conv_op_test.py

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** 
the log is 
[dw_conv.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/4514223/dw_conv.log)

**Comment by sunway513** [comment]
Hi @XuanBaby , the unit test has been passing in our private CI and my local test.
Please use the following command to run the test, inside the rocm3.3-tf1.15-dev docker container:
`cd ~/tensorflow && bazel test -s --config=rocm //tensorflow/core/kernels:depthwise_conv_ops_test_gpu`
I've also attached the following log for your reference:
[depthwise_conv_op_test.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/4537437/depthwise_conv_op_test.log)
