### ISSUE TITLE
Linking of rule '@flatbuffers//:flatc' failed

### ISSUE THREAD

**Issue by Una-Tian** [ROCmSoftwarePlatform/tensorflow-upstream#938]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: tensorflow 2.2
- Python version: python3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): bazel 2.0.0
- GCC/Compiler version (if compiling from source): gcc 7.3.1
- ROCm/MIOpen version: rocm3.3
- GPU model and memory: 16G

**Describe the problem**
Bazel build failed when it got 7590 targets. 
ERROR: /public/home/tianlh/software/Tensorflow/bazel_out4096/external/flatbuffers/BUILD.bazel:64:1: Linking of rule '@flatbuffers//:flatc' failed (
Exit 1)
I tried a few times. The error always occurs at 7590th target around. Linking of rule faltbuffers or swig failed.  And the size of bazel-out is 3.6GB. I suspect something about the configuration is wrong. But I don't know why. Please help. thx.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
#build command:
TF_PKG_LOC=/public/home/tianlh/software/Tensorflow/tensorflow_pkg
rm -f $TF_PKG_LOC/tensorflow*.whl
yes "" | ROCM_PATH=/public/software/compiler/rocm/rocm-3.3.0 TF_NEED_ROCM=1 TF_ENABLE_XLA=1 PYTHON_BIN_PATH=/public/home/tianlh/software/Tensorflow/Python3.6.8/install/bin/python3 ./configure
bazel --output_base=/public/home/tianlh/software/Tensorflow/bazel_out4096 build --config=opt \
      --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures --local_ram_resources=4096 &&
bazel-bin/tensorflow/tools/pip_package/build_pip_package $TF_PKG_LOC &&
pip3 install --upgrade $TF_PKG_LOC/tensorflow*.whl

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
......... (a lot of output )..........
INFO: From Compiling tensorflow/core/framework/cpu_allocator_impl.cc [for host]:
tensorflow/core/framework/cpu_allocator_impl.cc: In member function 'virtual void* tensorflow::{anonymous}::CPUAllocator::AllocateRaw(size_t, size_
t)':
tensorflow/core/framework/cpu_allocator_impl.cc:78:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (num_bytes > LargeAllocationWarningBytes() &&
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: /public/home/tianlh/software/Tensorflow/bazel_out4096/external/flatbuffers/BUILD.bazel:64:1: Linking of rule '@flatbuffers//:flatc' failed (
Exit 1)
bazel-out/host/bin/external/flatbuffers/src/_objs/flatc/idl_gen_swift.o:idl_gen_swift.cpp:function flatbuffers::BaseGenerator::~BaseGenerator(): er
ror: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/flatbuffers/src/_objs/flatc/idl_gen_swift.o:idl_gen_swift.cpp:function std::basic_stringbuf<char, std::char_traits<char
>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/flatbuffers/src/_objs/flatc/idl_gen_swift.o:idl_gen_swift.cpp:function flatbuffers::swift::SwiftGenerator::~SwiftGenera
tor(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/flatbuffers/src/_objs/flatc/idl_gen_rust.o:idl_gen_rust.cpp:function flatbuffers::rust::RustGenerator::~RustGenerator()
: error: undefined reference to 'operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 792.765s, Critical Path: 580.83s
INFO: 7592 processes: 7592 local.
FAILED: Build did NOT complete successfully
(END)

**Comment by sunway513** [comment]
Hi @Una-Tian , current our CentOS support is limited to TF1.13. 
However, we're working on long term CentOS support plan, will update you when we have more details to share.

**Comment by Una-Tian** [comment]
OK. Thank you.
