### ISSUE TITLE
*** stack smashing detectedstack smashing detected***

### ISSUE THREAD

**Issue by asheetal** [ROCmSoftwarePlatform/tensorflow-upstream#941]
I get this crash in during model fit command. Any suggestion how should I go about debugging it

```
2020-04-23 20:10:25.949632: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-04-23 20:10:25.956241: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2498405000 Hz
2020-04-23 20:10:25.957806: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xad7dad0 executing computations on platform Host. Devices:
2020-04-23 20:10:25.957840: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-04-23 20:10:25.958988: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
*** *** stack smashing detectedstack smashing detected***  ***: ***  ***: stack smashing detected<unknown>stack smashing detected<unknown> ***:  terminated
```

tensorflow-rocm (1.14.2)
Keras (2.2.4)

**Comment by sunway513** [comment]
Hi @asheetal , which ROCm version are you using? Please provide the following logs:
`apt --installed list | grep rocm`
The error message implies the tensorflow-rocm version is not compatible to the ROCm version installed on your system, for compatibility information, please refer to the following doc:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

**Comment by asheetal** [comment]
Thanks @sunway513 for posting a response. I believe I have latest rocm (3.3) running on Centos 7
I will fix

rocm-bandwidth-test.x86_64                 1.4.0.13_rocm_rel_3.3_19_gf671f73-1
rocm-bandwidth-test3.3.0.x86_64            1.4.0.13_rocm_rel_3.3_19_gf671f73-1
rocm-clang-ocl.x86_64                      0.5.0.48_rocm_rel_3.3_19_fa039e7-1
rocm-clang-ocl3.3.0.x86_64                 0.5.0.48_rocm_rel_3.3_19_fa039e7-1
rocm-cmake.x86_64                          0.3.0.141_rocm_rel_3.3_19_1b9e698-1
rocm-cmake3.3.0.x86_64                     0.3.0.141_rocm_rel_3.3_19_1b9e698-1
rocm-debug-agent.x86_64                    1.0.0-1                @ROCm
rocm-debug-agent3.3.0.x86_64               1.0.0-1                @ROCm
rocm-dev.x86_64                            3.3.0_19-1             @ROCm
rocm-dev3.3.0.x86_64                       3.3.0_19-1             @ROCm
rocm-device-libs.x86_64                    1.0.0.565_rocm_rel_3.3_19_58abd89-1
rocm-device-libs3.3.0.x86_64               1.0.0.565_rocm_rel_3.3_19_58abd89-1
rocm-dkms.x86_64                           3.3.0_19-1             @ROCm
rocm-dkms3.3.0.x86_64                      3.3.0_19-1             @ROCm
rocm-libs.x86_64                           3.3.0_19-1             @ROCm
rocm-libs3.3.0.x86_64                      3.3.0_19-1             @ROCm
rocm-opencl.x86_64                         2.0.0-rocm_rel_3.3_19_363509c8d
rocm-opencl-devel.x86_64                   2.0.0-rocm_rel_3.3_19_363509c8d
rocm-opencl-devel3.3.0.x86_64              2.0.0-rocm_rel_3.3_19_363509c8d
rocm-opencl3.3.0.x86_64                    2.0.0-rocm_rel_3.3_19_363509c8d
rocm-smi.x86_64                            1.0.0_199_rocm_rel_3.3_19_ga9d6426-1
rocm-smi-lib64.x86_64                      2.2.0.3.rocm_rel_3.3_19_a482394-1
rocm-smi-lib643.3.0.x86_64                 2.2.0.3.rocm_rel_3.3_19_a482394-1
rocm-smi3.3.0.x86_64                       1.0.0_199_rocm_rel_3.3_19_ga9d6426-1
rocm-utils.x86_64                          3.3.0_19-1             @ROCm
rocm-utils3.3.0.x86_64                     3.3.0_19-1             @ROCm
rocm-validation-suite.x86_64               3.2.30300-1            @ROCm
rocm-validation-suite3.3.0.x86_64          3.2.30300-1            @ROCm
rocminfo.x86_64                            1.30300.0-1            @ROCm
rocminfo3.3.0.x86_64                       1.30300.0-1            @ROCm

**Comment by sunway513** [comment]
Hi @asheetal , for bare metal CentOS, our support is limited to TF1.13 at this moment. 
However, you can deploy our public ubuntu based docker containers for more recent TF versions:
https://hub.docker.com/r/rocm/tensorflow

**Comment by asheetal** [comment]
Hi @sunway513, Thanks for you URL you shared with me. I just upgraded my tensorflow-rocm to the compatible version based on that URL and my models are running great now on Centos 7. Thanks for this awesome project. I am a researcher on a shoestring budget and working on a bunch of AMD cards on Ebay. Buying Tesla and running Cuda is a distant dream.
